"use client";

import { useState } from "react";
import { toast } from "sonner";
import { useComplianceEvidence, useCreateComplianceControl, useCreateComplianceEvidence, useUpdateComplianceControl } from "@/features/organizations/api/organization-console-api";
import { GovernedActionButton } from "./GovernedActionButton";
import { OrgCard, OrgSectionTitle, OrgStatusBadge } from "./OrgPageShared";

const inputClass = "rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs";
type Control = { id: string; framework: "GDPR" | "SOC2" | "ISO27001" | "HIPAA" | "CUSTOM"; control_key: string; title: string; owner_user_id?: string | null; applicability: "APPLICABLE" | "NOT_APPLICABLE"; state: "NOT_ASSESSED" | "IN_PROGRESS" | "READY" | "GAP"; readiness_score?: number | null; review_due_at?: string | null; version: number };

function EvidencePanel({ orgId, control }: { orgId: string; control: Control }) {
  const evidence = useComplianceEvidence(orgId, control.id); const create = useCreateComplianceEvidence(orgId, control.id);
  const [draft, setDraft] = useState({ evidence_type: "DOCUMENT", storage_reference: "", checksum_sha256: "", classification: "CONFIDENTIAL" as "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED", reason: "" });
  const submit = async () => { try { await create.mutateAsync({ ...draft, collected_at: new Date().toISOString() }); setDraft({ evidence_type: "DOCUMENT", storage_reference: "", checksum_sha256: "", classification: "CONFIDENTIAL", reason: "" }); toast.success("Compliance evidence attached"); } catch (error) { toast.error(error instanceof Error ? error.message : "Evidence attachment failed"); } };
  return <div className="mt-3 border-t border-[var(--border-subtle)] pt-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">Evidence ({evidence.data?.items.length ?? 0})</p><div className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-5"><input aria-label="Evidence type" value={draft.evidence_type} onChange={event => setDraft(value => ({ ...value, evidence_type: event.target.value }))} className={inputClass} /><input aria-label="Evidence storage reference" value={draft.storage_reference} onChange={event => setDraft(value => ({ ...value, storage_reference: event.target.value }))} placeholder="Durable asset reference" className={inputClass} /><input aria-label="Evidence checksum" value={draft.checksum_sha256} onChange={event => setDraft(value => ({ ...value, checksum_sha256: event.target.value }))} placeholder="SHA-256 checksum" className={`${inputClass} font-mono`} /><select aria-label="Evidence classification" value={draft.classification} onChange={event => setDraft(value => ({ ...value, classification: event.target.value as typeof draft.classification }))} className={inputClass}>{["INTERNAL", "CONFIDENTIAL", "RESTRICTED"].map(value => <option key={value}>{value}</option>)}</select><input aria-label="Evidence reason" value={draft.reason} onChange={event => setDraft(value => ({ ...value, reason: event.target.value }))} placeholder="Administrative reason" className={inputClass} /></div><button disabled={draft.storage_reference.length < 3 || !/^[a-fA-F0-9]{64}$/.test(draft.checksum_sha256) || draft.reason.length < 12 || create.isPending} onClick={submit} className="mt-2 rounded-lg border border-[var(--brand-primary)] px-3 py-1.5 text-xs font-bold text-[var(--brand-primary)] disabled:opacity-40">Attach evidence reference</button><div className="mt-2 space-y-1">{evidence.data?.items.map((item: any) => <p key={item.id} className="font-mono text-[10px] text-[var(--text-tertiary)]">{item.evidence_type} · {item.storage_reference} · {String(item.checksum_sha256).slice(0, 12)}</p>)}</div></div>;
}

export function ComplianceControlsPanel({ orgId, controls }: { orgId: string; controls: Control[] }) {
  const create = useCreateComplianceControl(orgId); const update = useUpdateComplianceControl(orgId);
  const [draft, setDraft] = useState({ framework: "SOC2" as Control["framework"], control_key: "", title: "", reason: "" });
  const submit = async () => { try { await create.mutateAsync({ ...draft, applicability: "APPLICABLE", state: "NOT_ASSESSED" }); setDraft({ framework: "SOC2", control_key: "", title: "", reason: "" }); toast.success("Compliance control created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Control creation failed"); } };
  return <div className="space-y-4"><OrgCard><OrgSectionTitle>Create compliance control</OrgSectionTitle><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><select aria-label="Compliance framework" value={draft.framework} onChange={event => setDraft(value => ({ ...value, framework: event.target.value as Control["framework"] }))} className={inputClass}>{["GDPR", "SOC2", "ISO27001", "HIPAA", "CUSTOM"].map(value => <option key={value}>{value}</option>)}</select><input aria-label="Control key" value={draft.control_key} onChange={event => setDraft(value => ({ ...value, control_key: event.target.value }))} placeholder="Control key" className={inputClass} /><input aria-label="Control title" value={draft.title} onChange={event => setDraft(value => ({ ...value, title: event.target.value }))} placeholder="Control title" className={inputClass} /><input aria-label="Control creation reason" value={draft.reason} onChange={event => setDraft(value => ({ ...value, reason: event.target.value }))} placeholder="Administrative reason" className={inputClass} /></div><button disabled={!draft.control_key || draft.title.length < 2 || draft.reason.length < 12 || create.isPending} onClick={submit} className="mt-3 rounded-xl bg-[var(--brand-primary)] px-4 py-2 text-xs font-bold text-[var(--primary-contrast)] disabled:opacity-40">Create control</button></OrgCard>
    {controls.map(control => <OrgCard key={control.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold">{control.framework} · {control.control_key}</p><p className="text-xs text-[var(--text-secondary)]">{control.title}</p><p className="mt-1 font-mono text-[10px] text-[var(--text-tertiary)]">v{control.version} · review {control.review_due_at ? new Date(control.review_due_at).toLocaleDateString() : "not scheduled"}</p></div><div className="flex items-center gap-2"><OrgStatusBadge status={control.state} /><GovernedActionButton label="Advance review" title="Update compliance review state" requireCaseReference={false} className="text-[10px] font-bold text-[var(--brand-primary)]" onConfirm={({ reason }) => update.mutateAsync({ controlId: control.id, version: control.version, framework: control.framework, control_key: control.control_key, title: control.title, owner_user_id: control.owner_user_id ?? undefined, applicability: control.applicability, state: control.state === "READY" ? "IN_PROGRESS" : "READY", readiness_score: control.state === "READY" ? 50 : 100, review_due_at: control.review_due_at ?? undefined, reason }).then(() => undefined)} /></div></div><EvidencePanel orgId={orgId} control={control} /></OrgCard>)}
  </div>;
}
