"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Database, FolderLock, Loader2, ServerCog, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/lib/api-client";

type SetupStatus = { setup_required: boolean; administrator_created: boolean; security_ready: boolean; database_ready: boolean; installation?: { name: string; status: string } };

export default function SetupPage() {
  const router = useRouter(); const [status, setStatus] = useState<SetupStatus | null>(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ installation_name: "Primary Venue Server", admin_name: "", admin_email: "", admin_username: "", admin_password: "", storage_path: "C:\\ProgramData\\Eventos\\Venue\\Content", backup_path: "D:\\EventosBackups" });
  useEffect(() => { apiClient.get<SetupStatus>("/setup/status").then((value) => { setStatus(value); if (!value.setup_required) router.replace("/login"); }).catch((error) => toast.error(error.message)); }, [router]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await apiClient.post("/setup/bootstrap", form); toast.success("Venue Server initialized"); router.replace("/login"); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); } };
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="min-h-screen overflow-y-auto bg-[var(--base)] p-6 text-[var(--text)]"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between border-b border-[var(--border)] pb-5"><div><p className="venue-eyebrow">Local appliance initialization</p><h1 className="text-2xl font-semibold">Set up Venue Server</h1><p className="mt-1 text-sm text-[var(--muted)]">This wizard is accepted only from the Venue Server itself and can run once.</p></div><img src="/brand/eventos-emblem-metal.png" alt="Eventos" className="size-12 object-contain" /></header>
    <div className="mt-5 grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><section className="venue-section h-fit"><div className="venue-section-header"><div><h2>Readiness checks</h2><p>Installer prerequisites observed by the API</p></div></div><div className="divide-y divide-[var(--border)]">{[[Database, "Database connection", status?.database_ready], [ShieldCheck, "Unique installer secrets", status?.security_ready], [ServerCog, "Administrator not yet created", status ? !status.administrator_created : undefined], [FolderLock, "Local-only setup endpoint", true]].map(([Icon, label, ready]) => { const Component = Icon as typeof Database; return <div className="flex items-center gap-3 p-4" key={String(label)}><Component className="size-4 text-[var(--acc)]" /><span className="flex-1 text-xs font-semibold">{String(label)}</span>{ready === undefined ? <Loader2 className="size-4 animate-spin" /> : ready ? <CheckCircle2 className="size-4 text-[var(--success)]" /> : <span className="venue-state venue-state--bad">Required</span>}</div>; })}</div></section>
    <section className="venue-section"><div className="venue-section-header"><div><h2>Installation identity</h2><p>Create the first administrator and validate storage destinations</p></div></div><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-2">{[
      ["installation_name", "Installation name", "Primary Venue Server", "text"], ["admin_name", "Administrator name", "Full name", "text"], ["admin_email", "Administrator email", "name@example.com", "email"], ["admin_username", "Administrator username", "venue.admin", "text"], ["admin_password", "Administrator password", "At least 12 characters", "password"], ["storage_path", "Content storage path", "C:\\...", "text"], ["backup_path", "Backup destination", "D:\\...", "text"],
    ].map(([field, label, placeholder, type]) => <label className={field === "installation_name" || field === "storage_path" || field === "backup_path" ? "md:col-span-2 text-xs font-semibold text-[var(--muted)]" : "text-xs font-semibold text-[var(--muted)]"} key={field}>{label}<input className="venue-input mt-1" type={type} value={form[field as keyof typeof form]} onChange={(event) => update(field as keyof typeof form, event.target.value)} placeholder={placeholder} required /></label>)}<div className="md:col-span-2 flex items-center justify-between border-t border-[var(--border)] pt-4"><p className="max-w-md text-xs text-[var(--muted)]">Setup creates directories and performs a write test before committing the installation.</p><button className="venue-button venue-button--primary" disabled={busy || !status?.security_ready}>{busy ? <Loader2 className="size-4 animate-spin" /> : <ServerCog className="size-4" />}Initialize server</button></div></form></section></div></div></div>;
}
