"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, RefreshCw, RotateCcw, TimerReset } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/lib/api-client";
import { EmptyState, ErrorState, EvidenceTime, LoadingState, PageFrame, Section, StatusBadge } from "@/components/operations/control-room";

type Alert = { id: string; severity: string; status: string; source_type: string; source_id?: string; title: string; evidence: string; suggested_action?: string; recurrence_count: number; first_seen_at: string; last_seen_at: string; acknowledged_at?: string; resolved_at?: string; snoozed_until?: string };

export default function AlertsPage() {
  const client = useQueryClient(); const [state, setState] = useState("active");
  const query = useQuery({ queryKey: ["venue-alerts", state], queryFn: () => apiClient.get<{ items: Alert[] }>(`/venue/admin/control/alerts?state=${state}`), refetchInterval: 10000 });
  const action = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => apiClient.post(`/venue/admin/control/alerts/${id}/action`, { action, reason: `Operator ${action}`, snooze_minutes: action === "snooze" ? 30 : undefined }), onSuccess: () => { toast.success("Alert updated"); client.invalidateQueries({ queryKey: ["venue-alerts"] }); }, onError: (error: Error) => toast.error(error.message) });
  return <PageFrame eyebrow="Persistent exception queue" title="Alerts" description="Evidence remains visible across service restarts until an operator acknowledges or resolves it." actions={<button className="venue-button venue-button--secondary" onClick={() => query.refetch()}><RefreshCw className="size-4" />Refresh</button>}><Section title="Operational alerts" description={`${query.data?.items.length || 0} in ${state} state`}><div className="venue-toolbar"><select className="venue-input !w-52" value={state} onChange={(event) => setState(event.target.value)}><option value="active">Active</option><option value="acknowledged">Acknowledged</option><option value="snoozed">Snoozed</option><option value="resolved">Resolved</option></select></div>{query.isLoading && <LoadingState />}{query.isError && <ErrorState message={(query.error as Error).message} retry={() => query.refetch()} />}{query.data?.items.length === 0 && <EmptyState title={`No ${state} alerts`} detail="This is an authoritative empty state from the alert ledger." />}{!!query.data?.items.length && <div className="venue-table-wrap"><table className="venue-table"><thead><tr><th>Alert</th><th>Severity / state</th><th>Evidence</th><th>Recurrence</th><th>Last seen</th><th>Actions</th></tr></thead><tbody>{query.data.items.map((alert) => <tr key={alert.id}><td><strong>{alert.title}</strong><div className="venue-code">{alert.source_type} · {alert.source_id || "No source ID"}</div></td><td><div className="flex flex-col items-start gap-1"><StatusBadge state={alert.severity} /><StatusBadge state={alert.status} /></div></td><td className="max-w-md"><p>{alert.evidence}</p>{alert.suggested_action && <p className="mt-1 text-[var(--muted)]">Next: {alert.suggested_action}</p>}</td><td>{alert.recurrence_count}</td><td><EvidenceTime value={alert.last_seen_at} /></td><td><div className="flex gap-1">{alert.status === "active" && <><button title="Acknowledge" className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => action.mutate({ id: alert.id, action: "acknowledge" })}><Check className="size-3.5" /></button><button title="Snooze 30 minutes" className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => action.mutate({ id: alert.id, action: "snooze" })}><TimerReset className="size-3.5" /></button></>}<button title={alert.status === "resolved" ? "Reopen" : "Resolve"} className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => action.mutate({ id: alert.id, action: alert.status === "resolved" ? "reopen" : "resolve" })}><RotateCcw className="size-3.5" /></button></div></td></tr>)}</tbody></table></div>}</Section></PageFrame>;
}
