from __future__ import annotations

from typing import Protocol, TypeVar

from app.schemas.cursor_pagination import CursorPage

EntityT = TypeVar("EntityT")
ResultT = TypeVar("ResultT")


class RepositoryContract(Protocol[EntityT]):
    """Persistence contract; transaction ownership stays with the caller."""

    async def get_by_id(self, record_id, *, organization_id=None) -> EntityT | None: ...
    async def get_for_event(self, record_id, event_id, *, organization_id=None) -> EntityT | None: ...
    async def list_page(self, stmt, *, limit: int = 100) -> list[EntityT]: ...
    async def list_for_event(self, event_id, stmt=None, *, organization_id=None, limit: int = 100) -> list[EntityT]: ...
    async def cursor_page(self, stmt, *, limit: int = 20, cursor: str | None = None, cursor_column=None, descending: bool = False) -> CursorPage[EntityT]: ...
    async def count(self, stmt) -> int: ...
    async def exists(self, stmt) -> bool: ...
    async def count_for_event(self, event_id, *, organization_id=None) -> int: ...
    async def exists_for_event(self, event_id, *, organization_id=None) -> bool: ...
    def create(self, entity: EntityT) -> EntityT: ...
    def update(self, entity: EntityT, values: dict) -> EntityT: ...
    async def delete(self, entity: EntityT) -> None: ...
    def bulk_insert(self, entities: list[EntityT]) -> list[EntityT]: ...


class OrganizationRepositoryContract(Protocol[EntityT]):
    """Standard contract for organization-scoped resources without event IDs."""

    async def get_by_id(self, organization_id, record_id) -> EntityT | None: ...
    async def list_page(self, organization_id, *, offset: int = 0, limit: int = 100, **filters) -> list[EntityT]: ...
    async def count_for_organization(self, organization_id) -> int: ...
    async def exists_for_organization(self, organization_id, record_id) -> bool: ...
    async def update(self, entity: EntityT, values: dict) -> EntityT: ...
    async def delete(self, entity: EntityT) -> None: ...
    def create(self, entity: EntityT) -> EntityT: ...
    def bulk_insert(self, entities: list[EntityT]) -> list[EntityT]: ...


class QueryServiceContract(Protocol[ResultT]):
    """Screen-level read contract. Implementations must not mutate or commit."""

    async def execute(self, **filters) -> ResultT: ...


class CommandServiceContract(Protocol[ResultT]):
    """Use-case mutation contract with one application-owned transaction."""

    async def execute(self, **command) -> ResultT: ...
