'use client';

import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useRouter } from 'next/navigation';
import dynamic from 'next/dynamic';
import { AlertTriangle, Loader2, RefreshCw } from 'lucide-react';
import type { WebsiteProjectData, WebsiteBuilderStudioProps } from '@eventos/website-builder-studio/studio';
import { platformWebsiteTemplates, type WebsiteTemplateDraftRecord } from '@/services/website-template-builder-service';

// Dynamically import WebsiteBuilderStudio with SSR disabled for GrapesJS DOM compatibility
const WebsiteBuilderStudio = dynamic<WebsiteBuilderStudioProps>(
  () => import('@eventos/website-builder-studio/studio').then((mod) => mod.WebsiteBuilderStudio),
  {
    ssr: false,
    loading: () => (
      <div className="h-screen w-screen flex items-center justify-center bg-background text-foreground">
        <Loader2 className="h-8 w-8 text-primary animate-spin" />
        <span className="ml-3 font-semibold text-muted-foreground">Loading Command Center Website Studio...</span>
      </div>
    ),
  }
);

export default function CommandCenterWebsiteBuilderPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState<WebsiteTemplateDraftRecord | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [initialData, setInitialData] = useState<WebsiteProjectData | undefined>(undefined);
  const [loadAttempt, setLoadAttempt] = useState(0);
  const [portalReady, setPortalReady] = useState(false);
  const draftVersionRef = useRef<number>(1);

  useEffect(() => {
    setPortalReady(true);
  }, []);

  useEffect(() => {
    let mounted = true;

    async function loadMasterTemplate() {
      setLoading(true);
      setLoadError(null);
      try {
        const record = await platformWebsiteTemplates.getMasterDraft();
        if (!mounted) return;
        draftVersionRef.current = record.version;
        setDraft(record);
        setInitialData({
          id: record.template_id,
          name: record.name,
          document: record.document,
          siteSettings: record.document.site,
          assets: record.document.assets,
          theme: record.document.tokens.theme,
          updatedAt: record.updated_at,
        });
      } catch (error) {
        if (!mounted) return;
        console.error('[Command Center] Failed to load master website template:', error);
        setLoadError('The master website draft could not be loaded. Editing is paused to prevent unsynchronised template changes.');
      } finally {
        if (mounted) setLoading(false);
      }
    }

    loadMasterTemplate();
    return () => {
      mounted = false;
    };
  }, [loadAttempt]);

  const handleSaveMasterTemplate = async (data: WebsiteProjectData) => {
    if (!data.document) {
      throw new Error('Website document was not generated by the studio.');
    }
    let saved: WebsiteTemplateDraftRecord;
    try {
      saved = await platformWebsiteTemplates.saveMasterDraft(draftVersionRef.current || draft?.version || 1, data.document);
    } catch (error) {
      if ((error as { code?: string }).code !== 'WEBSITE_TEMPLATE_DRAFT_CONFLICT') throw error;

      // A recovered tab can hold a stale optimistic version even though it is
      // still the active editor. Refresh only the version, then retry once
      // with the local canonical document. A second conflict is surfaced.
      const latest = await platformWebsiteTemplates.getMasterDraft();
      draftVersionRef.current = latest.version;
      saved = await platformWebsiteTemplates.saveMasterDraft(latest.version, data.document);
    }
    draftVersionRef.current = saved.version;
    setDraft(saved);
    setInitialData({
      id: saved.template_id,
      name: saved.name,
      document: saved.document,
      siteSettings: saved.document.site,
      assets: saved.document.assets,
      theme: saved.document.tokens.theme,
      updatedAt: saved.updated_at,
    });
  };

  const handlePublishMasterTemplate = async (data: WebsiteProjectData) => {
    if (!data.document) {
      throw new Error('Website document was not generated by the studio.');
    }
    const validation = await platformWebsiteTemplates.validateMaster(data.document);
    if (!validation.valid) {
      alert('Publish validation failed. Fix the website diagnostics before publishing.');
      return;
    }
    await handleSaveMasterTemplate(data);
    await platformWebsiteTemplates.publishMaster();
    alert('Master template published globally for event organizers.');
  };

  const handleCreatePreview = async (data: WebsiteProjectData, previewId?: string) => {
    if (!data.document) throw new Error('Website document was not generated by the studio.');
    const preview = await platformWebsiteTemplates.createPreview(data.document, previewId);
    return {
      previewId: preview.preview_id,
      url: preview.url,
      expiresAt: preview.expires_at,
    };
  };

  const handleBack = () => {
    router.back();
  };

  if (loading) {
    return (
      <div className="h-screen w-screen flex items-center justify-center bg-background text-foreground">
        <Loader2 className="h-8 w-8 text-primary animate-spin" />
      </div>
    );
  }

  if (loadError || !initialData) {
    return (
      <main className="grid min-h-screen place-items-center bg-background px-6 text-foreground">
        <section className="w-full max-w-md border border-border bg-card p-6 shadow-sm">
          <AlertTriangle className="mb-4 h-6 w-6 text-amber-500" aria-hidden="true" />
          <h1 className="text-lg font-semibold">Website draft unavailable</h1>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">{loadError || 'No canonical website draft was returned.'}</p>
          <button
            type="button"
            onClick={() => setLoadAttempt(attempt => attempt + 1)}
            className="mt-5 inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground"
          >
            <RefreshCw className="h-4 w-4" aria-hidden="true" />
            Retry
          </button>
        </section>
      </main>
    );
  }

  if (!portalReady) return null;

  // Command Center layout uses a transformed content pane. Rendering the studio
  // into body keeps its fixed shell truly viewport-sized instead of clipped.
  return createPortal(
    <WebsiteBuilderStudio
      mode="GLOBAL_ADMIN"
      initialData={initialData}
      onSave={handleSaveMasterTemplate}
      onPublish={handlePublishMasterTemplate}
      onCreatePreview={handleCreatePreview}
      onSearchImages={platformWebsiteTemplates.searchOpenverse}
      onBack={handleBack}
    />,
    document.body,
  );
}
