"use client";

import { useParams } from "next/navigation";
import { useState } from "react";
import { Bell, Mail, MessageSquare, Send, Smartphone } from "lucide-react";
import { toast } from "sonner";
import { useArchiveNotificationChannel, useArchiveNotificationRule, useCreateNotificationChannel, useCreateNotificationRule, useOrganizationDomain, useUpdateNotificationChannel, useUpdateNotificationRule, useVerifyNotificationChannel } from "@/features/organizations/api/organization-console-api";
import { GovernedActionButton } from "@/features/organizations/components/GovernedActionButton";
import { LoadingPage, OrgCard, OrgDataTable, OrgMetricCard, OrgPageHeader, OrgSectionTitle, OrgStatusBadge, OrgTabBar, UnavailableDomain } from "@/features/organizations/components/OrgPageShared";

const CHANNEL_ICONS: Record<string, React.ElementType> = { EMAIL: Mail, SMS: MessageSquare, WHATSAPP: MessageSquare, PUSH: Bell, IN_APP: Smartphone };
const CHANNELS = ["EMAIL", "SMS", "WHATSAPP", "PUSH", "IN_APP", "WEBHOOK"] as const;

export default function NotificationsPageScreen() {
  const { orgId } = useParams<{ orgId: string }>();
  const [activeTab, setActiveTab] = useState("rules");
  const query = useOrganizationDomain(orgId, "notifications");
  const createRule = useCreateNotificationRule(orgId); const updateRule = useUpdateNotificationRule(orgId); const archiveRule = useArchiveNotificationRule(orgId);
  const createChannel = useCreateNotificationChannel(orgId); const updateChannel = useUpdateNotificationChannel(orgId); const archiveChannel = useArchiveNotificationChannel(orgId);
  const verifyChannel = useVerifyNotificationChannel(orgId);
  const [rule, setRule] = useState({ name: "", trigger_key: "", channel: "EMAIL" as typeof CHANNELS[number], recipients: "{}", reason: "" });
  const [channel, setChannel] = useState({ channel: "EMAIL" as typeof CHANNELS[number], provider: "", state: "CONFIGURED" as "UNAVAILABLE" | "CONFIGURED" | "ACTIVE" | "PAUSED" | "DEGRADED", secret_reference: "", configuration: "{}", reason: "" });
  if (query.isLoading) return <LoadingPage />;
  if (query.isError || !query.data?.availability?.available) return <UnavailableDomain reason={query.data?.availability?.reason ?? "Notification governance is unavailable."} />;
  const data = query.data.data as any; const rules: any[] = data.rules ?? []; const channels: any[] = data.channels ?? []; const deliveryBatches: any[] = data.delivery_batches ?? [];
  const createRuleNow = async () => { try { await createRule.mutateAsync({ name: rule.name, trigger_key: rule.trigger_key, channel: rule.channel, recipients: JSON.parse(rule.recipients), conditions: {}, escalation_policy: {}, is_enabled: true, reason: rule.reason }); setRule({ name: "", trigger_key: "", channel: "EMAIL", recipients: "{}", reason: "" }); toast.success("Notification rule created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Rule creation failed"); } };
  const createChannelNow = async () => { try { await createChannel.mutateAsync({ channel: channel.channel, provider: channel.provider, state: channel.state, secret_reference: channel.secret_reference || undefined, configuration: JSON.parse(channel.configuration), reason: channel.reason }); setChannel({ channel: "EMAIL", provider: "", state: "CONFIGURED", secret_reference: "", configuration: "{}", reason: "" }); toast.success("Notification channel configured"); } catch (error) { toast.error(error instanceof Error ? error.message : "Channel configuration failed"); } };
  return <div className="space-y-6 p-6"><OrgPageHeader icon={Send} title="Notifications" description="Organization-owned delivery rules and channel configuration; global provider policy remains in Developer Console." generatedAt={query.data.generated_at} />
    <div className="grid grid-cols-2 gap-4 md:grid-cols-4"><OrgMetricCard label="Channels" value={channels.length} /><OrgMetricCard label="Active channels" value={channels.filter(item => item.state === "ACTIVE").length} /><OrgMetricCard label="Rules" value={rules.length} /><OrgMetricCard label="Enabled rules" value={rules.filter(item => item.is_enabled).length} /></div>
    <OrgTabBar tabs={[{ key: "rules", label: "Notification Rules" }, { key: "channels", label: "Channels" }, { key: "deliveries", label: "Provider Deliveries" }]} active={activeTab} onChange={setActiveTab} />
    {activeTab === "rules" && <div className="space-y-4"><OrgCard><OrgSectionTitle>Create notification rule</OrgSectionTitle><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-5"><input aria-label="Rule name" value={rule.name} onChange={event => setRule(value => ({ ...value, name: event.target.value }))} placeholder="Rule name" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /><input aria-label="Trigger key" value={rule.trigger_key} onChange={event => setRule(value => ({ ...value, trigger_key: event.target.value }))} placeholder="event.registration.approved" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /><select aria-label="Rule channel" value={rule.channel} onChange={event => setRule(value => ({ ...value, channel: event.target.value as typeof rule.channel }))} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs">{CHANNELS.map(value => <option key={value}>{value}</option>)}</select><input aria-label="Recipient policy JSON" value={rule.recipients} onChange={event => setRule(value => ({ ...value, recipients: event.target.value }))} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 font-mono text-xs" /><input aria-label="Rule creation reason" value={rule.reason} onChange={event => setRule(value => ({ ...value, reason: event.target.value }))} placeholder="Administrative reason" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /></div><button disabled={rule.name.length < 2 || rule.trigger_key.length < 2 || rule.reason.length < 12 || createRule.isPending} onClick={createRuleNow} className="mt-3 rounded-xl bg-[var(--brand-primary)] px-4 py-2 text-xs font-bold text-[var(--primary-contrast)] disabled:opacity-40">Create rule</button></OrgCard>
      <OrgDataTable columns={[{ key: "name", header: "Rule", render: (item: any) => <div><p className="text-xs font-bold">{item.name}</p><p className="font-mono text-[10px] text-[var(--text-tertiary)]">{item.trigger_key}</p></div> }, { key: "channel", header: "Channel", render: (item: any) => <OrgStatusBadge status={item.channel} /> }, { key: "status", header: "Status", render: (item: any) => <OrgStatusBadge status={item.is_enabled ? "ENABLED" : "DISABLED"} /> }, { key: "actions", header: "Actions", render: (item: any) => <div className="flex gap-2"><GovernedActionButton label={item.is_enabled ? "Disable" : "Enable"} title={`${item.is_enabled ? "Disable" : "Enable"} notification rule`} requireCaseReference={false} className="text-[10px] font-bold text-[var(--brand-primary)]" onConfirm={({ reason }) => updateRule.mutateAsync({ ruleId: item.id, version: item.version, name: item.name, trigger_key: item.trigger_key, channel: item.channel, recipients: item.recipients ?? {}, conditions: item.conditions ?? {}, escalation_policy: item.escalation_policy ?? {}, is_enabled: !item.is_enabled, template_id: item.template_id ?? undefined, reason }).then(() => undefined)} /><GovernedActionButton label="Archive" title="Archive notification rule" requireCaseReference={false} confirmationText={item.name} className="text-[10px] font-bold text-[var(--status-danger)]" onConfirm={({ reason }) => archiveRule.mutateAsync({ ruleId: item.id, version: item.version, reason }).then(() => undefined)} /></div> }]} rows={rules} keyFn={(item: any) => item.id} emptyMessage="No notification rules configured" /></div>}
    {activeTab === "channels" && <div className="space-y-4"><OrgCard><OrgSectionTitle>Configure organization channel</OrgSectionTitle><p className="mt-1 text-xs text-[var(--text-tertiary)]">Secrets use deployment-injected <span className="font-mono">env://VARIABLE</span> references and are never returned. SMS uses TWILIO, WhatsApp uses META_CLOUD, and push uses EXPO. A provider becomes active only after Command Center verification.</p><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><select aria-label="Channel type" value={channel.channel} onChange={event => setChannel(value => ({ ...value, channel: event.target.value as typeof channel.channel }))} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs">{CHANNELS.map(value => <option key={value}>{value}</option>)}</select><input aria-label="Provider" value={channel.provider} onChange={event => setChannel(value => ({ ...value, provider: event.target.value }))} placeholder="TWILIO, META_CLOUD, or EXPO" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /><select aria-label="Channel state" value={channel.state} onChange={event => setChannel(value => ({ ...value, state: event.target.value as typeof channel.state }))} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs">{["UNAVAILABLE", "CONFIGURED", "PAUSED", "DEGRADED"].map(value => <option key={value}>{value}</option>)}</select><input aria-label="Secret reference" value={channel.secret_reference} onChange={event => setChannel(value => ({ ...value, secret_reference: event.target.value }))} placeholder="env://EVENTOS_PROVIDER_SECRET" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /><input aria-label="Channel configuration JSON" value={channel.configuration} onChange={event => setChannel(value => ({ ...value, configuration: event.target.value }))} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 font-mono text-xs" /><input aria-label="Channel configuration reason" value={channel.reason} onChange={event => setChannel(value => ({ ...value, reason: event.target.value }))} placeholder="Administrative reason" className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-3)] px-3 py-2 text-xs" /></div><button disabled={channel.provider.length < 2 || channel.reason.length < 12 || createChannel.isPending} onClick={createChannelNow} className="mt-3 rounded-xl bg-[var(--brand-primary)] px-4 py-2 text-xs font-bold text-[var(--primary-contrast)] disabled:opacity-40">Configure channel</button></OrgCard>
      <div className="grid gap-3 md:grid-cols-2">{channels.map(item => { const Icon = CHANNEL_ICONS[item.channel] ?? Bell; return <OrgCard key={item.id}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Icon className="h-4 w-4 text-[var(--brand-primary)]" /><div><p className="text-xs font-bold">{item.channel} · {item.provider}</p><p className="font-mono text-[10px] text-[var(--text-tertiary)]">v{item.version} · secret {item.secret_reference_present ? "configured" : "not exposed"} · verified {item.last_verified_at ? new Date(item.last_verified_at).toLocaleString() : "never"}</p></div></div><OrgStatusBadge status={item.state} /></div><div className="mt-3 flex gap-2">{item.state === "ACTIVE" ? <GovernedActionButton label="Pause" title="Pause notification channel" requireCaseReference={false} className="text-[10px] font-bold text-[var(--brand-primary)]" onConfirm={({ reason }) => updateChannel.mutateAsync({ channelId: item.id, version: item.version, channel: item.channel, provider: item.provider, state: "PAUSED", configuration: item.configuration ?? {}, reason }).then(() => undefined)} /> : <GovernedActionButton label="Verify & activate" title="Verify and activate notification channel" requireCaseReference className="text-[10px] font-bold text-[var(--brand-primary)]" onConfirm={({ reason, caseReference }) => verifyChannel.mutateAsync({ channelId: item.id, version: item.version, reason, caseReference }).then(() => undefined)} />}<GovernedActionButton label="Archive" title="Archive notification channel" requireCaseReference={false} confirmationText={item.channel} className="text-[10px] font-bold text-[var(--status-danger)]" onConfirm={({ reason }) => archiveChannel.mutateAsync({ channelId: item.id, version: item.version, reason }).then(() => undefined)} /></div></OrgCard>; })}</div>{channels.length === 0 && <p className="rounded-xl border border-[var(--border-default)] p-6 text-center text-xs text-[var(--text-tertiary)]">No channels configured.</p>}</div>}
    {activeTab === "deliveries" && <OrgDataTable columns={[{ key: "channel", header: "Channel", render: (item: any) => <div><p className="text-xs font-bold">{item.channel}</p><p className="text-[10px] text-[var(--text-tertiary)]">{item.provider}</p></div> }, { key: "status", header: "Status", render: (item: any) => <OrgStatusBadge status={item.status} /> }, { key: "counts", header: "Delivery", render: (item: any) => <p className="text-xs">{item.accepted_count} accepted · {item.failed_count} failed · {item.requested_count} requested</p> }, { key: "event", header: "Event", render: (item: any) => <p className="font-mono text-[10px]">{item.event_id}</p> }, { key: "created", header: "Created", render: (item: any) => <p className="text-xs">{new Date(item.created_at).toLocaleString()}</p> }]} rows={deliveryBatches} keyFn={(item: any) => item.id} emptyMessage="No provider delivery batches recorded" />}
  </div>;
}
