import { FormTemplate } from "./types";

export const DEFAULT_FORM_TEMPLATES: FormTemplate[] = [
  // ── 1. Standard Event Registration Form (Default System Form) ───────────
  {
    id: "tpl_standard_registration",
    name: "Standard Event Registration Form",
    slug: "standard-event-registration",
    category_key: "registration",
    category_name: "Registration Form",
    description: "The complete enterprise conference attendee registration questionnaire with identity verification, institutional profile, country selector, and registration category.",
    scope_type: "GLOBAL",
    is_default: true,
    is_system: true,
    is_active: true,
    version: 1,
    settings: {
      submit_button_label: "Complete Registration",
      success_title: "Registration Confirmed!",
      success_message: "Your registration has been successfully processed. Check your email for badge credentials and schedule details.",
      terms_and_conditions: "By submitting this form, you acknowledge and agree to the Conference Code of Conduct, Privacy Policy, and on-site badge scanning terms.",
      include_default_faqs: true,
    },
    fields: [
      {
        id: "title",
        name: "title",
        label: "Title / Prefix",
        type: "select",
        is_default: true,
        is_required: false,
        is_active: true,
        sort_order: 0,
        placeholder: "Select title",
        options: ["Dr.", "Prof.", "Mr.", "Ms.", "Mrs."],
        grid_width: "third",
        category: "identity",
      },
      {
        id: "first_name",
        name: "first_name",
        label: "First Name",
        type: "text",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 1,
        placeholder: "Enter your first name",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "last_name",
        name: "last_name",
        label: "Last Name",
        type: "text",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 2,
        placeholder: "Enter your last name",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "email",
        name: "email",
        label: "Email Address",
        type: "email",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 3,
        placeholder: "attendee@example.com",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "phone",
        name: "phone",
        label: "Phone Number",
        type: "phone",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 4,
        placeholder: "Enter mobile number",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "company",
        name: "company",
        label: "Institution / Organization",
        type: "text",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 5,
        placeholder: "Enter institution, university, or organization",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "designation",
        name: "designation",
        label: "Job Title / Designation",
        type: "text",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 6,
        placeholder: "e.g. Senior Consultant / Resident / Lead Engineer",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "country",
        name: "country",
        label: "Country & State",
        type: "country",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 7,
        placeholder: "Select your country",
        options: [],
        grid_width: "full",
        category: "identity",
      },
      {
        id: "role",
        name: "role",
        label: "Registration Role / Category",
        type: "select",
        is_default: true,
        is_required: true,
        is_active: true,
        sort_order: 8,
        placeholder: "Select your role category",
        options: ["Delegate", "Postgraduate Student", "Faculty / Speaker", "Corporate Sponsor"],
        grid_width: "half",
        category: "identity",
      },
    ],
  },

  // ── 2. Scientific & Academic Abstract Submission Form ──────────────────
  {
    id: "tpl_abstract_submission",
    name: "Scientific & Academic Abstract Submission",
    slug: "scientific-abstract-submission",
    category_key: "abstract",
    category_name: "Abstract Form",
    description: "Standard academic call-for-papers intake with author affiliations, presentation preference, structured abstract text, keywords, and manuscript upload.",
    scope_type: "GLOBAL",
    is_default: false,
    is_system: true,
    is_active: true,
    version: 1,
    settings: {
      submit_button_label: "Submit Abstract for Review",
      success_title: "Abstract Submitted Successfully!",
      success_message: "Your submission has been queued for peer review by the Scientific Committee. You will receive review notifications via email.",
      terms_and_conditions: "Authors certify that this work is original, has not been published elsewhere, and all co-authors consent to presentation.",
    },
    fields: [
      {
        id: "abstract_title",
        name: "abstract_title",
        label: "Abstract / Paper Title",
        type: "text",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 0,
        placeholder: "Enter the full title of your research paper or case study",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "presentation_format",
        name: "presentation_format",
        label: "Preferred Presentation Format",
        type: "radio",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 1,
        options: ["Oral Podium Presentation", "ePoster Display", "Workshop Demo", "Either Oral or Poster"],
        grid_width: "full",
        category: "choice",
      },
      {
        id: "scientific_track",
        name: "scientific_track",
        label: "Conference Topic / Track",
        type: "select",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 2,
        options: ["Clinical Cardiology", "AI in Diagnostics", "Genomics & Oncology", "Medical Ethics & Policy", "General Medicine"],
        placeholder: "Choose relevant track...",
        grid_width: "half",
        category: "choice",
      },
      {
        id: "primary_author",
        name: "primary_author",
        label: "Lead / Presenting Author",
        type: "text",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 3,
        placeholder: "Dr. Jane Doe, MD",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "co_authors",
        name: "co_authors",
        label: "Co-Authors & Institutional Affiliations",
        type: "textarea",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 4,
        placeholder: "List co-authors and their institutions (e.g. John Smith - Harvard Medical School, ...)",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "abstract_body",
        name: "abstract_body",
        label: "Structured Abstract Text (Max 500 words)",
        type: "textarea",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 5,
        placeholder: "Background, Methods, Results, and Conclusion...",
        help_text: "Structured format recommended: Background, Objective, Methodology, Results, Conclusion.",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "keywords",
        name: "keywords",
        label: "Keywords (comma separated)",
        type: "text",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 6,
        placeholder: "e.g. Machine Learning, Echocardiography, Risk Stratification",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "manuscript_file",
        name: "manuscript_file",
        label: "Upload Full Paper / Manuscript Draft",
        type: "file",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 7,
        help_text: "PDF or DOCX format, up to 25MB.",
        grid_width: "full",
        category: "media",
      },
    ],
  },

  // ── 3. Post-Event Attendee Feedback & CSAT Survey ─────────────────────
  {
    id: "tpl_attendee_survey",
    name: "Post-Event Attendee Feedback & CSAT Survey",
    slug: "post-event-attendee-survey",
    category_key: "survey",
    category_name: "Survey Form",
    description: "Measure delegate satisfaction, evaluate keynote lectures, gather venue facilities feedback, and calculate Net Promoter Score (NPS).",
    scope_type: "GLOBAL",
    is_default: false,
    is_system: true,
    is_active: true,
    version: 1,
    settings: {
      submit_button_label: "Submit Feedback",
      success_title: "Thank You for Your Feedback!",
      success_message: "Your responses help us improve future conferences. Your participation certificate is ready for download.",
    },
    fields: [
      {
        id: "overall_rating",
        name: "overall_rating",
        label: "How would you rate your overall conference experience?",
        type: "rating",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 0,
        grid_width: "full",
        category: "media",
      },
      {
        id: "sessions_quality",
        name: "sessions_quality",
        label: "Quality & Relevance of Scientific Sessions",
        type: "select",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 1,
        options: ["Exceeded Expectations", "Met Expectations", "Needs Improvement", "Poor"],
        grid_width: "half",
        category: "choice",
      },
      {
        id: "venue_facilities",
        name: "venue_facilities",
        label: "Venue & Hospitality Rating (AV, Catering, Logistics)",
        type: "select",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 2,
        options: ["Excellent", "Good", "Average", "Poor"],
        grid_width: "half",
        category: "choice",
      },
      {
        id: "nps_score",
        name: "nps_score",
        label: "How likely are you to recommend this conference to a peer or colleague?",
        type: "nps",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 3,
        help_text: "0 = Not likely at all, 10 = Extremely likely",
        grid_width: "full",
        category: "media",
      },
      {
        id: "favorite_talk",
        name: "favorite_talk",
        label: "Which keynote session or workshop did you find most valuable?",
        type: "text",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 4,
        placeholder: "Speaker name or session title...",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "improvements",
        name: "improvements",
        label: "What can we do to make next year's conference even better?",
        type: "textarea",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 5,
        placeholder: "Share suggestions for topics, workshops, timing, networking...",
        grid_width: "full",
        category: "basic",
      },
    ],
  },

  // ── 4. Speaker Bio & Presentation Intake Form ─────────────────────────
  {
    id: "tpl_speaker_intake",
    name: "Speaker Bio & Presentation Deck Intake",
    slug: "speaker-bio-presentation-intake",
    category_key: "speaker_intake",
    category_name: "Speaker Intake Form",
    description: "Streamlined speaker onboarding collecting verified bio, headshot photo, session AV requirements, and presentation slides upload.",
    scope_type: "GLOBAL",
    is_default: false,
    is_system: true,
    is_active: true,
    version: 1,
    settings: {
      submit_button_label: "Save Speaker Profile",
      success_title: "Profile & Materials Uploaded!",
      success_message: "Your speaker bio and slides have been submitted to the AV and program technical desk for review.",
    },
    fields: [
      {
        id: "speaker_full_name",
        name: "speaker_full_name",
        label: "Speaker Full Name & Honorifics",
        type: "text",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 0,
        placeholder: "Prof. John Doe, MD, PhD, FACC",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "speaker_bio",
        name: "speaker_bio",
        label: "Professional Biography (100-200 words)",
        type: "textarea",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 1,
        placeholder: "Include current roles, research focus, and major accolades...",
        grid_width: "full",
        category: "basic",
      },
      {
        id: "headshot_image",
        name: "headshot_image",
        label: "Official Headshot Photo",
        type: "image",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 2,
        help_text: "High-resolution portrait photo (PNG/JPG, minimum 800x800px).",
        grid_width: "half",
        category: "media",
      },
      {
        id: "av_requirements",
        name: "av_requirements",
        label: "Audio / Visual & Stage Requirements",
        type: "checkbox",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 3,
        options: ["Lapel / Lavalier Mic", "Confidence Monitor", "Macbook Adapter / HDMI", "Audio playback in slides", "Live Software Demo"],
        grid_width: "half",
        category: "choice",
      },
      {
        id: "presentation_deck",
        name: "presentation_deck",
        label: "Final Presentation Slides (PPTX / PDF)",
        type: "file",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 4,
        help_text: "Aspect ratio 16:9 widescreen recommended (Up to 100MB).",
        grid_width: "full",
        category: "media",
      },
    ],
  },

  // ── 5. VIP Gala Dinner & Social RSVP Form ─────────────────────────────
  {
    id: "tpl_gala_dinner_rsvp",
    name: "VIP Gala Dinner & Social Evening RSVP",
    slug: "vip-gala-dinner-rsvp",
    category_key: "registration",
    category_name: "Registration Form",
    description: "Exclusive evening dinner RSVP capturing attendance confirmation, plus-one credentials, dietary preferences, and seating choices.",
    scope_type: "GLOBAL",
    is_default: false,
    is_system: true,
    is_active: true,
    version: 1,
    settings: {
      submit_button_label: "Confirm Gala RSVP",
      success_title: "RSVP Confirmed!",
      success_message: "Your banquet table allocation and invitation pass have been registered.",
    },
    fields: [
      {
        id: "attending_status",
        name: "attending_status",
        label: "Will you be attending the Presidential Gala Dinner?",
        type: "radio",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 0,
        options: ["Yes, I will attend", "Regretfully, I cannot attend"],
        grid_width: "full",
        category: "choice",
      },
      {
        id: "plus_one_name",
        name: "plus_one_name",
        label: "Accompanying Guest / Spouse Full Name (if applicable)",
        type: "text",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 1,
        placeholder: "Guest Full Name",
        grid_width: "half",
        category: "basic",
      },
      {
        id: "dietary_preference",
        name: "dietary_preference",
        label: "Dietary Preferences & Allergies",
        type: "select",
        is_default: false,
        is_required: true,
        is_active: true,
        sort_order: 2,
        options: ["No Restrictions (Standard Non-Veg)", "Vegetarian", "Vegan", "Jain Meal", "Gluten-Free", "Halal", "Kosher"],
        grid_width: "half",
        category: "choice",
      },
      {
        id: "special_requests",
        name: "special_requests",
        label: "Accessibility or Seating Notes",
        type: "textarea",
        is_default: false,
        is_required: false,
        is_active: true,
        sort_order: 3,
        placeholder: "Wheelchair access, table preference with colleagues, etc.",
        grid_width: "full",
        category: "basic",
      },
    ],
  },
];

export function getTemplateById(id: string): FormTemplate | undefined {
  return DEFAULT_FORM_TEMPLATES.find((t) => t.id === id || t.slug === id);
}

export function getTemplatesByCategory(categoryKey: string): FormTemplate[] {
  if (categoryKey === "all") return DEFAULT_FORM_TEMPLATES;
  return DEFAULT_FORM_TEMPLATES.filter((t) => t.category_key === categoryKey);
}
