"use client";
import type { ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { BarChart3, Calendar, CreditCard, Download, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { apiClient, apiGet } from "@/lib/api-client";
import { MetricCard } from "../OrganiserPrimitives";
import { OrganiserSection, Unavailable } from "../OrganiserSection";
export type ReportData = { metrics: Record<string, number | null>; trend: Array<Record<string, any>>; events: Array<Record<string, any>>; total: number; page: number; page_size: number; freshness_at: string | null; source: string };
export type ReportDomain = "overview" | "registrations" | "revenue" | "engagement" | "events";
export const reportTabs = [["Overview", "/dashboard/analytics/overview"], ["Registrations", "/dashboard/analytics/registrations"], ["Revenue", "/dashboard/analytics/revenue"], ["Engagement", "/dashboard/analytics/engagement"], ["Events", "/dashboard/analytics/events"], ["Exports", "/dashboard/analytics/exports"], ["Custom", "/dashboard/analytics/custom"]].map(([label, href]) => ({ label, href }));
export function ReportsPage({ data, error, actions, children }: { data?: ReportData; error?: boolean; actions?: ReactNode; children: ReactNode }) { const metrics = data?.metrics || {}; return <OrganiserSection title="Reports & Analytics" description="Track organisation-wide registration, revenue, engagement, and event performance." tabs={reportTabs} actions={actions}>{error ? <Unavailable>This report is unavailable from the organisation analytics read model.</Unavailable> : null}<div className="op-metric-grid"><MetricCard label="Registrations" value={metrics.total_registrations ?? "Unavailable"} tone="rose" icon={<Users className="h-5 w-5" />} /><MetricCard label="Revenue" value={metrics.total_revenue != null ? new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(metrics.total_revenue) : "Unavailable"} tone="purple" icon={<CreditCard className="h-5 w-5" />} /><MetricCard label="Active events" value={metrics.active_events ?? "Unavailable"} tone="amber" icon={<Calendar className="h-5 w-5" />} /><MetricCard label="Engagement" value={metrics.engagement_pct != null ? `${metrics.engagement_pct}%` : "Unavailable"} tone="green" icon={<BarChart3 className="h-5 w-5" />} /></div>{children}<p className="text-xs text-[var(--op-subtle)]">Source: {data?.source || "Unavailable"} · Freshness: {data?.freshness_at ? new Date(data.freshness_at).toLocaleString() : "Unavailable"}</p></OrganiserSection>; }
export function useReportDomain(domain: ReportDomain, page = 1, pageSize = 10) { return useQuery({ queryKey: ["organiser-reports", domain, page, pageSize], queryFn: () => apiGet<ReportData>(`/organiser/reports/${domain}?page=${page}&page_size=${pageSize}`) }); }
export function ReportExportAction({ domain }: { domain: ReportDomain }) { const create = useMutation({ mutationFn: () => apiClient.post<any>("/organiser/reports/exports", { domain, format: "csv" }, { headers: { "Idempotency-Key": crypto.randomUUID() } }), onSuccess: async (result) => { toast.success("Report export is ready."); try { await downloadReport(result.id); } catch { toast.error("Report download failed."); } }, onError: (error: any) => toast.error(error?.message || "Report export failed.") }); return <Button onClick={() => create.mutate()} disabled={create.isPending}><Download className="mr-2 h-4 w-4" />{create.isPending ? "Preparing..." : "Export CSV"}</Button>; }
export const reportMoney = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
export async function downloadReport(id: string) { const storage = localStorage.getItem("obsidian-auth-storage"); const token = storage ? JSON.parse(storage)?.state?.accessToken : null; const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000"}/api/v1/organiser/reports/exports/${id}/download`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("Download failed"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `organiser-report-${id}.csv`; anchor.click(); URL.revokeObjectURL(url); }
