"use client";

import { EmailBuilderStudio, type StudioAsset, type StudioDraft, type StudioFragment, type StudioTemplate } from "@eventos/email-builder-studio";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

import { eventEmailAssets, eventEmailComponents, eventEmailTemplates, type EmailAssetRecord, type EmailFragmentRecord, type EmailStudioRecord } from "@/services/email-template-studio-service";
import { uploadEmailAsset } from "@/services/email-service";

const VARIABLES = [{ key: "{{EventName}}", label: "Event name", required: true }, { key: "{{SpeakerName}}", label: "Speaker name" }, { key: "{{UploadLink}}", label: "Upload link" }, { key: "{{EventDate}}", label: "Event date" }, { key: "{{EventVenue}}", label: "Venue" }];
const map = (row: EmailStudioRecord): StudioTemplate => ({ id: row.id, name: row.name, subject: row.subject, preheader: row.preheader ?? "", stableKey: row.stable_key, scopeType: row.scope_type, lifecycleState: row.lifecycle_state, version: row.version, designerJson: (row.designer_json as { root?: unknown } | null)?.root ? row.designer_json as StudioTemplate["designerJson"] : null, bodyHtml: row.body_html, editable: row.editable, effectiveOrigin: row.effective_origin, fallbackReason: row.fallback_reason });

export function EventEmailStudio({ eventId }: { eventId: string }) {
  const [rows, setRows] = useState<EmailStudioRecord[]>([]); const [fragmentRows, setFragmentRows] = useState<EmailFragmentRecord[]>([]); const [assetRows, setAssetRows] = useState<EmailAssetRecord[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [result, savedFragments, savedAssets] = await Promise.all([eventEmailTemplates.list(eventId), eventEmailComponents.list(eventId), eventEmailAssets.list(eventId)]); setRows(result); setFragmentRows(savedFragments); setAssetRows(savedAssets); setActiveId((current) => current && result.some((row) => row.id === current) ? current : result[0]?.id ?? null); } catch (error) { toast.error(error instanceof Error ? error.message : "Email templates are unavailable."); } finally { setLoading(false); } }, [eventId]);
  useEffect(() => { void load(); }, [load]);
  const replace = (saved: EmailStudioRecord, priorId: string) => { setRows((current) => [saved, ...current.filter((row) => row.id !== priorId && row.id !== saved.id)]); setActiveId(saved.id); };
  const save = async (draft: StudioDraft) => { const saved = await eventEmailTemplates.saveDraft(eventId, draft.templateId, draft.expectedVersion, { name: draft.name, subject: draft.subject, preheader: draft.preheader ?? "", body_html: draft.bodyHtml, designer_json: draft.designerJson, editor_schema_version: draft.editorSchemaVersion }); replace(saved, draft.templateId); };
  const publish = async (template: StudioTemplate, reason: string) => { setBusy(true); try { replace(await eventEmailTemplates.publish(eventId, template.id, template.version, reason.trim()), template.id); toast.success("Event email template published."); } catch (error) { toast.error(error instanceof Error ? error.message : "Template could not be published."); } finally { setBusy(false); } };
  const preview = async (draft: StudioDraft) => { const result = await eventEmailTemplates.preview(eventId, draft.templateId, { name: draft.name, subject: draft.subject, preheader: draft.preheader ?? "", body_html: draft.bodyHtml, designer_json: draft.designerJson, editor_schema_version: draft.editorSchemaVersion }); return { html: result.html, plainText: result.plain_text, diagnostics: result.diagnostics }; };
  const sendTest = async (draft: StudioDraft, recipient: string) => { await eventEmailTemplates.testSend(eventId, draft.templateId, recipient, { name: draft.name, subject: draft.subject, preheader: draft.preheader ?? "", body_html: draft.bodyHtml, designer_json: draft.designerJson, editor_schema_version: draft.editorSchemaVersion }); toast.success(`Test email queued for ${recipient}.`); };
  const saveFragment = async (fragment: { name: string; componentKind: "BLOCK" | "SECTION"; documentFragment: Record<string, unknown> }) => { const stableKey = `${fragment.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "fragment"}-${Date.now().toString(36)}`; const saved = await eventEmailComponents.create(eventId, { name: fragment.name, stable_key: stableKey, component_kind: fragment.componentKind, category: "saved", document_fragment: fragment.documentFragment, preview_metadata: {} }); setFragmentRows((current) => [saved, ...current]); toast.success("Reusable email fragment saved."); };
  const fragments: StudioFragment[] = fragmentRows.map((row) => ({ id: row.id, name: row.name, category: row.category, componentKind: row.component_kind, scopeType: row.scope_type, documentFragment: row.document_fragment, editable: row.editable }));
  const assets: StudioAsset[] = assetRows.map((row) => ({ id: row.id, name: row.name, url: row.url, fileType: row.file_type, scopeType: row.scope_type, assetKind: row.asset_kind, sourceType: row.source_type, width: row.width ?? undefined, height: row.height ?? undefined, metadata: row.metadata }));
  const upload = async (file: File, assetKind: "IMAGE" | "ICON" = "IMAGE") => { const saved = await uploadEmailAsset(eventId, file); setAssetRows((current) => [{ ...saved, scope_type: "EVENT", asset_kind: assetKind, source_type: "UPLOAD" }, ...current]); return saved.url; };
  const templates = useMemo(() => rows.map(map), [rows]);
  if (loading) return <div className="grid h-full min-h-0 flex-1 place-items-center text-sm text-muted-foreground">Loading email production desk…</div>;
  return <EmailBuilderStudio templates={templates} fragments={fragments} assets={assets} activeTemplateId={activeId} variables={VARIABLES} scopeLabel="Event design studio" busy={busy} readOnly={!templates.some((template) => template.editable)} onSelectTemplate={setActiveId} onSaveDraft={save} onPublish={publish} onPreview={preview} onSendTest={sendTest} onSaveFragment={saveFragment} onUploadAsset={upload} />;
}
