"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { orgApi } from "@/components/organizer/org/org-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiClient, apiGet } from "@/lib/api-client";
import { Panel } from "../OrganiserPrimitives";
import { Unavailable } from "../OrganiserSection";
import { SettingsPage } from "./shared";
export function SettingsBrandingTab() { const client = useQueryClient(); const org = useQuery({ queryKey: ["organisation", "me"], queryFn: orgApi.me }); const query = useQuery({ queryKey: ["organisation-settings", "branding"], queryFn: () => apiGet<any>("/organiser/settings/branding") }); const [brand, setBrand] = useState({ logo_url: "", primary_color: "#6366f1", secondary_color: "#8b5cf6" }); useEffect(() => { const data = org.data?.organization; if (data) setBrand({ logo_url: data.logo_url || "", primary_color: data.primary_color || "#6366f1", secondary_color: data.secondary_color || "#8b5cf6" }); }, [org.data]); const save = useMutation({ mutationFn: () => apiClient.put("/organiser/settings/branding", { logo_url: brand.logo_url.trim() || null, primary_color: brand.primary_color, secondary_color: brand.secondary_color }, { headers: { "If-Match": String(query.data?.profile?.version || 0) } }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["organisation-settings", "branding"] }), client.invalidateQueries({ queryKey: ["organisation", "me"] })]); toast.success("Branding settings saved."); }, onError: (reason: any) => toast.error(reason?.message || "Branding settings could not be saved.") }); return <SettingsPage actions={<Button disabled={save.isPending || query.isError} onClick={() => save.mutate()}>{save.isPending ? "Saving..." : "Save branding"}</Button>}>{query.isError ? <Unavailable>Branding settings are unavailable.</Unavailable> : null}<Panel title="Branding settings"><div className="op-form-grid"><label>Logo URL<Input value={brand.logo_url} onChange={(event) => setBrand({ ...brand, logo_url: event.target.value })} placeholder="https://..." /></label>{(["primary_color", "secondary_color"] as const).map((key) => <label key={key}>{key === "primary_color" ? "Primary colour" : "Secondary colour"}<div className="flex gap-2"><input aria-label={key} type="color" className="h-10 w-12 rounded-md border border-[var(--op-border)]" value={brand[key]} onChange={(event) => setBrand({ ...brand, [key]: event.target.value })} /><Input value={brand[key]} onChange={(event) => setBrand({ ...brand, [key]: event.target.value })} /></div></label>)}</div><dl className="op-detail-list mt-5"><dt>Profile status</dt><dd>{query.data?.profile?.status || "Not configured"}</dd><dt>Published version</dt><dd>{query.data?.profile?.published_version || "Not published"}</dd></dl></Panel></SettingsPage>; }
