"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clipboard, Download, KeyRound, Plus, RefreshCw, RotateCcw, ShieldCheck, ShieldOff } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/lib/api-client";
import { EmptyState, ErrorState, EvidenceTime, LoadingState, PageFrame, Section, StatusBadge } from "@/components/operations/control-room";

type ApiKey = { id: string; name: string; key_prefix: string; source_url: string; scopes: string[]; allowed_cidrs: string[]; expires_at?: string; revoked_at?: string; grace_until?: string; last_used_at?: string; last_used_ip?: string; usage_count: number; created_at: string; api_key?: string; api_key_visible_once?: boolean };

export default function RegistrationAccessPage() {
  const client = useQueryClient(); const [name, setName] = useState("Registration Server"); const [cidrs, setCidrs] = useState(""); const [revealed, setRevealed] = useState<ApiKey | null>(null);
  const query = useQuery({ queryKey: ["registration-api-keys"], queryFn: () => apiClient.get<{ event_id: string | null; source_url: string; state: string; items: ApiKey[] }>("/venue/admin/registration-api-keys") });
  const refresh = () => client.invalidateQueries({ queryKey: ["registration-api-keys"] });
  const create = useMutation({ mutationFn: () => apiClient.post<ApiKey>("/venue/admin/registration-api-keys", { name, allowed_cidrs: cidrs.split(",").map((item) => item.trim()).filter(Boolean) }), onSuccess: (key) => { setRevealed(key); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const rotate = useMutation({ mutationFn: (id: string) => apiClient.post<ApiKey>(`/venue/admin/registration-api-keys/${id}/rotate`, {}), onSuccess: (key) => { setRevealed(key); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const revoke = useMutation({ mutationFn: (id: string) => apiClient.post(`/venue/admin/registration-api-keys/${id}/revoke`, { reason: "Revoked from Venue Server console" }), onSuccess: () => { toast.success("Key revoked"); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const test = useMutation({ mutationFn: (id: string) => apiClient.post<{ ready: boolean }>(`/venue/admin/registration-api-keys/${id}/test`, {}), onSuccess: (result) => result.ready ? toast.success("Credential configuration is ready") : toast.error("Credential configuration failed readiness checks"), onError: (error: Error) => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); toast.success("Copied to clipboard"); };
  const downloadPackage = async () => { const payload = await apiClient.get<Record<string, unknown>>("/venue/admin/registration-api-keys/connection-package"); const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "eventos-registration-connection.json"; link.click(); URL.revokeObjectURL(url); };
  return <PageFrame eyebrow="Registration trust boundary" title="Registration API access" description="Issue event-bound machine credentials for Registration Server fetch, delta, heartbeat and idempotent operation push." actions={<><button className="venue-button venue-button--secondary" onClick={downloadPackage}><Download className="size-4" />Connection package</button><button className="venue-button venue-button--secondary" onClick={() => query.refetch()}><RefreshCw className="size-4" />Refresh</button></>}>
    {revealed?.api_key && <section className="border border-[var(--warn)] bg-[color-mix(in_srgb,var(--warn)_8%,var(--card))] p-4" style={{ borderRadius: 6 }}><div className="flex items-start gap-3"><KeyRound className="mt-0.5 size-5 text-[var(--warn)]" /><div className="min-w-0 flex-1"><strong className="text-sm">Store this secret now</strong><p className="mt-1 text-xs text-[var(--muted)]">It is shown once and cannot be recovered from Venue Server.</p><div className="mt-3 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto border border-[var(--border)] bg-[var(--inset)] p-3 font-mono text-xs select-text">{revealed.api_key}</code><button className="venue-button venue-button--secondary" onClick={() => copy(revealed.api_key!)}><Clipboard className="size-4" />Copy</button></div><button className="mt-3 text-xs font-semibold text-[var(--acc)]" onClick={() => setRevealed(null)}><Check className="mr-1 inline size-3.5" />I stored the secret</button></div></div></section>}
    <Section title="Issue credential" description={query.data?.event_id ? "Default scopes allow snapshot and delta reads plus heartbeat and operation writes" : "Bind exactly one event before issuing Registration credentials"}><form className="grid gap-3 p-4 md:grid-cols-[minmax(220px,.6fr)_minmax(300px,1fr)_auto]" onSubmit={submit}><input className="venue-input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Registration server name" disabled={!query.data?.event_id} /><input className="venue-input font-mono" value={cidrs} onChange={(event) => setCidrs(event.target.value)} placeholder="Optional CIDRs: 10.10.0.0/16, 192.168.1.20/32" disabled={!query.data?.event_id} /><button className="venue-button venue-button--primary" disabled={create.isPending || !query.data?.event_id}><Plus className="size-4" />Create key</button></form></Section>
    <Section title="Active and historical credentials" description={query.data ? `Source endpoint: ${query.data.source_url}` : "Loading source endpoint"}>{query.isLoading && <LoadingState />}{query.isError && <ErrorState message={(query.error as Error).message} retry={() => query.refetch()} />}{query.data?.items.length === 0 && <EmptyState title="No Registration credentials" detail="Create one for each Registration Server installation." />}{!!query.data?.items.length && <div className="venue-table-wrap"><table className="venue-table"><thead><tr><th>Credential</th><th>State</th><th>Scopes / networks</th><th>Last use</th><th>Created</th><th>Control</th></tr></thead><tbody>{query.data.items.map((key) => <tr key={key.id}><td><strong>{key.name}</strong><div className="venue-code">{key.key_prefix}…</div></td><td><StatusBadge state={key.revoked_at ? "offline" : key.expires_at && new Date(key.expires_at) <= new Date() ? "stale" : "healthy"} evidence={key.revoked_at ? `Revoked ${key.revoked_at}` : key.expires_at ? `Expires ${key.expires_at}` : "No expiry"} />{key.grace_until && <div className="venue-code">Rotation grace to {new Date(key.grace_until).toLocaleTimeString()}</div>}</td><td><div className="max-w-sm text-[11px]">{key.scopes.join(", ")}</div><div className="venue-code">{key.allowed_cidrs.length ? key.allowed_cidrs.join(", ") : "Any trusted subnet address"}</div></td><td><EvidenceTime value={key.last_used_at} /><div className="venue-code">{key.last_used_ip || "No source IP"} · {key.usage_count} uses</div></td><td><EvidenceTime value={key.created_at} /></td><td><div className="flex gap-1"><button disabled={!!key.revoked_at} title="Rotate key" className="venue-button venue-button--secondary !h-8 !px-2 disabled:opacity-35" onClick={() => rotate.mutate(key.id)}><RotateCcw className="size-3.5" /></button><button disabled={!!key.revoked_at} title="Revoke key" className="venue-button venue-button--danger !h-8 !px-2 disabled:opacity-35" onClick={() => revoke.mutate(key.id)}><ShieldOff className="size-3.5" /></button></div></td></tr>)}</tbody></table></div>}</Section>
  </PageFrame>;
}
