"use client";

import { useRevenueMetrics } from "@/services/super-admin-service";
import { TrendingUp, RefreshCw, DollarSign, BarChart3 } from "lucide-react";
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

export default function RevenueAnalyticsPage() {
  const { data: metrics = [], isLoading, refetch } = useRevenueMetrics(12);

  const totalMrr = metrics.at(-1)?.mrr || 0;
  const totalArr = totalMrr * 12;
  const growthRate = metrics.length >= 2
    ? ((metrics.at(-1)!.mrr - metrics.at(-2)!.mrr) / (metrics.at(-2)!.mrr || 1)) * 100
    : 0;

  return (
    <div className="space-y-5 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-2xl bg-emerald-500/10 border border-emerald-500/20">
            <TrendingUp className="w-6 h-6 text-emerald-400" />
          </div>
          <div>
            <h1 className="text-xl font-black text-white">Revenue Analytics</h1>
            <p className="text-[11px] text-white/35">MRR/ARR trends across the platform</p>
          </div>
        </div>
        <button onClick={() => refetch()} className="p-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors text-white/40 hover:text-white">
          <RefreshCw className={`w-4 h-4 ${isLoading ? "animate-spin" : ""}`} />
        </button>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { label: "Current MRR", value: formatCurrency(totalMrr), icon: DollarSign, color: "text-emerald-400" },
          { label: "Current ARR", value: formatCurrency(totalArr), icon: TrendingUp, color: "text-violet-400" },
          { label: "MoM Growth", value: `${growthRate >= 0 ? "+" : ""}${growthRate.toFixed(1)}%`, icon: BarChart3, color: growthRate >= 0 ? "text-emerald-400" : "text-red-400" },
        ].map(({ label, value, icon: Icon, color }) => (
          <div key={label} className="rounded-2xl border border-white/5 bg-white/3 p-5">
            <div className="flex items-center justify-between mb-3">
              <p className="text-[10px] font-bold uppercase tracking-widest text-white/30">{label}</p>
              <Icon className={`w-4 h-4 ${color}`} />
            </div>
            <p className={`text-2xl font-black tabular-nums ${color}`}>{value}</p>
          </div>
        ))}
      </div>

      {/* MRR Chart */}
      {isLoading ? (
        <div className="flex items-center gap-2 text-white/30 p-8">
          <RefreshCw className="w-4 h-4 animate-spin" /> Loading revenue data…
        </div>
      ) : metrics.length === 0 ? (
        <div className="rounded-2xl border border-white/5 bg-white/3 p-12 text-center text-white/20 text-sm">
          No revenue data yet. Revenue metrics are generated by the billing engine.
        </div>
      ) : (
        <>
          <div className="rounded-2xl border border-white/5 bg-white/3 p-5">
            <h3 className="text-sm font-black text-white mb-1">Monthly Recurring Revenue</h3>
            <p className="text-[10px] text-white/30 mb-5">Last 12 months · USD</p>
            <ResponsiveContainer width="100%" height={220}>
              <AreaChart data={metrics} margin={{ top: 5, right: 5, left: 0, bottom: 0 }}>
                <defs>
                  <linearGradient id="mrrArea" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" />
                <XAxis dataKey="period" tick={{ fontSize: 9, fill: "rgba(255,255,255,0.3)" }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 9, fill: "rgba(255,255,255,0.3)" }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${(v/1000).toFixed(0)}k`} />
                <Tooltip
                  contentStyle={{ background: "rgba(15,15,20,0.95)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, fontSize: 11 }}
                  formatter={(v: any) => [formatCurrency(v), "MRR"]}
                />
                <Area type="monotone" dataKey="mrr" stroke="#10b981" fill="url(#mrrArea)" strokeWidth={2} dot={{ r: 3, fill: "#10b981" }} />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          {/* Add-on Revenue */}
          <div className="rounded-2xl border border-white/5 bg-white/3 p-5">
            <h3 className="text-sm font-black text-white mb-5">Add-on Revenue by Period</h3>
            <ResponsiveContainer width="100%" height={160}>
              <BarChart data={metrics} margin={{ top: 5, right: 5, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                <XAxis dataKey="period" tick={{ fontSize: 9, fill: "rgba(255,255,255,0.3)" }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 9, fill: "rgba(255,255,255,0.3)" }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v}`} />
                <Tooltip contentStyle={{ background: "rgba(15,15,20,0.95)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, fontSize: 11 }} formatter={(v: any) => [formatCurrency(v), "Add-on"]} />
                <Bar dataKey="addon_revenue" fill="#8b5cf6" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </>
      )}
    </div>
  );
}
