"""add recording rights to file and poster

Revision ID: 0ed6e2bcf9c8
Revises: 35d286bdf37f
Create Date: 2026-05-07 10:40:26.751398+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed6e2bcf9c8'
down_revision: Union[str, None] = '35d286bdf37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posters', sa.Column('recording_rights', sa.String(length=20), nullable=True))
    op.add_column('presentation_files', sa.Column('recording_rights', sa.String(length=20), nullable=True))
    op.add_column('speakers', sa.Column('speaker_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_speakers_speaker_code'), 'speakers', ['speaker_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speakers_speaker_code'), table_name='speakers')
    op.alter_column('speakers', 'speaker_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('presentation_files', 'recording_rights')
    op.drop_column('posters', 'recording_rights')
    # ### end Alembic commands ###
