"""Add webhooks table and event settings columns

Revision ID: 9433ef8cf3fe
Revises: 62e9dc5f53be
Create Date: 2026-04-23 15:00:24.804911+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9433ef8cf3fe'
down_revision: Union[str, None] = '62e9dc5f53be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('subscribed_events', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_reason', sa.Text(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_created_at'), 'webhooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhooks_event_id'), 'webhooks', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhooks_status'), 'webhooks', ['status'], unique=False)
    op.add_column('events', sa.Column('theme_color', sa.String(length=20), nullable=False))
    op.add_column('events', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('license_tier', sa.String(length=30), nullable=False))
    op.add_column('events', sa.Column('feature_toggles', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'feature_toggles')
    op.drop_column('events', 'license_tier')
    op.drop_column('events', 'logo_url')
    op.drop_column('events', 'theme_color')
    op.drop_index(op.f('ix_webhooks_status'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_event_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_created_at'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
