"""add job_type to import_jobs

Revision ID: a13e6a82c057
Revises: 45072c36760e
Create Date: 2026-05-02 08:11:46.463681+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13e6a82c057'
down_revision: Union[str, None] = '45072c36760e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('job_type', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_import_jobs_job_type'), 'import_jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_job_type'), table_name='import_jobs')
    op.drop_column('import_jobs', 'job_type')
    # ### end Alembic commands ###
