"""add_session_id_to_posters

Revision ID: 731712219e26
Revises: a13e6a82c057
Create Date: 2026-05-02 08:26:45.606561+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731712219e26'
down_revision: Union[str, None] = 'a13e6a82c057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posters', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_posters_session_id'), 'posters', ['session_id'], unique=False)
    op.create_foreign_key(None, 'posters', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posters', type_='foreignkey')
    op.drop_index(op.f('ix_posters_session_id'), table_name='posters')
    op.drop_column('posters', 'session_id')
    # ### end Alembic commands ###
