"""add_advanced_metadata_fields

Revision ID: 35d286bdf37f
Revises: 9c18f74110d2
Create Date: 2026-05-06 09:10:25.901295+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35d286bdf37f'
down_revision: Union[str, None] = '9c18f74110d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_validations', sa.Column('image_count', sa.Integer(), nullable=False))
    op.add_column('file_validations', sa.Column('video_count', sa.Integer(), nullable=False))
    op.add_column('file_validations', sa.Column('animation_count', sa.Integer(), nullable=False))
    op.add_column('file_validations', sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('file_validations', sa.Column('is_bundle', sa.Boolean(), nullable=False))
    op.add_column('file_validations', sa.Column('bundle_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_validations', 'bundle_contents')
    op.drop_column('file_validations', 'is_bundle')
    op.drop_column('file_validations', 'technical_metadata')
    op.drop_column('file_validations', 'animation_count')
    op.drop_column('file_validations', 'video_count')
    op.drop_column('file_validations', 'image_count')
    # ### end Alembic commands ###
