"""Initial schema

Revision ID: 81dd6aec5840
Revises: 
Create Date: 2026-08-19 11:20:28.988167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81dd6aec5840'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for schema in ("identity", "events", "registration", "presentations", "venue"):
        op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_organizations_slug'), 'organizations', ['slug'], unique=True, schema='identity')
    op.create_table('venue_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('allowed_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_venue_users_email'), 'venue_users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_venue_users_organization_id'), 'venue_users', ['organization_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_venue_users_role'), 'venue_users', ['role'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_venue_users_username'), 'venue_users', ['username'], unique=True, schema='identity')
    op.create_table('kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('distributed_quantity', sa.Integer(), nullable=False),
    sa.Column('max_per_participant', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_name'),
    schema='venue'
    )
    op.create_table('printers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_table('registration_source_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('allowed_app', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_registration_source_api_keys_hash'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_registration_source_api_keys_event_id'), 'registration_source_api_keys', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_registration_source_api_keys_key_prefix'), 'registration_source_api_keys', ['key_prefix'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_registration_source_api_keys_organization_id'), 'registration_source_api_keys', ['organization_id'], unique=False, schema='venue')
    op.create_table('sync_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_table('venue_checkin_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_name', sa.String(length=255), nullable=False),
    sa.Column('gate_type', sa.String(length=100), nullable=False),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_checkins_per_delegate', sa.Integer(), nullable=False),
    sa.Column('gate_capacity', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('updated_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_table('venue_operational_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('allowed_payment_statuses_for_checkin', sa.JSON(), nullable=False),
    sa.Column('allowed_payment_statuses_for_print', sa.JSON(), nullable=False),
    sa.Column('allowed_payment_statuses_for_self_checkin', sa.JSON(), nullable=False),
    sa.Column('require_paid_for_checkin', sa.Boolean(), nullable=False),
    sa.Column('require_paid_for_print', sa.Boolean(), nullable=False),
    sa.Column('require_paid_for_self_checkin', sa.Boolean(), nullable=False),
    sa.Column('require_checkin_for_print', sa.Boolean(), nullable=False),
    sa.Column('require_checkin_for_kit', sa.Boolean(), nullable=False),
    sa.Column('require_primary_checkin_for_companions', sa.Boolean(), nullable=False),
    sa.Column('max_badge_reprints', sa.Integer(), nullable=False),
    sa.Column('allow_self_checkin_reprints', sa.Boolean(), nullable=False),
    sa.Column('max_self_checkin_reprints', sa.Integer(), nullable=False),
    sa.Column('allow_self_checkin_profile_edit', sa.Boolean(), nullable=False),
    sa.Column('limit_single_kit_per_delegate', sa.Boolean(), nullable=False),
    sa.Column('max_companions_per_delegate', sa.Integer(), nullable=False),
    sa.Column('allow_admin_override', sa.Boolean(), nullable=False),
    sa.Column('custom_rules', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('organizer_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('upload_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('allowed_formats', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('event_mode', sa.Boolean(), nullable=False),
    sa.Column('license_tier', sa.String(length=30), nullable=False),
    sa.Column('feature_toggles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('speaker_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registration_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('branding_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['identity.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_index(op.f('ix_events_events_created_at'), 'events', ['created_at'], unique=False, schema='events')
    op.create_index(op.f('ix_events_events_organization_id'), 'events', ['organization_id'], unique=False, schema='events')
    op.create_index(op.f('ix_events_events_short_code'), 'events', ['short_code'], unique=True, schema='events')
    op.create_index(op.f('ix_events_events_status'), 'events', ['status'], unique=False, schema='events')
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('screen_count', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('av_technician', sa.String(length=150), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_index(op.f('ix_events_rooms_event_id'), 'rooms', ['event_id'], unique=False, schema='events')
    op.create_table('speakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('upload_token', sa.String(length=128), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_speakers_created_at'), 'speakers', ['created_at'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_speakers_email'), 'speakers', ['email'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_speakers_event_id'), 'speakers', ['event_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_speakers_upload_status'), 'speakers', ['upload_status'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_speakers_upload_token'), 'speakers', ['upload_token'], unique=True, schema='presentations')
    op.create_table('participant_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_participant_roles_event_id'), 'participant_roles', ['event_id'], unique=False, schema='registration')
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('regno', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('paid_status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_participants_email'), 'participants', ['email'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_participants_event_id'), 'participants', ['event_id'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_participants_regno'), 'participants', ['regno'], unique=False, schema='registration')
    op.create_table('event_report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('revision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.venue_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['venue.event_report_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'version', name='uq_event_report_snapshot_version'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_event_report_snapshots_event_id'), 'event_report_snapshots', ['event_id'], unique=False, schema='venue')
    op.create_table('print_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=30), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_print_templates_event_id'), 'print_templates', ['event_id'], unique=False, schema='venue')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('session_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moderator_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['events.rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_index(op.f('ix_events_sessions_event_id'), 'sessions', ['event_id'], unique=False, schema='events')
    op.create_index(op.f('ix_events_sessions_room_id'), 'sessions', ['room_id'], unique=False, schema='events')
    op.create_index(op.f('ix_events_sessions_session_code'), 'sessions', ['session_code'], unique=False, schema='events')
    op.create_index(op.f('ix_events_sessions_start_time'), 'sessions', ['start_time'], unique=False, schema='events')
    op.create_index(op.f('ix_events_sessions_status'), 'sessions', ['status'], unique=False, schema='events')
    op.create_table('posters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_screen', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['presentations.speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_posters_display_screen'), 'posters', ['display_screen'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_posters_event_id'), 'posters', ['event_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_posters_speaker_id'), 'posters', ['speaker_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_posters_status'), 'posters', ['status'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_posters_submitted_at'), 'posters', ['submitted_at'], unique=False, schema='presentations')
    op.create_table('companions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('primary_participant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('badge_code', sa.String(length=50), nullable=True),
    sa.Column('badge_status', sa.String(length=30), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dietary_preference', sa.String(length=50), nullable=True),
    sa.Column('special_assistance', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_participant_id'], ['registration.participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_companions_event_id'), 'companions', ['event_id'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_companions_primary_participant_id'), 'companions', ['primary_participant_id'], unique=False, schema='registration')
    op.create_table('participant_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('dietary_preference', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['registration.participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_participant_extensions_participant_id'), 'participant_extensions', ['participant_id'], unique=True, schema='registration')
    op.create_table('participant_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('registration_status', sa.String(length=50), nullable=False),
    sa.Column('registration_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['registration.participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_participant_registrations_event_id'), 'participant_registrations', ['event_id'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_participant_registrations_participant_id'), 'participant_registrations', ['participant_id'], unique=False, schema='registration')
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('nfc_uid', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['registration.participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['venue.print_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_badges_badge_code'), 'badges', ['badge_code'], unique=True, schema='venue')
    op.create_index(op.f('ix_venue_badges_nfc_uid'), 'badges', ['nfc_uid'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_badges_participant_id'), 'badges', ['participant_id'], unique=False, schema='venue')
    op.create_table('event_report_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=True),
    sa.Column('data_scope', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.venue_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['venue.event_report_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_event_report_audit_action'), 'event_report_audit', ['action'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_event_report_audit_created_at'), 'event_report_audit', ['created_at'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_event_report_audit_event_id'), 'event_report_audit', ['event_id'], unique=False, schema='venue')
    op.create_table('participant_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['venue.kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['registration.participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_participant_kits_kit_id'), 'participant_kits', ['kit_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_participant_kits_participant_id'), 'participant_kits', ['participant_id'], unique=False, schema='venue')
    op.create_table('room_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['events.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_room_devices_device_type'), 'room_devices', ['device_type'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_room_devices_event_id'), 'room_devices', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_room_devices_room_id'), 'room_devices', ['room_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_room_devices_status'), 'room_devices', ['status'], unique=False, schema='venue')
    op.create_table('srr_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('station_number', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_speaker_id', sa.UUID(), nullable=True),
    sa.Column('session_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_speaker_id'], ['presentations.speakers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_srr_stations_assigned_speaker_id'), 'srr_stations', ['assigned_speaker_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_stations_event_id'), 'srr_stations', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_stations_status'), 'srr_stations', ['status'], unique=False, schema='venue')
    op.create_table('session_speakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('presentation_title', sa.String(length=500), nullable=True),
    sa.Column('talk_order', sa.Integer(), nullable=False),
    sa.Column('talk_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['events.sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['presentations.speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_session_speakers_session_id'), 'session_speakers', ['session_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_session_speakers_speaker_id'), 'session_speakers', ['speaker_id'], unique=False, schema='presentations')
    op.create_table('capacity_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_promote', sa.Boolean(), nullable=False),
    sa.Column('priority_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['events.rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['events.sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_capacity_rules_event_id'), 'capacity_rules', ['event_id'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_capacity_rules_room_id'), 'capacity_rules', ['room_id'], unique=False, schema='registration')
    op.create_index(op.f('ix_registration_capacity_rules_session_id'), 'capacity_rules', ['session_id'], unique=False, schema='registration')
    op.create_table('badge_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['venue.badges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_badge_history_badge_id'), 'badge_history', ['badge_id'], unique=False, schema='venue')
    op.create_table('badge_print_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('printer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['venue.badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['venue.printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_badge_print_jobs_badge_id'), 'badge_print_jobs', ['badge_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_badge_print_jobs_printer_id'), 'badge_print_jobs', ['printer_id'], unique=False, schema='venue')
    op.create_table('node_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('station_id', sa.String(length=120), nullable=True),
    sa.Column('checkin_gate_id', sa.UUID(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkin_gate_id'], ['venue.venue_checkin_gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.venue_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['venue.room_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'device_id', name='uq_venue_node_event_device'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_node_assignments_checkin_gate_id'), 'node_assignments', ['checkin_gate_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_node_assignments_device_id'), 'node_assignments', ['device_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_node_assignments_event_id'), 'node_assignments', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_node_assignments_status'), 'node_assignments', ['status'], unique=False, schema='venue')
    op.create_table('srr_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('checked_in_by', sa.UUID(), nullable=True),
    sa.Column('checkin_method', sa.String(length=30), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['presentations.speakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['venue.srr_stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_srr_checkins_checked_in_at'), 'srr_checkins', ['checked_in_at'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_checkins_event_id'), 'srr_checkins', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_checkins_speaker_id'), 'srr_checkins', ['speaker_id'], unique=False, schema='venue')
    op.create_table('venue_scan_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('companion_id', sa.UUID(), nullable=True),
    sa.Column('checkin_gate_id', sa.UUID(), nullable=True),
    sa.Column('badge_id', sa.UUID(), nullable=True),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('station_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('badge_code', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_overridden_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['venue.badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checkin_gate_id'], ['venue.venue_checkin_gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['companion_id'], ['registration.companions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['registration.participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_venue_scan_events_badge_id'), 'venue_scan_events', ['badge_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_scan_events_checkin_gate_id'), 'venue_scan_events', ['checkin_gate_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_scan_events_companion_id'), 'venue_scan_events', ['companion_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_scan_events_participant_id'), 'venue_scan_events', ['participant_id'], unique=False, schema='venue')
    op.create_table('presentation_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('session_speaker_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('upload_source', sa.String(length=30), nullable=False),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('local_cache_path', sa.Text(), nullable=True),
    sa.Column('local_sync_status', sa.String(length=30), nullable=False),
    sa.Column('local_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_speaker_id'], ['presentations.session_speakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['presentations.speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_presentation_files_event_id'), 'presentation_files', ['event_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_file_format'), 'presentation_files', ['file_format'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_is_current_version'), 'presentation_files', ['is_current_version'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_local_sync_status'), 'presentation_files', ['local_sync_status'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_session_speaker_id'), 'presentation_files', ['session_speaker_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_speaker_id'), 'presentation_files', ['speaker_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_upload_status'), 'presentation_files', ['upload_status'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_files_uploaded_at'), 'presentation_files', ['uploaded_at'], unique=False, schema='presentations')
    op.create_table('node_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conflict_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['venue.node_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_node_operations_assignment_id'), 'node_operations', ['assignment_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_node_operations_event_id'), 'node_operations', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_node_operations_operation_id'), 'node_operations', ['operation_id'], unique=True, schema='venue')
    op.create_index(op.f('ix_venue_node_operations_status'), 'node_operations', ['status'], unique=False, schema='venue')
    op.create_table('presentation_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_speaker_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('queue_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['venue.room_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['presentations.presentation_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['events.sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_speaker_id'], ['presentations.session_speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_presentation_queue_file_id'), 'presentation_queue', ['file_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_queue_queue_order'), 'presentation_queue', ['queue_order'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_queue_session_id'), 'presentation_queue', ['session_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_queue_session_speaker_id'), 'presentation_queue', ['session_speaker_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_presentation_queue_status'), 'presentation_queue', ['status'], unique=False, schema='presentations')
    op.create_table('srr_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('speaker_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['presentations.presentation_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speaker_id'], ['presentations.speakers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['venue.srr_stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_srr_activity_logs_action'), 'srr_activity_logs', ['action'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_activity_logs_event_id'), 'srr_activity_logs', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_activity_logs_occurred_at'), 'srr_activity_logs', ['occurred_at'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_activity_logs_speaker_id'), 'srr_activity_logs', ['speaker_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_srr_activity_logs_station_id'), 'srr_activity_logs', ['station_id'], unique=False, schema='venue')
    op.create_table('venue_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['presentations.presentation_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='venue'
    )
    op.create_index(op.f('ix_venue_venue_sync_jobs_created_at'), 'venue_sync_jobs', ['created_at'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_sync_jobs_event_id'), 'venue_sync_jobs', ['event_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_sync_jobs_file_id'), 'venue_sync_jobs', ['file_id'], unique=False, schema='venue')
    op.create_index(op.f('ix_venue_venue_sync_jobs_status'), 'venue_sync_jobs', ['status'], unique=False, schema='venue')
    op.create_table('playback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_entry_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['venue.room_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['presentations.presentation_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='presentations'
    )
    op.create_index(op.f('ix_presentations_playback_events_device_id'), 'playback_events', ['device_id'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_playback_events_event_type'), 'playback_events', ['event_type'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_playback_events_occurred_at'), 'playback_events', ['occurred_at'], unique=False, schema='presentations')
    op.create_index(op.f('ix_presentations_playback_events_queue_entry_id'), 'playback_events', ['queue_entry_id'], unique=False, schema='presentations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presentations_playback_events_queue_entry_id'), table_name='playback_events', schema='presentations')
    op.drop_index(op.f('ix_presentations_playback_events_occurred_at'), table_name='playback_events', schema='presentations')
    op.drop_index(op.f('ix_presentations_playback_events_event_type'), table_name='playback_events', schema='presentations')
    op.drop_index(op.f('ix_presentations_playback_events_device_id'), table_name='playback_events', schema='presentations')
    op.drop_table('playback_events', schema='presentations')
    op.drop_index(op.f('ix_venue_venue_sync_jobs_status'), table_name='venue_sync_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_venue_sync_jobs_file_id'), table_name='venue_sync_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_venue_sync_jobs_event_id'), table_name='venue_sync_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_venue_sync_jobs_created_at'), table_name='venue_sync_jobs', schema='venue')
    op.drop_table('venue_sync_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_srr_activity_logs_station_id'), table_name='srr_activity_logs', schema='venue')
    op.drop_index(op.f('ix_venue_srr_activity_logs_speaker_id'), table_name='srr_activity_logs', schema='venue')
    op.drop_index(op.f('ix_venue_srr_activity_logs_occurred_at'), table_name='srr_activity_logs', schema='venue')
    op.drop_index(op.f('ix_venue_srr_activity_logs_event_id'), table_name='srr_activity_logs', schema='venue')
    op.drop_index(op.f('ix_venue_srr_activity_logs_action'), table_name='srr_activity_logs', schema='venue')
    op.drop_table('srr_activity_logs', schema='venue')
    op.drop_index(op.f('ix_presentations_presentation_queue_status'), table_name='presentation_queue', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_queue_session_speaker_id'), table_name='presentation_queue', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_queue_session_id'), table_name='presentation_queue', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_queue_queue_order'), table_name='presentation_queue', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_queue_file_id'), table_name='presentation_queue', schema='presentations')
    op.drop_table('presentation_queue', schema='presentations')
    op.drop_index(op.f('ix_venue_node_operations_status'), table_name='node_operations', schema='venue')
    op.drop_index(op.f('ix_venue_node_operations_operation_id'), table_name='node_operations', schema='venue')
    op.drop_index(op.f('ix_venue_node_operations_event_id'), table_name='node_operations', schema='venue')
    op.drop_index(op.f('ix_venue_node_operations_assignment_id'), table_name='node_operations', schema='venue')
    op.drop_table('node_operations', schema='venue')
    op.drop_index(op.f('ix_presentations_presentation_files_uploaded_at'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_upload_status'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_speaker_id'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_session_speaker_id'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_local_sync_status'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_is_current_version'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_file_format'), table_name='presentation_files', schema='presentations')
    op.drop_index(op.f('ix_presentations_presentation_files_event_id'), table_name='presentation_files', schema='presentations')
    op.drop_table('presentation_files', schema='presentations')
    op.drop_index(op.f('ix_venue_venue_scan_events_participant_id'), table_name='venue_scan_events', schema='venue')
    op.drop_index(op.f('ix_venue_venue_scan_events_companion_id'), table_name='venue_scan_events', schema='venue')
    op.drop_index(op.f('ix_venue_venue_scan_events_checkin_gate_id'), table_name='venue_scan_events', schema='venue')
    op.drop_index(op.f('ix_venue_venue_scan_events_badge_id'), table_name='venue_scan_events', schema='venue')
    op.drop_table('venue_scan_events', schema='venue')
    op.drop_index(op.f('ix_venue_srr_checkins_speaker_id'), table_name='srr_checkins', schema='venue')
    op.drop_index(op.f('ix_venue_srr_checkins_event_id'), table_name='srr_checkins', schema='venue')
    op.drop_index(op.f('ix_venue_srr_checkins_checked_in_at'), table_name='srr_checkins', schema='venue')
    op.drop_table('srr_checkins', schema='venue')
    op.drop_index(op.f('ix_venue_node_assignments_status'), table_name='node_assignments', schema='venue')
    op.drop_index(op.f('ix_venue_node_assignments_event_id'), table_name='node_assignments', schema='venue')
    op.drop_index(op.f('ix_venue_node_assignments_device_id'), table_name='node_assignments', schema='venue')
    op.drop_index(op.f('ix_venue_node_assignments_checkin_gate_id'), table_name='node_assignments', schema='venue')
    op.drop_table('node_assignments', schema='venue')
    op.drop_index(op.f('ix_venue_badge_print_jobs_printer_id'), table_name='badge_print_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_badge_print_jobs_badge_id'), table_name='badge_print_jobs', schema='venue')
    op.drop_table('badge_print_jobs', schema='venue')
    op.drop_index(op.f('ix_venue_badge_history_badge_id'), table_name='badge_history', schema='venue')
    op.drop_table('badge_history', schema='venue')
    op.drop_index(op.f('ix_registration_capacity_rules_session_id'), table_name='capacity_rules', schema='registration')
    op.drop_index(op.f('ix_registration_capacity_rules_room_id'), table_name='capacity_rules', schema='registration')
    op.drop_index(op.f('ix_registration_capacity_rules_event_id'), table_name='capacity_rules', schema='registration')
    op.drop_table('capacity_rules', schema='registration')
    op.drop_index(op.f('ix_presentations_session_speakers_speaker_id'), table_name='session_speakers', schema='presentations')
    op.drop_index(op.f('ix_presentations_session_speakers_session_id'), table_name='session_speakers', schema='presentations')
    op.drop_table('session_speakers', schema='presentations')
    op.drop_index(op.f('ix_venue_srr_stations_status'), table_name='srr_stations', schema='venue')
    op.drop_index(op.f('ix_venue_srr_stations_event_id'), table_name='srr_stations', schema='venue')
    op.drop_index(op.f('ix_venue_srr_stations_assigned_speaker_id'), table_name='srr_stations', schema='venue')
    op.drop_table('srr_stations', schema='venue')
    op.drop_index(op.f('ix_venue_room_devices_status'), table_name='room_devices', schema='venue')
    op.drop_index(op.f('ix_venue_room_devices_room_id'), table_name='room_devices', schema='venue')
    op.drop_index(op.f('ix_venue_room_devices_event_id'), table_name='room_devices', schema='venue')
    op.drop_index(op.f('ix_venue_room_devices_device_type'), table_name='room_devices', schema='venue')
    op.drop_table('room_devices', schema='venue')
    op.drop_index(op.f('ix_venue_participant_kits_participant_id'), table_name='participant_kits', schema='venue')
    op.drop_index(op.f('ix_venue_participant_kits_kit_id'), table_name='participant_kits', schema='venue')
    op.drop_table('participant_kits', schema='venue')
    op.drop_index(op.f('ix_venue_event_report_audit_event_id'), table_name='event_report_audit', schema='venue')
    op.drop_index(op.f('ix_venue_event_report_audit_created_at'), table_name='event_report_audit', schema='venue')
    op.drop_index(op.f('ix_venue_event_report_audit_action'), table_name='event_report_audit', schema='venue')
    op.drop_table('event_report_audit', schema='venue')
    op.drop_index(op.f('ix_venue_badges_participant_id'), table_name='badges', schema='venue')
    op.drop_index(op.f('ix_venue_badges_nfc_uid'), table_name='badges', schema='venue')
    op.drop_index(op.f('ix_venue_badges_badge_code'), table_name='badges', schema='venue')
    op.drop_table('badges', schema='venue')
    op.drop_index(op.f('ix_registration_participant_registrations_participant_id'), table_name='participant_registrations', schema='registration')
    op.drop_index(op.f('ix_registration_participant_registrations_event_id'), table_name='participant_registrations', schema='registration')
    op.drop_table('participant_registrations', schema='registration')
    op.drop_index(op.f('ix_registration_participant_extensions_participant_id'), table_name='participant_extensions', schema='registration')
    op.drop_table('participant_extensions', schema='registration')
    op.drop_index(op.f('ix_registration_companions_primary_participant_id'), table_name='companions', schema='registration')
    op.drop_index(op.f('ix_registration_companions_event_id'), table_name='companions', schema='registration')
    op.drop_table('companions', schema='registration')
    op.drop_index(op.f('ix_presentations_posters_submitted_at'), table_name='posters', schema='presentations')
    op.drop_index(op.f('ix_presentations_posters_status'), table_name='posters', schema='presentations')
    op.drop_index(op.f('ix_presentations_posters_speaker_id'), table_name='posters', schema='presentations')
    op.drop_index(op.f('ix_presentations_posters_event_id'), table_name='posters', schema='presentations')
    op.drop_index(op.f('ix_presentations_posters_display_screen'), table_name='posters', schema='presentations')
    op.drop_table('posters', schema='presentations')
    op.drop_index(op.f('ix_events_sessions_status'), table_name='sessions', schema='events')
    op.drop_index(op.f('ix_events_sessions_start_time'), table_name='sessions', schema='events')
    op.drop_index(op.f('ix_events_sessions_session_code'), table_name='sessions', schema='events')
    op.drop_index(op.f('ix_events_sessions_room_id'), table_name='sessions', schema='events')
    op.drop_index(op.f('ix_events_sessions_event_id'), table_name='sessions', schema='events')
    op.drop_table('sessions', schema='events')
    op.drop_index(op.f('ix_venue_print_templates_event_id'), table_name='print_templates', schema='venue')
    op.drop_table('print_templates', schema='venue')
    op.drop_index(op.f('ix_venue_event_report_snapshots_event_id'), table_name='event_report_snapshots', schema='venue')
    op.drop_table('event_report_snapshots', schema='venue')
    op.drop_index(op.f('ix_registration_participants_regno'), table_name='participants', schema='registration')
    op.drop_index(op.f('ix_registration_participants_event_id'), table_name='participants', schema='registration')
    op.drop_index(op.f('ix_registration_participants_email'), table_name='participants', schema='registration')
    op.drop_table('participants', schema='registration')
    op.drop_index(op.f('ix_registration_participant_roles_event_id'), table_name='participant_roles', schema='registration')
    op.drop_table('participant_roles', schema='registration')
    op.drop_index(op.f('ix_presentations_speakers_upload_token'), table_name='speakers', schema='presentations')
    op.drop_index(op.f('ix_presentations_speakers_upload_status'), table_name='speakers', schema='presentations')
    op.drop_index(op.f('ix_presentations_speakers_event_id'), table_name='speakers', schema='presentations')
    op.drop_index(op.f('ix_presentations_speakers_email'), table_name='speakers', schema='presentations')
    op.drop_index(op.f('ix_presentations_speakers_created_at'), table_name='speakers', schema='presentations')
    op.drop_table('speakers', schema='presentations')
    op.drop_index(op.f('ix_events_rooms_event_id'), table_name='rooms', schema='events')
    op.drop_table('rooms', schema='events')
    op.drop_index(op.f('ix_events_events_status'), table_name='events', schema='events')
    op.drop_index(op.f('ix_events_events_short_code'), table_name='events', schema='events')
    op.drop_index(op.f('ix_events_events_organization_id'), table_name='events', schema='events')
    op.drop_index(op.f('ix_events_events_created_at'), table_name='events', schema='events')
    op.drop_table('events', schema='events')
    op.drop_table('venue_operational_policies', schema='venue')
    op.drop_table('venue_checkin_gates', schema='venue')
    op.drop_table('sync_outbox', schema='venue')
    op.drop_index(op.f('ix_venue_registration_source_api_keys_organization_id'), table_name='registration_source_api_keys', schema='venue')
    op.drop_index(op.f('ix_venue_registration_source_api_keys_key_prefix'), table_name='registration_source_api_keys', schema='venue')
    op.drop_index(op.f('ix_venue_registration_source_api_keys_event_id'), table_name='registration_source_api_keys', schema='venue')
    op.drop_table('registration_source_api_keys', schema='venue')
    op.drop_table('printers', schema='venue')
    op.drop_table('kits', schema='venue')
    op.drop_index(op.f('ix_identity_venue_users_username'), table_name='venue_users', schema='identity')
    op.drop_index(op.f('ix_identity_venue_users_role'), table_name='venue_users', schema='identity')
    op.drop_index(op.f('ix_identity_venue_users_organization_id'), table_name='venue_users', schema='identity')
    op.drop_index(op.f('ix_identity_venue_users_email'), table_name='venue_users', schema='identity')
    op.drop_table('venue_users', schema='identity')
    op.drop_index(op.f('ix_identity_organizations_slug'), table_name='organizations', schema='identity')
    op.drop_table('organizations', schema='identity')
    for schema in ("venue", "presentations", "registration", "events", "identity"):
        op.execute(sa.text(f'DROP SCHEMA IF EXISTS "{schema}"'))
    # ### end Alembic commands ###
