output "api_load_balancer_dns_name" { value = aws_lb.api.dns_name }
output "api_load_balancer_zone_id" { value = aws_lb.api.zone_id }
output "ecs_cluster_name" { value = aws_ecs_cluster.main.name }
output "backend_service_name" { value = aws_ecs_service.backend.name }
output "worker_service_name" { value = aws_ecs_service.worker.name }
output "runtime_secret_arn" { value = aws_secretsmanager_secret.runtime.arn }
output "deployment_secret_arn" { value = aws_secretsmanager_secret.deployment.arn }
output "identity_bootstrap_secret_arn" { value = aws_secretsmanager_secret.identity_bootstrap.arn }
output "database_endpoint" { value = aws_db_instance.postgres.address }
output "database_master_secret_arn" { value = try(aws_db_instance.postgres.master_user_secret[0].secret_arn, null) }
output "redis_endpoint" { value = aws_elasticache_replication_group.redis.primary_endpoint_address }
output "alert_topic_arn" { value = aws_sns_topic.alerts.arn }
output "backend_task_definition_arn" { value = aws_ecs_task_definition.backend.arn }
output "worker_task_definition_arn" { value = aws_ecs_task_definition.worker.arn }
output "database_bootstrap_task_definition_arn" { value = aws_ecs_task_definition.database_bootstrap.arn }
output "migration_task_definition_arn" { value = aws_ecs_task_definition.migration.arn }
output "identity_bootstrap_task_definition_arn" { value = aws_ecs_task_definition.identity_bootstrap.arn }
output "runtime_security_group_id" { value = aws_security_group.runtime.id }
