'use client';

import React, { Suspense, useEffect, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import { AlertTriangle, Loader2, RefreshCw } from 'lucide-react';
import type { WebsiteProjectData, WebsiteBuilderStudioProps } from '@eventos/website-builder-studio/studio';
import { EVENT_TEMPLATES } from '@eventos/website-builder-studio';
import { platformWebsiteTemplates, type WebsiteTemplateDraftRecord } from '@/services/website-template-builder-service';

// Dynamically import WebsiteBuilderStudio with SSR disabled for GrapesJS DOM compatibility
const WebsiteBuilderStudio = dynamic<WebsiteBuilderStudioProps>(
  () => import('@eventos/website-builder-studio/studio').then((mod) => mod.WebsiteBuilderStudio),
  {
    ssr: false,
    loading: () => (
      <div className="w-full h-full min-h-[500px] flex items-center justify-center bg-background text-foreground">
        <Loader2 className="h-8 w-8 text-primary animate-spin" />
        <span className="ml-3 font-semibold text-muted-foreground">Loading Website Studio...</span>
      </div>
    ),
  }
);

function BuilderInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const templateId = searchParams.get('templateId');

  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState<WebsiteTemplateDraftRecord | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [initialData, setInitialData] = useState<WebsiteProjectData | undefined>(undefined);
  const [loadAttempt, setLoadAttempt] = useState(0);
  const draftVersionRef = useRef<number>(1);

  useEffect(() => {
    let mounted = true;

    async function loadTemplate() {
      setLoading(true);
      setLoadError(null);

      // Check if opening a specific category seeded template
      if (templateId && templateId !== 'master-event-website') {
        const seeded = EVENT_TEMPLATES.find((t) => t.id === templateId);
        if (seeded) {
          const doc = seeded.createDocument();
          if (!mounted) return;
          setInitialData({
            id: seeded.id,
            name: seeded.name,
            document: doc,
            siteSettings: doc.site,
            assets: doc.assets,
            theme: doc.tokens.theme,
            updatedAt: doc.updatedAt,
          });
          setLoading(false);
          return;
        }
      }

      // Otherwise load platform master template draft
      try {
        const record = await platformWebsiteTemplates.getMasterDraft();
        if (!mounted) return;
        draftVersionRef.current = record.version;
        setDraft(record);
        setInitialData({
          id: record.template_id,
          name: record.name,
          document: record.document,
          siteSettings: record.document.site,
          assets: record.document.assets,
          theme: record.document.tokens.theme,
          updatedAt: record.updated_at,
        });
      } catch (error) {
        if (!mounted) return;
        console.error('[Command Center] Failed to load master website template:', error);
        setLoadError('The master website draft could not be loaded. Editing is paused to prevent unsynchronised template changes.');
      } finally {
        if (mounted) setLoading(false);
      }
    }

    loadTemplate();
    return () => {
      mounted = false;
    };
  }, [loadAttempt, templateId]);

  const handleSaveMasterTemplate = async (data: WebsiteProjectData) => {
    if (!data.document) {
      throw new Error('Website document was not generated by the studio.');
    }
    let saved: WebsiteTemplateDraftRecord;
    try {
      saved = await platformWebsiteTemplates.saveMasterDraft(draftVersionRef.current || draft?.version || 1, data.document);
    } catch (error) {
      if ((error as { code?: string }).code !== 'WEBSITE_TEMPLATE_DRAFT_CONFLICT') throw error;

      const latest = await platformWebsiteTemplates.getMasterDraft();
      draftVersionRef.current = latest.version;
      saved = await platformWebsiteTemplates.saveMasterDraft(latest.version, data.document);
    }
    draftVersionRef.current = saved.version;
    setDraft(saved);
  };

  const handlePublishMasterTemplate = async (data: WebsiteProjectData) => {
    if (!data.document) {
      throw new Error('Website document was not generated by the studio.');
    }
    const validation = await platformWebsiteTemplates.validateMaster(data.document);
    if (!validation.valid) {
      alert('Publish validation failed. Fix the website diagnostics before publishing.');
      return;
    }
    await handleSaveMasterTemplate(data);
    await platformWebsiteTemplates.publishMaster();
    alert('Master template published globally for event organizers.');
  };

  const handleCreatePreview = async (data: WebsiteProjectData, previewId?: string) => {
    if (!data.document) throw new Error('Website document was not generated by the studio.');
    const preview = await platformWebsiteTemplates.createPreview(data.document, previewId);
    return {
      previewId: preview.preview_id,
      url: preview.url,
      expiresAt: preview.expires_at,
    };
  };

  const handleBack = () => {
    router.push('/applications/templates/website');
  };

  if (loading) {
    return (
      <div className="w-full h-full min-h-[600px] flex items-center justify-center bg-background text-foreground">
        <Loader2 className="h-8 w-8 text-primary animate-spin" />
        <span className="ml-3 font-semibold text-muted-foreground">Loading Website Studio...</span>
      </div>
    );
  }

  if (loadError || !initialData) {
    return (
      <div className="grid min-h-[500px] place-items-center bg-background px-6 text-foreground">
        <section className="w-full max-w-md border border-border bg-card p-6 shadow-sm rounded-xl">
          <AlertTriangle className="mb-4 h-6 w-6 text-amber-500" aria-hidden="true" />
          <h1 className="text-lg font-semibold">Website draft unavailable</h1>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">{loadError || 'No canonical website draft was returned.'}</p>
          <button
            type="button"
            onClick={() => setLoadAttempt((attempt) => attempt + 1)}
            className="mt-5 inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground"
          >
            <RefreshCw className="h-4 w-4" aria-hidden="true" />
            Retry
          </button>
        </section>
      </div>
    );
  }

  return (
    <div className="relative w-full h-[calc(100vh-130px)] min-h-[600px] flex flex-col overflow-hidden rounded-[14px] border border-[var(--border)] bg-[var(--base)] text-[var(--text)]">
      <WebsiteBuilderStudio
        mode="GLOBAL_ADMIN"
        initialData={initialData}
        onSave={handleSaveMasterTemplate}
        onPublish={handlePublishMasterTemplate}
        onCreatePreview={handleCreatePreview}
        onSearchImages={platformWebsiteTemplates.searchOpenverse}
        onBack={handleBack}
      />
    </div>
  );
}

export default function DeveloperWebsiteBuilderPage() {
  return (
    <Suspense
      fallback={
        <div className="w-full h-full min-h-[600px] flex items-center justify-center bg-background text-foreground">
          <Loader2 className="h-8 w-8 text-primary animate-spin" />
          <span className="ml-3 font-semibold text-muted-foreground">Loading Studio...</span>
        </div>
      }
    >
      <BuilderInner />
    </Suspense>
  );
}
