"""organizer commercial control plane

Revision ID: 20260722_0930
Revises: 20260720_0920
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260722_0930"
down_revision = "20260720_0920"
branch_labels = None
depends_on = None
UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())

def upgrade() -> None:
    op.add_column("logs", sa.Column("hash_version", sa.Integer(), nullable=False, server_default="1"), schema="audit")
    op.add_column("impersonation_logs", sa.Column("case_reference", sa.String(160)), schema="audit")
    op.create_index("ix_impersonation_handoff_hash", "impersonation_logs", ["session_token_hash"], unique=True, schema="audit", postgresql_where=sa.text("session_token_hash IS NOT NULL"))
    op.execute("""CREATE OR REPLACE FUNCTION audit.reject_log_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit.logs is append-only'; END; $$""")
    op.execute("""CREATE TRIGGER trg_audit_logs_append_only BEFORE UPDATE OR DELETE ON audit.logs FOR EACH ROW EXECUTE FUNCTION audit.reject_log_mutation()""")
    op.add_column("email_campaigns", sa.Column("deleted_at", sa.DateTime(timezone=True)), schema="communications")
    op.add_column("email_campaigns", sa.Column("deleted_by", UUID), schema="communications")
    op.create_foreign_key("fk_email_campaigns_deleted_by", "email_campaigns", "users", ["deleted_by"], ["id"], source_schema="communications", referent_schema="identity", ondelete="SET NULL")
    op.add_column("email_templates", sa.Column("deleted_at", sa.DateTime(timezone=True)), schema="communications")
    op.add_column("email_templates", sa.Column("deleted_by", UUID), schema="communications")
    op.create_foreign_key("fk_email_templates_deleted_by", "email_templates", "users", ["deleted_by"], ["id"], source_schema="communications", referent_schema="identity", ondelete="SET NULL")
    op.add_column("print_templates", sa.Column("deleted_at", sa.DateTime(timezone=True)), schema="registration")
    op.add_column("print_templates", sa.Column("deleted_by", UUID), schema="registration")
    op.create_foreign_key("fk_print_templates_deleted_by", "print_templates", "users", ["deleted_by"], ["id"], source_schema="registration", referent_schema="identity", ondelete="SET NULL")
    op.create_table("event_commercial_contracts", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID, nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("plan_key", sa.String(100), nullable=False), sa.Column("plan_version", sa.String(60), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("entitlements", JSONB, nullable=False), sa.Column("hard_ceilings", JSONB, nullable=False), sa.Column("addons", JSONB, nullable=False), sa.Column("source", JSONB, nullable=False), sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True)), sa.Column("created_by", UUID, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("event_id", "version", name="uq_event_contract_version"), schema="platform")
    op.create_index("ix_event_contract_active", "event_commercial_contracts", ["organization_id", "event_id", "status"], schema="platform")
    op.create_table("entitlement_override_requests", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID), sa.Column("entitlement_key", sa.String(120), nullable=False), sa.Column("operation", sa.String(24), nullable=False), sa.Column("requested_value", JSONB, nullable=False), sa.Column("previous_value", JSONB), sa.Column("reason", sa.Text(), nullable=False), sa.Column("case_reference", sa.String(160), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("requested_by", UUID, nullable=False), sa.Column("approved_by", UUID), sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["requested_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["approved_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_entitlement_override_idempotency"), schema="platform")
    op.create_index("ix_entitlement_override_scope_status", "entitlement_override_requests", ["organization_id", "event_id", "status"], schema="platform")
    op.create_table("usage_counter_epochs", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("baseline_value", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("reset_entry_id", UUID), sa.Column("reason", sa.Text()), sa.Column("created_by", UUID), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by"], ["identity.users.id"], ondelete="SET NULL"), sa.UniqueConstraint("organization_id", "event_id", "metric_key", "sequence", name="uq_usage_counter_epoch_sequence"), schema="platform")
    op.create_index("ix_usage_counter_epoch_active", "usage_counter_epochs", ["organization_id", "event_id", "metric_key", "closed_at"], schema="platform")
    op.create_table("usage_ledger_entries", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("quantity", sa.Integer(), nullable=False), sa.Column("unit", sa.String(30), nullable=False), sa.Column("entry_type", sa.String(24), nullable=False), sa.Column("source", sa.String(120), nullable=False), sa.Column("reason", sa.Text()), sa.Column("idempotency_key", sa.String(160), nullable=False), sa.Column("actor_user_id", UUID), sa.Column("period_start", sa.DateTime(timezone=True)), sa.Column("period_end", sa.DateTime(timezone=True)), sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False), sa.Column("epoch_id", UUID), sa.Column("parent_entry_id", UUID), sa.Column("metadata_json", JSONB, nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["actor_user_id"], ["identity.users.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["epoch_id"], ["platform.usage_counter_epochs.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["parent_entry_id"], ["platform.usage_ledger_entries.id"], ondelete="RESTRICT"), sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_usage_ledger_idempotency"), schema="platform")
    op.create_index("ix_usage_ledger_scope_metric", "usage_ledger_entries", ["organization_id", "event_id", "metric_key", "occurred_at"], schema="platform")
    op.create_table("usage_reconciliation_runs", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID, nullable=False), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("ledger_value", sa.Integer(), nullable=False), sa.Column("authoritative_value", sa.Integer(), nullable=False), sa.Column("drift", sa.Integer(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("source", sa.String(120), nullable=False), sa.Column("details", JSONB, nullable=False), sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), schema="platform")
    op.create_index("ix_usage_reconciliation_scope", "usage_reconciliation_runs", ["organization_id", "event_id", "metric_key", "reconciled_at"], schema="platform")
    op.create_table("entitlement_shadow_comparisons", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID, nullable=False), sa.Column("legacy_values", JSONB, nullable=False), sa.Column("contract_values", JSONB, nullable=False), sa.Column("differences", JSONB, nullable=False), sa.Column("resolution_version", sa.String(64), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("compared_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="CASCADE"), schema="platform")
    op.create_index("ix_entitlement_shadow_scope_time", "entitlement_shadow_comparisons", ["organization_id", "event_id", "compared_at"], schema="platform")
    op.create_table("privileged_access_sessions", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("actor_user_id", UUID, nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("case_reference", sa.String(160), nullable=False), sa.Column("field_categories", JSONB, nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["actor_user_id"], ["identity.users.id"], ondelete="RESTRICT"), schema="platform")
    op.create_index("ix_privileged_access_actor_active", "privileged_access_sessions", ["organization_id", "actor_user_id", "expires_at"], schema="platform")
    op.create_table("organization_financial_adjustments", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("event_id", UUID), sa.Column("adjustment_type", sa.String(24), nullable=False), sa.Column("amount", sa.Numeric(14, 2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("case_reference", sa.String(160), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("requested_by", UUID, nullable=False), sa.Column("approved_by", UUID), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("effective_at", sa.DateTime(timezone=True)), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["requested_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["approved_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_org_financial_adjustment_idempotency"), schema="platform")
    op.create_index("ix_org_financial_adjustment_status", "organization_financial_adjustments", ["organization_id", "status", "created_at"], schema="platform")
    op.add_column("organization_financial_adjustments", sa.Column("details", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), schema="platform")
    op.add_column("organization_financial_adjustments", sa.Column("applied_at", sa.DateTime(timezone=True)), schema="platform")
    op.add_column("organization_financial_adjustments", sa.Column("applied_resource_type", sa.String(80)), schema="platform")
    op.add_column("organization_financial_adjustments", sa.Column("applied_resource_id", UUID), schema="platform")
    op.add_column("developer_api_keys", sa.Column("idempotency_key", sa.String(128)), schema="developer")
    op.add_column("developer_api_keys", sa.Column("request_hash", sa.String(64)), schema="developer")
    op.create_index("uq_developer_api_keys_org_idempotency", "developer_api_keys", ["organization_id", "idempotency_key"], unique=True, schema="developer")
    op.add_column("connections", sa.Column("idempotency_key", sa.String(128)), schema="integrations")
    op.add_column("connections", sa.Column("request_hash", sa.String(64)), schema="integrations")
    op.add_column("connections", sa.Column("version", sa.Integer(), nullable=False, server_default="1"), schema="integrations")
    op.create_index("uq_integration_connections_org_idempotency", "connections", ["organization_id", "idempotency_key"], unique=True, schema="integrations")
    op.create_table("organization_teams", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.Text()), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by", UUID, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["created_by"], ["identity.users.id"], ondelete="RESTRICT"), schema="platform")
    op.create_index("uq_organization_team_name_active", "organization_teams", ["organization_id", "name"], unique=True, schema="platform", postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("ix_organization_teams_org_active", "organization_teams", ["organization_id", "deleted_at"], schema="platform")
    op.create_table("organization_team_members", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("team_id", UUID, nullable=False), sa.Column("organization_member_id", UUID, nullable=False), sa.Column("created_by", UUID, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["team_id"], ["platform.organization_teams.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["organization_member_id"], ["rbac.organization_members.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["created_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("team_id", "organization_member_id", name="uq_organization_team_member"), schema="platform")
    op.create_index("ix_organization_team_members_org_team", "organization_team_members", ["organization_id", "team_id"], schema="platform")
    op.create_table("organization_team_events", sa.Column("id", UUID, primary_key=True), sa.Column("organization_id", UUID, nullable=False), sa.Column("team_id", UUID, nullable=False), sa.Column("event_id", UUID, nullable=False), sa.Column("permissions", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_by", UUID, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["platform.organizations.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["team_id"], ["platform.organization_teams.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["event_id"], ["events.events.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["created_by"], ["identity.users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("team_id", "event_id", name="uq_organization_team_event"), schema="platform")
    op.create_index("ix_organization_team_events_org_team", "organization_team_events", ["organization_id", "team_id"], schema="platform")
    op.add_column("organization_notification_rules", sa.Column("deleted_at", sa.DateTime(timezone=True)), schema="platform")
    op.add_column("organization_notification_channel_configs", sa.Column("deleted_at", sa.DateTime(timezone=True)), schema="platform")
    op.drop_constraint("uq_org_notification_rule_name", "organization_notification_rules", schema="platform", type_="unique")
    op.drop_constraint("uq_org_notification_channel", "organization_notification_channel_configs", schema="platform", type_="unique")
    op.create_index("uq_org_notification_rule_name_active", "organization_notification_rules", ["organization_id", "name"], unique=True, schema="platform", postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("uq_org_notification_channel_active", "organization_notification_channel_configs", ["organization_id", "channel"], unique=True, schema="platform", postgresql_where=sa.text("deleted_at IS NULL"))

def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit.logs")
    op.execute("DROP FUNCTION IF EXISTS audit.reject_log_mutation()")
    op.drop_column("logs", "hash_version", schema="audit")
    op.drop_index("ix_impersonation_handoff_hash", table_name="impersonation_logs", schema="audit")
    op.drop_column("impersonation_logs", "case_reference", schema="audit")
    op.drop_table("entitlement_shadow_comparisons", schema="platform")
    op.drop_index("uq_org_notification_channel_active", table_name="organization_notification_channel_configs", schema="platform")
    op.drop_index("uq_org_notification_rule_name_active", table_name="organization_notification_rules", schema="platform")
    op.create_unique_constraint("uq_org_notification_channel", "organization_notification_channel_configs", ["organization_id", "channel"], schema="platform")
    op.create_unique_constraint("uq_org_notification_rule_name", "organization_notification_rules", ["organization_id", "name"], schema="platform")
    op.drop_column("organization_notification_channel_configs", "deleted_at", schema="platform")
    op.drop_column("organization_notification_rules", "deleted_at", schema="platform")
    op.drop_table("organization_team_events", schema="platform")
    op.drop_table("organization_team_members", schema="platform")
    op.drop_index("uq_organization_team_name_active", table_name="organization_teams", schema="platform")
    op.drop_table("organization_teams", schema="platform")
    op.drop_index("uq_integration_connections_org_idempotency", table_name="connections", schema="integrations")
    op.drop_column("connections", "version", schema="integrations")
    op.drop_column("connections", "request_hash", schema="integrations")
    op.drop_column("connections", "idempotency_key", schema="integrations")
    op.drop_index("uq_developer_api_keys_org_idempotency", table_name="developer_api_keys", schema="developer")
    op.drop_column("developer_api_keys", "request_hash", schema="developer")
    op.drop_column("developer_api_keys", "idempotency_key", schema="developer")
    for table in ("organization_financial_adjustments", "privileged_access_sessions", "usage_reconciliation_runs", "usage_ledger_entries", "usage_counter_epochs", "entitlement_override_requests", "event_commercial_contracts"):
        op.drop_table(table, schema="platform")
    op.drop_constraint("fk_print_templates_deleted_by", "print_templates", schema="registration", type_="foreignkey")
    op.drop_column("print_templates", "deleted_by", schema="registration")
    op.drop_column("print_templates", "deleted_at", schema="registration")
    op.drop_constraint("fk_email_templates_deleted_by", "email_templates", schema="communications", type_="foreignkey")
    op.drop_column("email_templates", "deleted_by", schema="communications")
    op.drop_column("email_templates", "deleted_at", schema="communications")
    op.drop_constraint("fk_email_campaigns_deleted_by", "email_campaigns", schema="communications", type_="foreignkey")
    op.drop_column("email_campaigns", "deleted_by", schema="communications")
    op.drop_column("email_campaigns", "deleted_at", schema="communications")
