"""add_platform_audit_activity_compliance

Revision ID: 73e680f44263
Revises: be7d39c4425f
Create Date: 2026-06-21 14:22:34.122246+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e680f44263'
down_revision: Union[str, None] = 'be7d39c4425f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_audit')
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_activity')
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_compliance')
    op.create_table('activity_feed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='platform_activity',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_platform_activity_activity_feed_created_at'), 'activity_feed', ['created_at'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_activity_feed_organization_id'), 'activity_feed', ['organization_id'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_activity_feed_user_id'), 'activity_feed', ['user_id'], unique=False, schema='platform_activity')
    op.create_table('activity_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_activity'
    )
    op.create_index(op.f('ix_platform_activity_activity_subscriptions_entity_id'), 'activity_subscriptions', ['entity_id'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_activity_subscriptions_user_id'), 'activity_subscriptions', ['user_id'], unique=False, schema='platform_activity')
    op.create_table('user_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='platform_activity',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_activity_org', 'user_activity_logs', ['organization_id'], unique=False, schema='platform_activity')
    op.create_index('idx_activity_user', 'user_activity_logs', ['user_id'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_user_activity_logs_activity_type'), 'user_activity_logs', ['activity_type'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_user_activity_logs_created_at'), 'user_activity_logs', ['created_at'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_user_activity_logs_organization_id'), 'user_activity_logs', ['organization_id'], unique=False, schema='platform_activity')
    op.create_index(op.f('ix_platform_activity_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False, schema='platform_activity')
    op.create_table('api_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='platform_audit',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_platform_audit_api_activity_logs_created_at'), 'api_activity_logs', ['created_at'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_api_activity_logs_organization_id'), 'api_activity_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_api_activity_logs_user_id'), 'api_activity_logs', ['user_id'], unique=False, schema='platform_audit')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'performed_at'),
    schema='platform_audit',
    postgresql_partition_by='RANGE (performed_at)'
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='platform_audit')
    op.create_index('idx_audit_org', 'audit_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index('idx_audit_user', 'audit_logs', ['performed_by'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_module'), 'audit_logs', ['module'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_performed_at'), 'audit_logs', ['performed_at'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False, schema='platform_audit')
    op.create_table('data_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_audit'
    )
    op.create_index(op.f('ix_platform_audit_data_access_logs_accessed_at'), 'data_access_logs', ['accessed_at'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_data_access_logs_organization_id'), 'data_access_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_data_access_logs_user_id'), 'data_access_logs', ['user_id'], unique=False, schema='platform_audit')
    op.create_table('entity_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_audit'
    )
    op.create_index(op.f('ix_platform_audit_entity_history_created_at'), 'entity_history', ['created_at'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_entity_history_entity_id'), 'entity_history', ['entity_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_entity_history_entity_type'), 'entity_history', ['entity_type'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_entity_history_organization_id'), 'entity_history', ['organization_id'], unique=False, schema='platform_audit')
    op.create_table('export_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_audit'
    )
    op.create_index(op.f('ix_platform_audit_export_logs_created_at'), 'export_logs', ['created_at'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_export_logs_organization_id'), 'export_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_export_logs_user_id'), 'export_logs', ['user_id'], unique=False, schema='platform_audit')
    op.create_table('impersonation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_audit'
    )
    op.create_index(op.f('ix_platform_audit_impersonation_logs_admin_user_id'), 'impersonation_logs', ['admin_user_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_impersonation_logs_organization_id'), 'impersonation_logs', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_impersonation_logs_target_user_id'), 'impersonation_logs', ['target_user_id'], unique=False, schema='platform_audit')
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'login_time'),
    schema='platform_audit',
    postgresql_partition_by='RANGE (login_time)'
    )
    op.create_index('idx_login_user', 'login_history', ['user_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_login_history_login_time'), 'login_history', ['login_time'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_login_history_organization_id'), 'login_history', ['organization_id'], unique=False, schema='platform_audit')
    op.create_index(op.f('ix_platform_audit_login_history_user_id'), 'login_history', ['user_id'], unique=False, schema='platform_audit')
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_compliance'
    )
    op.create_index(op.f('ix_platform_compliance_compliance_reports_generated_at'), 'compliance_reports', ['generated_at'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_compliance_reports_organization_id'), 'compliance_reports', ['organization_id'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_compliance_reports_report_type'), 'compliance_reports', ['report_type'], unique=False, schema='platform_compliance')
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('archive_enabled', sa.Boolean(), nullable=False),
    sa.Column('delete_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_compliance'
    )
    op.create_index(op.f('ix_platform_compliance_retention_policies_module'), 'retention_policies', ['module'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_retention_policies_organization_id'), 'retention_policies', ['organization_id'], unique=False, schema='platform_compliance')
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='platform_compliance',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_security_events', 'security_events', ['organization_id', 'severity'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_security_events_created_at'), 'security_events', ['created_at'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_security_events_event_type'), 'security_events', ['event_type'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_security_events_organization_id'), 'security_events', ['organization_id'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_security_events_severity'), 'security_events', ['severity'], unique=False, schema='platform_compliance')
    op.create_index(op.f('ix_platform_compliance_security_events_status'), 'security_events', ['status'], unique=False, schema='platform_compliance')

    # Create default partition partitions
    op.execute('CREATE TABLE IF NOT EXISTS platform_activity.activity_feed_default PARTITION OF platform_activity.activity_feed DEFAULT')
    op.execute('CREATE TABLE IF NOT EXISTS platform_activity.user_activity_logs_default PARTITION OF platform_activity.user_activity_logs DEFAULT')
    op.execute('CREATE TABLE IF NOT EXISTS platform_audit.api_activity_logs_default PARTITION OF platform_audit.api_activity_logs DEFAULT')
    op.execute('CREATE TABLE IF NOT EXISTS platform_audit.audit_logs_default PARTITION OF platform_audit.audit_logs DEFAULT')
    op.execute('CREATE TABLE IF NOT EXISTS platform_audit.login_history_default PARTITION OF platform_audit.login_history DEFAULT')
    op.execute('CREATE TABLE IF NOT EXISTS platform_compliance.security_events_default PARTITION OF platform_compliance.security_events DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_compliance_security_events_status'), table_name='security_events', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_security_events_severity'), table_name='security_events', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_security_events_organization_id'), table_name='security_events', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_security_events_event_type'), table_name='security_events', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_security_events_created_at'), table_name='security_events', schema='platform_compliance')
    op.drop_index('idx_security_events', table_name='security_events', schema='platform_compliance')
    op.drop_table('security_events', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_retention_policies_organization_id'), table_name='retention_policies', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_retention_policies_module'), table_name='retention_policies', schema='platform_compliance')
    op.drop_table('retention_policies', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_compliance_reports_report_type'), table_name='compliance_reports', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_compliance_reports_organization_id'), table_name='compliance_reports', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_compliance_compliance_reports_generated_at'), table_name='compliance_reports', schema='platform_compliance')
    op.drop_table('compliance_reports', schema='platform_compliance')
    op.drop_index(op.f('ix_platform_audit_login_history_user_id'), table_name='login_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_login_history_organization_id'), table_name='login_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_login_history_login_time'), table_name='login_history', schema='platform_audit')
    op.drop_index('idx_login_user', table_name='login_history', schema='platform_audit')
    op.drop_table('login_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_impersonation_logs_target_user_id'), table_name='impersonation_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_impersonation_logs_organization_id'), table_name='impersonation_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_impersonation_logs_admin_user_id'), table_name='impersonation_logs', schema='platform_audit')
    op.drop_table('impersonation_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_export_logs_user_id'), table_name='export_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_export_logs_organization_id'), table_name='export_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_export_logs_created_at'), table_name='export_logs', schema='platform_audit')
    op.drop_table('export_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_entity_history_organization_id'), table_name='entity_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_entity_history_entity_type'), table_name='entity_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_entity_history_entity_id'), table_name='entity_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_entity_history_created_at'), table_name='entity_history', schema='platform_audit')
    op.drop_table('entity_history', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_data_access_logs_user_id'), table_name='data_access_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_data_access_logs_organization_id'), table_name='data_access_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_data_access_logs_accessed_at'), table_name='data_access_logs', schema='platform_audit')
    op.drop_table('data_access_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_performed_by'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_performed_at'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_organization_id'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_module'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_entity_type'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_entity_id'), table_name='audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_audit_logs_action'), table_name='audit_logs', schema='platform_audit')
    op.drop_index('idx_audit_user', table_name='audit_logs', schema='platform_audit')
    op.drop_index('idx_audit_org', table_name='audit_logs', schema='platform_audit')
    op.drop_index('idx_audit_entity', table_name='audit_logs', schema='platform_audit')
    op.drop_table('audit_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_api_activity_logs_user_id'), table_name='api_activity_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_api_activity_logs_organization_id'), table_name='api_activity_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_audit_api_activity_logs_created_at'), table_name='api_activity_logs', schema='platform_audit')
    op.drop_table('api_activity_logs', schema='platform_audit')
    op.drop_index(op.f('ix_platform_activity_user_activity_logs_user_id'), table_name='user_activity_logs', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_user_activity_logs_organization_id'), table_name='user_activity_logs', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_user_activity_logs_created_at'), table_name='user_activity_logs', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_user_activity_logs_activity_type'), table_name='user_activity_logs', schema='platform_activity')
    op.drop_index('idx_activity_user', table_name='user_activity_logs', schema='platform_activity')
    op.drop_index('idx_activity_org', table_name='user_activity_logs', schema='platform_activity')
    op.drop_table('user_activity_logs', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_activity_subscriptions_user_id'), table_name='activity_subscriptions', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_activity_subscriptions_entity_id'), table_name='activity_subscriptions', schema='platform_activity')
    op.drop_table('activity_subscriptions', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_activity_feed_user_id'), table_name='activity_feed', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_activity_feed_organization_id'), table_name='activity_feed', schema='platform_activity')
    op.drop_index(op.f('ix_platform_activity_activity_feed_created_at'), table_name='activity_feed', schema='platform_activity')
    op.drop_table('activity_feed', schema='platform_activity')
    # ### end Alembic commands ###
