"""add_subscription_transactions

Revision ID: 99f14dfd43d1
Revises: 922d300bd1ba
Create Date: 2026-06-14 16:42:28.375866+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f14dfd43d1'
down_revision: Union[str, None] = '922d300bd1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('billing_phone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_custom_plan', sa.Boolean(), nullable=False),
    sa.Column('custom_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addon_keys', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.alter_column('addons', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('addons', 'features_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True,
               schema='billing')
    op.alter_column('addons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.drop_constraint(op.f('uq_plan_features_plan_feature'), 'plan_features', schema='billing', type_='unique')
    op.alter_column('subscription_plans', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'billing_model',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'is_popular',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('feature_catalog', 'category_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'feature_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_addon',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_billable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_billable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'is_addon',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'feature_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('feature_catalog', 'category_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='platform')
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'is_popular',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'billing_model',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PER_EVENT'::character varying"),
               existing_nullable=False,
               schema='billing')
    op.alter_column('subscription_plans', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False,
               schema='billing')
    op.create_unique_constraint(op.f('uq_plan_features_plan_feature'), 'plan_features', ['plan_id', 'feature_id'], schema='billing', postgresql_nulls_not_distinct=False)
    op.alter_column('addons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('addons', 'features_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True,
               schema='billing')
    op.alter_column('addons', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='billing')
    op.drop_table('subscription_transactions', schema='billing')
    # ### end Alembic commands ###
