"""add_platform_notifications

Revision ID: be7d39c4425f
Revises: 8d02510082ce
Create Date: 2026-06-21 13:35:29.479965+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_platform_notifications

Revision ID: be7d39c4425f
Revises: 8d02510082ce
Create Date: 2026-06-21 13:35:29.479965+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be7d39c4425f'
down_revision: Union[str, None] = '8d02510082ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_notifications')
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_communications')
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_alerts')
    op.execute('CREATE SCHEMA IF NOT EXISTS platform_webhooks')
    op.create_table('notification_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_events_event_key'), 'notification_events', ['event_key'], unique=True, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_events_module'), 'notification_events', ['module'], unique=False, schema='platform_notifications')
    op.create_table('marketplace_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['marketplace.apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_marketplace_apps_app_id'), 'marketplace_apps', ['app_id'], unique=True, schema='marketplace')
    op.create_table('notification_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_communications'
    )
    op.create_index(op.f('ix_platform_communications_notification_groups_organization_id'), 'notification_groups', ['organization_id'], unique=False, schema='platform_communications')
    op.create_table('notification_webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_webhooks'
    )
    op.create_index(op.f('ix_platform_webhooks_notification_webhooks_organization_id'), 'notification_webhooks', ['organization_id'], unique=False, schema='platform_webhooks')
    op.create_table('system_announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_alerts'
    )
    op.create_index(op.f('ix_platform_alerts_system_announcements_organization_id'), 'system_announcements', ['organization_id'], unique=False, schema='platform_alerts')
    op.create_table('notification_digests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_communications'
    )
    op.create_index(op.f('ix_platform_communications_notification_digests_next_run_at'), 'notification_digests', ['next_run_at'], unique=False, schema='platform_communications')
    op.create_index(op.f('ix_platform_communications_notification_digests_organization_id'), 'notification_digests', ['organization_id'], unique=False, schema='platform_communications')
    op.create_index(op.f('ix_platform_communications_notification_digests_user_id'), 'notification_digests', ['user_id'], unique=False, schema='platform_communications')
    op.create_table('notification_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['platform_communications.notification_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_communications'
    )
    op.create_index(op.f('ix_platform_communications_notification_group_members_group_id'), 'notification_group_members', ['group_id'], unique=False, schema='platform_communications')
    op.create_index(op.f('ix_platform_communications_notification_group_members_user_id'), 'notification_group_members', ['user_id'], unique=False, schema='platform_communications')
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['platform_notifications.notification_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_communications'
    )
    op.create_index(op.f('ix_platform_communications_notification_subscriptions_event_id'), 'notification_subscriptions', ['event_id'], unique=False, schema='platform_communications')
    op.create_index(op.f('ix_platform_communications_notification_subscriptions_organization_id'), 'notification_subscriptions', ['organization_id'], unique=False, schema='platform_communications')
    op.create_index(op.f('ix_platform_communications_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False, schema='platform_communications')
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_in_app_notifications_created_at'), 'in_app_notifications', ['created_at'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_in_app_notifications_organization_id'), 'in_app_notifications', ['organization_id'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_in_app_notifications_user_id'), 'in_app_notifications', ['user_id'], unique=False, schema='platform_notifications')
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_start_time', sa.String(length=10), nullable=True),
    sa.Column('quiet_end_time', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['platform_notifications.notification_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_preferences_event_id'), 'notification_preferences', ['event_id'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False, schema='platform_notifications')
    op.create_table('notification_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['platform_notifications.notification_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_templates_channel'), 'notification_templates', ['channel'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_templates_deleted_at'), 'notification_templates', ['deleted_at'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_templates_event_id'), 'notification_templates', ['event_id'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_templates_organization_id'), 'notification_templates', ['organization_id'], unique=False, schema='platform_notifications')
    op.create_table('notification_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('notification_event_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_event_id'], ['platform_notifications.notification_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['platform_notifications.notification_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_queue_organization_id'), 'notification_queue', ['organization_id'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_queue_priority'), 'notification_queue', ['priority'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_queue_recipient_id'), 'notification_queue', ['recipient_id'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_queue_scheduled_at'), 'notification_queue', ['scheduled_at'], unique=False, schema='platform_notifications')
    op.create_index(op.f('ix_platform_notifications_notification_queue_status'), 'notification_queue', ['status'], unique=False, schema='platform_notifications')
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['platform_notifications.notification_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_alerts'
    )
    op.create_index(op.f('ix_platform_alerts_notification_logs_notification_id'), 'notification_logs', ['notification_id'], unique=False, schema='platform_alerts')
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['platform_notifications.notification_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_deliveries_queue_id'), 'notification_deliveries', ['queue_id'], unique=False, schema='platform_notifications')
    op.create_table('notification_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['presentations.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['platform_notifications.notification_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform_notifications'
    )
    op.create_index(op.f('ix_platform_notifications_notification_attachments_notification_id'), 'notification_attachments', ['notification_id'], unique=False, schema='platform_notifications')
    op.drop_index(op.f('ix_integrations_marketplace_apps_app_id'), table_name='marketplace_apps', schema='integrations')
    op.drop_table('marketplace_apps', schema='integrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_apps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['marketplace.apps.id'], name=op.f('marketplace_apps_app_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('marketplace_apps_pkey')),
    schema='integrations'
    )
    op.create_index(op.f('ix_integrations_marketplace_apps_app_id'), 'marketplace_apps', ['app_id'], unique=True, schema='integrations')
    op.drop_index(op.f('ix_platform_notifications_notification_attachments_notification_id'), table_name='notification_attachments', schema='platform_notifications')
    op.drop_table('notification_attachments', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_deliveries_queue_id'), table_name='notification_deliveries', schema='platform_notifications')
    op.drop_table('notification_deliveries', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_alerts_notification_logs_notification_id'), table_name='notification_logs', schema='platform_alerts')
    op.drop_table('notification_logs', schema='platform_alerts')
    op.drop_index(op.f('ix_platform_notifications_notification_queue_status'), table_name='notification_queue', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_queue_scheduled_at'), table_name='notification_queue', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_queue_recipient_id'), table_name='notification_queue', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_queue_priority'), table_name='notification_queue', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_queue_organization_id'), table_name='notification_queue', schema='platform_notifications')
    op.drop_table('notification_queue', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_templates_organization_id'), table_name='notification_templates', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_templates_event_id'), table_name='notification_templates', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_templates_deleted_at'), table_name='notification_templates', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_templates_channel'), table_name='notification_templates', schema='platform_notifications')
    op.drop_table('notification_templates', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_preferences_user_id'), table_name='notification_preferences', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_preferences_event_id'), table_name='notification_preferences', schema='platform_notifications')
    op.drop_table('notification_preferences', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_in_app_notifications_user_id'), table_name='in_app_notifications', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_in_app_notifications_organization_id'), table_name='in_app_notifications', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_in_app_notifications_is_read'), table_name='in_app_notifications', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_in_app_notifications_created_at'), table_name='in_app_notifications', schema='platform_notifications')
    op.drop_table('in_app_notifications', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_communications_notification_subscriptions_user_id'), table_name='notification_subscriptions', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_subscriptions_organization_id'), table_name='notification_subscriptions', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_subscriptions_event_id'), table_name='notification_subscriptions', schema='platform_communications')
    op.drop_table('notification_subscriptions', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_group_members_user_id'), table_name='notification_group_members', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_group_members_group_id'), table_name='notification_group_members', schema='platform_communications')
    op.drop_table('notification_group_members', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_digests_user_id'), table_name='notification_digests', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_digests_organization_id'), table_name='notification_digests', schema='platform_communications')
    op.drop_index(op.f('ix_platform_communications_notification_digests_next_run_at'), table_name='notification_digests', schema='platform_communications')
    op.drop_table('notification_digests', schema='platform_communications')
    op.drop_index(op.f('ix_platform_alerts_system_announcements_organization_id'), table_name='system_announcements', schema='platform_alerts')
    op.drop_table('system_announcements', schema='platform_alerts')
    op.drop_index(op.f('ix_platform_webhooks_notification_webhooks_organization_id'), table_name='notification_webhooks', schema='platform_webhooks')
    op.drop_table('notification_webhooks', schema='platform_webhooks')
    op.drop_index(op.f('ix_platform_communications_notification_groups_organization_id'), table_name='notification_groups', schema='platform_communications')
    op.drop_table('notification_groups', schema='platform_communications')
    op.drop_index(op.f('ix_marketplace_marketplace_apps_app_id'), table_name='marketplace_apps', schema='marketplace')
    op.drop_table('marketplace_apps', schema='marketplace')
    op.drop_index(op.f('ix_platform_notifications_notification_events_module'), table_name='notification_events', schema='platform_notifications')
    op.drop_index(op.f('ix_platform_notifications_notification_events_event_key'), table_name='notification_events', schema='platform_notifications')
    op.drop_table('notification_events', schema='platform_notifications')
    op.execute('DROP SCHEMA IF EXISTS platform_webhooks CASCADE')
    op.execute('DROP SCHEMA IF EXISTS platform_alerts CASCADE')
    op.execute('DROP SCHEMA IF EXISTS platform_communications CASCADE')
    op.execute('DROP SCHEMA IF EXISTS platform_notifications CASCADE')
    # ### end Alembic commands ###
