"""add_commercial_inventory_pricing_procurement

Revision ID: cf4fac6c672a
Revises: 73e680f44263
Create Date: 2026-06-21 18:29:27.152143+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_commercial_inventory_pricing_procurement

Revision ID: cf4fac6c672a
Revises: 73e680f44263
Create Date: 2026-06-21 18:29:27.152143+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf4fac6c672a'
down_revision: Union[str, None] = '73e680f44263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS commercial")
    op.execute("CREATE SCHEMA IF NOT EXISTS inventory")
    op.execute("CREATE SCHEMA IF NOT EXISTS pricing")
    op.execute("CREATE SCHEMA IF NOT EXISTS procurement")

    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='commercial'
    )
    op.create_table('service_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('package_name', sa.String(length=150), nullable=False),
    sa.Column('package_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_code'),
    schema='commercial'
    )
    op.create_index(op.f('ix_commercial_service_packages_is_active'), 'service_packages', ['is_active'], unique=False, schema='commercial')
    op.create_index(op.f('ix_commercial_service_packages_organization_id'), 'service_packages', ['organization_id'], unique=False, schema='commercial')
    op.create_table('staff_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    schema='commercial'
    )
    op.create_table('hardware_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='inventory'
    )
    op.create_table('cost_formulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pricing'
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_index('idx_currency_pair', 'currency_rates', ['from_currency', 'to_currency'], unique=False, schema='pricing')
    op.create_table('discount_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('margin_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('minimum_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommended_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maximum_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='pricing'
    )
    op.create_index('idx_pricing_status', 'pricing_rules', ['status'], unique=False, schema='pricing')
    op.create_index(op.f('ix_pricing_pricing_rules_organization_id'), 'pricing_rules', ['organization_id'], unique=False, schema='pricing')
    op.create_table('pricing_simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='pricing',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_pricing_pricing_simulations_created_at'), 'pricing_simulations', ['created_at'], unique=False, schema='pricing')
    op.create_index(op.f('ix_pricing_pricing_simulations_organization_id'), 'pricing_simulations', ['organization_id'], unique=False, schema='pricing')
    op.create_index(op.f('ix_pricing_pricing_simulations_user_id'), 'pricing_simulations', ['user_id'], unique=False, schema='pricing')
    op.create_table('revenue_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='pricing',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_pricing_revenue_forecasts_created_at'), 'revenue_forecasts', ['created_at'], unique=False, schema='pricing')
    op.create_index(op.f('ix_pricing_revenue_forecasts_organization_id'), 'revenue_forecasts', ['organization_id'], unique=False, schema='pricing')
    op.create_table('tax_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_code'),
    schema='pricing'
    )
    op.create_index('idx_tax_country', 'tax_rules', ['country'], unique=False, schema='pricing')
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='procurement'
    )
    op.create_index('idx_vendor_status', 'vendors', ['status'], unique=False, schema='procurement')
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['commercial.service_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_code'),
    schema='commercial'
    )
    op.create_index('idx_service_category', 'services', ['category_id'], unique=False, schema='commercial')
    op.create_index('idx_service_code', 'services', ['service_code'], unique=False, schema='commercial')
    op.create_index(op.f('ix_commercial_services_is_active'), 'services', ['is_active'], unique=False, schema='commercial')
    op.create_index(op.f('ix_commercial_services_organization_id'), 'services', ['organization_id'], unique=False, schema='commercial')
    op.create_table('staff_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['commercial.staff_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='commercial'
    )
    op.create_table('staff_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['commercial.staff_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='commercial'
    )
    op.create_table('hardware_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('replacement_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory.hardware_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code'),
    schema='inventory'
    )
    op.create_index('idx_hardware_status', 'hardware_items', ['status'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_hardware_items_organization_id'), 'hardware_items', ['organization_id'], unique=False, schema='inventory')
    op.create_table('pricing_rule_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing.pricing_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('pricing_rule_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('logical_operator', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing.pricing_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('package_services',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['commercial.service_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['commercial.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'service_id'),
    schema='commercial'
    )
    op.create_table('service_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['commercial.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='commercial'
    )
    op.create_table('hardware_maintenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hardware_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendor', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['inventory.hardware_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('hardware_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('hardware_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['inventory.hardware_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='inventory',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_hardware_movements_org', 'hardware_movements', ['organization_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_hardware_movements_created_at'), 'hardware_movements', ['created_at'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_hardware_movements_organization_id'), 'hardware_movements', ['organization_id'], unique=False, schema='inventory')
    op.create_table('hardware_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hardware_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['inventory.hardware_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('service_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['commercial.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('vendor_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['commercial.services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['procurement.vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='procurement'
    )
    # Create default partition tables
    op.execute("CREATE TABLE inventory.hardware_movements_default PARTITION OF inventory.hardware_movements DEFAULT")
    op.execute("CREATE TABLE pricing.pricing_simulations_default PARTITION OF pricing.pricing_simulations DEFAULT")
    op.execute("CREATE TABLE pricing.revenue_forecasts_default PARTITION OF pricing.revenue_forecasts DEFAULT")


def downgrade() -> None:
    # Drop default partition tables first
    op.execute("DROP TABLE IF EXISTS inventory.hardware_movements_default")
    op.execute("DROP TABLE IF EXISTS pricing.pricing_simulations_default")
    op.execute("DROP TABLE IF EXISTS pricing.revenue_forecasts_default")

    # Drop our created tables
    op.drop_table('vendor_services', schema='procurement')
    op.drop_table('service_pricing', schema='pricing')
    op.drop_table('hardware_stock', schema='inventory')
    op.drop_index(op.f('ix_inventory_hardware_movements_organization_id'), table_name='hardware_movements', schema='inventory')
    op.drop_index(op.f('ix_inventory_hardware_movements_created_at'), table_name='hardware_movements', schema='inventory')
    op.drop_index('idx_hardware_movements_org', table_name='hardware_movements', schema='inventory')
    op.drop_table('hardware_movements', schema='inventory')
    op.drop_table('hardware_maintenance', schema='inventory')
    op.drop_table('service_features', schema='commercial')
    op.drop_table('package_services', schema='commercial')
    op.drop_table('pricing_rule_conditions', schema='pricing')
    op.drop_table('pricing_rule_actions', schema='pricing')
    op.drop_index(op.f('ix_inventory_hardware_items_organization_id'), table_name='hardware_items', schema='inventory')
    op.drop_index('idx_hardware_status', table_name='hardware_items', schema='inventory')
    op.drop_table('hardware_items', schema='inventory')
    op.drop_table('staff_skills', schema='commercial')
    op.drop_table('staff_rates', schema='commercial')
    op.drop_index(op.f('ix_commercial_services_organization_id'), table_name='services', schema='commercial')
    op.drop_index(op.f('ix_commercial_services_is_active'), table_name='services', schema='commercial')
    op.drop_index('idx_service_code', table_name='services', schema='commercial')
    op.drop_index('idx_service_category', table_name='services', schema='commercial')
    op.drop_table('services', schema='commercial')
    op.drop_index('idx_vendor_status', table_name='vendors', schema='procurement')
    op.drop_table('vendors', schema='procurement')
    op.drop_index('idx_tax_country', table_name='tax_rules', schema='pricing')
    op.drop_table('tax_rules', schema='pricing')
    op.drop_index(op.f('ix_pricing_revenue_forecasts_organization_id'), table_name='revenue_forecasts', schema='pricing')
    op.drop_index(op.f('ix_pricing_revenue_forecasts_created_at'), table_name='revenue_forecasts', schema='pricing')
    op.drop_table('revenue_forecasts', schema='pricing')
    op.drop_index(op.f('ix_pricing_pricing_simulations_user_id'), table_name='pricing_simulations', schema='pricing')
    op.drop_index(op.f('ix_pricing_pricing_simulations_organization_id'), table_name='pricing_simulations', schema='pricing')
    op.drop_index(op.f('ix_pricing_pricing_simulations_created_at'), table_name='pricing_simulations', schema='pricing')
    op.drop_table('pricing_simulations', schema='pricing')
    op.drop_index(op.f('ix_pricing_pricing_rules_organization_id'), table_name='pricing_rules', schema='pricing')
    op.drop_index('idx_pricing_status', table_name='pricing_rules', schema='pricing')
    op.drop_table('pricing_rules', schema='pricing')
    op.drop_table('margin_policies', schema='pricing')
    op.drop_table('discount_rules', schema='pricing')
    op.drop_index('idx_currency_pair', table_name='currency_rates', schema='pricing')
    op.drop_table('currency_rates', schema='pricing')
    op.drop_table('cost_formulas', schema='pricing')
    op.drop_table('hardware_categories', schema='inventory')
    op.drop_table('staff_roles', schema='commercial')
    op.drop_index(op.f('ix_commercial_service_packages_organization_id'), table_name='service_packages', schema='commercial')
    op.drop_index(op.f('ix_commercial_service_packages_is_active'), table_name='service_packages', schema='commercial')
    op.drop_table('service_packages', schema='commercial')
    op.drop_table('service_categories', schema='commercial')

    # Drop schemas
    op.execute("DROP SCHEMA IF EXISTS procurement CASCADE")
    op.execute("DROP SCHEMA IF EXISTS pricing CASCADE")
    op.execute("DROP SCHEMA IF EXISTS inventory CASCADE")
    op.execute("DROP SCHEMA IF EXISTS commercial CASCADE")
