"""add_ops_and_tech_services

Revision ID: 5f930bb2dbae
Revises: 1a26d965eae8
Create Date: 2026-06-22 05:06:29.253871+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f930bb2dbae'
down_revision: Union[str, None] = '1a26d965eae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS technology_services")
    op.execute("CREATE SCHEMA IF NOT EXISTS operations_planning")
    op.execute("CREATE SCHEMA IF NOT EXISTS resource_management")
    op.execute("CREATE SCHEMA IF NOT EXISTS deployment_management")
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations_planning'
    )
    op.create_index(op.f('ix_operations_planning_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False, schema='operations_planning')
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number'),
    schema='technology_services'
    )
    op.create_index('idx_request_org_event', 'service_requests', ['organization_id', 'event_id'], unique=False, schema='technology_services')
    op.create_index('idx_request_status', 'service_requests', ['status'], unique=False, schema='technology_services')
    op.create_index(op.f('ix_technology_services_service_requests_event_id'), 'service_requests', ['event_id'], unique=False, schema='technology_services')
    op.create_index(op.f('ix_technology_services_service_requests_organization_id'), 'service_requests', ['organization_id'], unique=False, schema='technology_services')
    op.create_index(op.f('ix_technology_services_service_requests_status'), 'service_requests', ['status'], unique=False, schema='technology_services')
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.UUID(), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_manager_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_request_id'], ['technology_services.service_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code'),
    schema='operations_planning'
    )
    op.create_index('idx_project_org_event', 'projects', ['organization_id', 'event_id'], unique=False, schema='operations_planning')
    op.create_index('idx_project_status', 'projects', ['status'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_projects_event_id'), 'projects', ['event_id'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_projects_organization_id'), 'projects', ['organization_id'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_projects_status'), 'projects', ['status'], unique=False, schema='operations_planning')
    op.create_table('request_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['technology_services.service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technology_services'
    )
    op.create_table('request_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['technology_services.service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'performed_at'),
    schema='technology_services',
    postgresql_partition_by='RANGE (performed_at)'
    )
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('requirement_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['technology_services.service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technology_services'
    )
    op.create_table('service_request_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['commercial.services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_request_id'], ['technology_services.service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technology_services'
    )
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('deployment_number', sa.String(length=50), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=False),
    sa.Column('deployment_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_number'),
    schema='deployment_management'
    )
    op.create_table('readiness_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('technology_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('staff_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('equipment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('network_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_calculated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='deployment_management'
    )
    op.create_index('idx_readiness_score', 'readiness_scores', ['overall_score'], unique=False, schema='deployment_management')
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.String(length=20), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='deployment_management'
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations_planning'
    )
    op.create_index('idx_milestone_status', 'milestones', ['status'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_milestones_status'), 'milestones', ['status'], unique=False, schema='operations_planning')
    op.create_table('equipment_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('hardware_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['inventory.hardware_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_management'
    )
    op.create_table('resource_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_management'
    )
    op.create_index('idx_resource_status', 'resource_allocations', ['status'], unique=False, schema='resource_management')
    op.create_index(op.f('ix_resource_management_resource_allocations_status'), 'resource_allocations', ['status'], unique=False, schema='resource_management')
    op.create_table('resource_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_management'
    )
    op.create_table('staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['commercial.staff_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_management'
    )
    op.create_table('travel_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('hotel', sa.String(length=150), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_management'
    )
    op.create_table('requirement_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['technology_services.requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='technology_services'
    )
    op.create_table('deployment_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment_management.deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='deployment_management'
    )
    op.create_table('deployment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment_management.deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='deployment_management',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_table('project_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['milestone_id'], ['operations_planning.milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['operations_planning.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    schema='operations_planning',
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_task_status', 'project_tasks', ['status'], unique=False, schema='operations_planning')
    op.create_index(op.f('ix_operations_planning_project_tasks_status'), 'project_tasks', ['status'], unique=False, schema='operations_planning')
    
    # Create default partition tables
    op.execute("CREATE TABLE IF NOT EXISTS technology_services.request_history_default PARTITION OF technology_services.request_history DEFAULT")
    op.execute("CREATE TABLE IF NOT EXISTS operations_planning.project_tasks_default PARTITION OF operations_planning.project_tasks DEFAULT")
    op.execute("CREATE TABLE IF NOT EXISTS deployment_management.deployment_logs_default PARTITION OF deployment_management.deployment_logs DEFAULT")
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop default partitions first
    op.execute("DROP TABLE IF EXISTS technology_services.request_history_default")
    op.execute("DROP TABLE IF EXISTS operations_planning.project_tasks_default")
    op.execute("DROP TABLE IF EXISTS deployment_management.deployment_logs_default")

    # Drop tables
    op.drop_table('deployment_logs', schema='deployment_management')
    op.drop_table('deployment_checklists', schema='deployment_management')
    op.drop_table('deployments', schema='deployment_management')
    op.drop_table('readiness_scores', schema='deployment_management')
    op.drop_table('risks', schema='deployment_management')

    op.drop_table('travel_plans', schema='resource_management')
    op.drop_table('staff_assignments', schema='resource_management')
    op.drop_table('equipment_assignments', schema='resource_management')
    op.drop_table('resource_allocations', schema='resource_management')
    op.drop_table('resource_plans', schema='resource_management')

    op.drop_table('task_dependencies', schema='operations_planning')
    op.drop_table('project_tasks', schema='operations_planning')
    op.drop_table('milestones', schema='operations_planning')
    op.drop_table('projects', schema='operations_planning')

    op.drop_table('request_history', schema='technology_services')
    op.drop_table('request_comments', schema='technology_services')
    op.drop_table('requirement_documents', schema='technology_services')
    op.drop_table('requirements', schema='technology_services')
    op.drop_table('service_request_items', schema='technology_services')
    op.drop_table('service_requests', schema='technology_services')

    # Drop schemas
    op.execute("DROP SCHEMA IF EXISTS deployment_management CASCADE")
    op.execute("DROP SCHEMA IF EXISTS resource_management CASCADE")
    op.execute("DROP SCHEMA IF EXISTS operations_planning CASCADE")
    op.execute("DROP SCHEMA IF EXISTS technology_services CASCADE")
    # ### end Alembic commands ###
