"""add_promo_and_payments

Revision ID: 036eeb9fac68
Revises: b657f073d9aa
Create Date: 2026-05-26 03:41:57.507206+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '036eeb9fac68'
down_revision: Union[str, None] = 'b657f073d9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'code', name='_event_promo_code_uc')
    )
    op.create_index(op.f('ix_promo_codes_event_id'), 'promo_codes', ['event_id'], unique=False)
    
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('discount_applied', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['participant_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_event_id'), 'payment_transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_gateway_order_id'), 'payment_transactions', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_gateway_payment_id'), 'payment_transactions', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_promo_code_id'), 'payment_transactions', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_registration_id'), 'payment_transactions', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_registration_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_promo_code_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_gateway_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_gateway_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_event_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_promo_codes_event_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
