"""add_override_metadata_to_feature_overrides

Revision ID: 511d300bd1ba
Revises: b21d79dfbdcf
Create Date: 2026-06-12 20:19:04.246882+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511d300bd1ba'
down_revision: Union[str, None] = 'b21d79dfbdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='logs', schema='audit')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='logs', schema='audit')
    op.create_index(op.f('ix_audit_logs_impersonated_by'), 'logs', ['impersonated_by'], unique=False, schema='audit')
    op.add_column('invoice_items', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False), schema='billing')
    op.add_column('invoices', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False), schema='billing')
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True), schema='billing')
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True), schema='billing')
    op.add_column('organization_feature_overrides', sa.Column('override_by', sa.UUID(), nullable=True), schema='billing')
    op.add_column('organization_feature_overrides', sa.Column('override_at', sa.DateTime(timezone=True), nullable=True), schema='billing')
    op.create_foreign_key(None, 'organization_feature_overrides', 'users', ['override_by'], ['id'], source_schema='billing', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key('fk_session_speakers_presentation_bundle_id', 'session_speakers', 'bundles', ['presentation_bundle_id'], ['id'], source_schema='events', referent_schema='presentations', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_session_speakers_presentation_bundle_id', 'session_speakers', schema='events', type_='foreignkey')
    op.drop_constraint(None, 'organization_feature_overrides', schema='billing', type_='foreignkey')
    op.drop_column('organization_feature_overrides', 'override_at', schema='billing')
    op.drop_column('organization_feature_overrides', 'override_by', schema='billing')
    op.drop_column('invoices', 'paid_at', schema='billing')
    op.drop_column('invoices', 'due_date', schema='billing')
    op.drop_column('invoices', 'currency', schema='billing')
    op.drop_column('invoice_items', 'quantity', schema='billing')
    op.drop_index(op.f('ix_audit_logs_impersonated_by'), table_name='logs', schema='audit')
    op.create_index(op.f('ix_audit_logs_entity_type'), 'logs', ['resource_type'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'logs', ['resource_id'], unique=False, schema='audit')
    # ### end Alembic commands ###
