"""add_phase_6_builder_and_blueprints

Revision ID: 1a26d965eae8
Revises: cf4fac6c672a
Create Date: 2026-06-21 18:40:21.975224+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a26d965eae8'
down_revision: Union[str, None] = 'cf4fac6c672a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS templates")
    op.execute("CREATE SCHEMA IF NOT EXISTS website_builder")
    op.execute("CREATE SCHEMA IF NOT EXISTS blueprints")
    op.execute("CREATE SCHEMA IF NOT EXISTS design_system")
    op.execute("CREATE SCHEMA IF NOT EXISTS theme_engine")
    op.create_table('event_blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('blueprint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='blueprints'
    )
    op.create_index(op.f('ix_blueprints_event_blueprints_industry'), 'event_blueprints', ['industry'], unique=False, schema='blueprints')
    op.create_table('component_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='design_system'
    )
    op.create_table('theme_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='design_system'
    )
    op.create_table('template_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_table('template_marketplace_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='templates'
    )
    op.create_table('blueprint_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.event_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='blueprints'
    )
    op.create_index(op.f('ix_blueprints_blueprint_steps_blueprint_id'), 'blueprint_steps', ['blueprint_id'], unique=False, schema='blueprints')
    op.create_table('design_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='design_system'
    )
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='theme_engine'
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_marketplace', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['templates.template_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_templates_deleted_at'), 'templates', ['deleted_at'], unique=False, schema='templates')
    op.create_index(op.f('ix_templates_templates_slug'), 'templates', ['slug'], unique=False, schema='templates')
    op.create_index(op.f('ix_templates_templates_status'), 'templates', ['status'], unique=False, schema='templates')
    op.create_index(op.f('ix_templates_templates_template_type'), 'templates', ['template_type'], unique=False, schema='templates')
    op.create_index(op.f('ix_templates_templates_visibility'), 'templates', ['visibility'], unique=False, schema='templates')
    op.create_table('theme_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('asset_url', sa.String(length=512), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['theme_engine.themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='theme_engine'
    )
    op.create_index(op.f('ix_theme_engine_theme_assets_theme_id'), 'theme_assets', ['theme_id'], unique=False, schema='theme_engine')
    op.create_table('blueprint_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.event_blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='blueprints'
    )
    op.create_index(op.f('ix_blueprints_blueprint_installations_event_id'), 'blueprint_installations', ['event_id'], unique=False, schema='blueprints')
    op.create_table('blueprint_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.event_blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='blueprints'
    )
    op.create_index(op.f('ix_blueprints_blueprint_templates_blueprint_id'), 'blueprint_templates', ['blueprint_id'], unique=False, schema='blueprints')
    op.create_table('marketplace_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_marketplace_favorites_user_id'), 'marketplace_favorites', ['user_id'], unique=False, schema='templates')
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False, schema='templates')
    op.create_index(op.f('ix_templates_marketplace_listings_template_id'), 'marketplace_listings', ['template_id'], unique=False, schema='templates')
    op.create_table('template_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('dependency_template_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dependency_template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_template_dependencies_template_id'), 'template_dependencies', ['template_id'], unique=False, schema='templates')
    op.create_table('template_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_template_reviews_template_id'), 'template_reviews', ['template_id'], unique=False, schema='templates')
    op.create_table('template_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_template_usage_template_id'), 'template_usage', ['template_id'], unique=False, schema='templates')
    op.create_table('template_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_template_versions_template_id'), 'template_versions', ['template_id'], unique=False, schema='templates')
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_sites_event_id'), 'sites', ['event_id'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_sites_slug'), 'sites', ['slug'], unique=True, schema='website_builder')
    op.create_index(op.f('ix_website_builder_sites_status'), 'sites', ['status'], unique=False, schema='website_builder')
    op.create_table('marketplace_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['templates.marketplace_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_marketplace_purchases_listing_id'), 'marketplace_purchases', ['listing_id'], unique=False, schema='templates')
    op.create_table('template_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('installed_version_id', sa.UUID(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installed_version_id'], ['templates.template_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='templates'
    )
    op.create_index(op.f('ix_templates_template_installations_event_id'), 'template_installations', ['event_id'], unique=False, schema='templates')
    op.create_table('blogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['website_builder.sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_blogs_site_id'), 'blogs', ['site_id'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_blogs_slug'), 'blogs', ['slug'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_blogs_status'), 'blogs', ['status'], unique=False, schema='website_builder')
    op.create_table('navigation_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['website_builder.sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_navigation_menus_site_id'), 'navigation_menus', ['site_id'], unique=False, schema='website_builder')
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('is_homepage', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['website_builder.sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_pages_site_id'), 'pages', ['site_id'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_pages_slug'), 'pages', ['slug'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_pages_status'), 'pages', ['status'], unique=False, schema='website_builder')
    op.create_table('site_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ssl_status', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['website_builder.sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_site_domains_site_id'), 'site_domains', ['site_id'], unique=False, schema='website_builder')
    op.create_index(op.f('ix_website_builder_site_domains_status'), 'site_domains', ['status'], unique=False, schema='website_builder')
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['website_builder.navigation_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['website_builder.menu_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False, schema='website_builder')
    op.create_table('page_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['website_builder.pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_page_assets_page_id'), 'page_assets', ['page_id'], unique=False, schema='website_builder')
    op.create_table('page_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_builder.pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_page_sections_page_id'), 'page_sections', ['page_id'], unique=False, schema='website_builder')
    op.create_table('page_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('styles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['website_builder.page_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='website_builder'
    )
    op.create_index(op.f('ix_website_builder_page_components_section_id'), 'page_components', ['section_id'], unique=False, schema='website_builder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_builder_page_components_section_id'), table_name='page_components', schema='website_builder')
    op.drop_table('page_sections', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_page_assets_page_id'), table_name='page_assets', schema='website_builder')
    op.drop_table('page_assets', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_menu_items_menu_id'), table_name='menu_items', schema='website_builder')
    op.drop_table('menu_items', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_site_domains_status'), table_name='site_domains', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_site_domains_site_id'), table_name='site_domains', schema='website_builder')
    op.drop_table('site_domains', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_pages_status'), table_name='pages', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_pages_slug'), table_name='pages', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_pages_site_id'), table_name='pages', schema='website_builder')
    op.drop_table('pages', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_navigation_menus_site_id'), table_name='navigation_menus', schema='website_builder')
    op.drop_table('navigation_menus', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_blogs_status'), table_name='blogs', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_blogs_slug'), table_name='blogs', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_blogs_site_id'), table_name='blogs', schema='website_builder')
    op.drop_table('blogs', schema='website_builder')
    op.drop_index(op.f('ix_templates_template_installations_event_id'), table_name='template_installations', schema='templates')
    op.drop_table('template_installations', schema='templates')
    op.drop_index(op.f('ix_templates_marketplace_purchases_listing_id'), table_name='marketplace_purchases', schema='templates')
    op.drop_table('marketplace_purchases', schema='templates')
    op.drop_index(op.f('ix_website_builder_sites_status'), table_name='sites', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_sites_slug'), table_name='sites', schema='website_builder')
    op.drop_index(op.f('ix_website_builder_sites_event_id'), table_name='sites', schema='website_builder')
    op.drop_table('sites', schema='website_builder')
    op.drop_index(op.f('ix_templates_template_versions_template_id'), table_name='template_versions', schema='templates')
    op.drop_table('template_versions', schema='templates')
    op.drop_index(op.f('ix_templates_template_usage_template_id'), table_name='template_usage', schema='templates')
    op.drop_table('template_usage', schema='templates')
    op.drop_index(op.f('ix_templates_template_reviews_template_id'), table_name='template_reviews', schema='templates')
    op.drop_table('template_reviews', schema='templates')
    op.drop_index(op.f('ix_templates_template_dependencies_template_id'), table_name='template_dependencies', schema='templates')
    op.drop_table('template_dependencies', schema='templates')
    op.drop_index(op.f('ix_templates_marketplace_listings_template_id'), table_name='marketplace_listings', schema='templates')
    op.drop_index(op.f('ix_templates_marketplace_listings_status'), table_name='marketplace_listings', schema='templates')
    op.drop_table('marketplace_listings', schema='templates')
    op.drop_index(op.f('ix_templates_marketplace_favorites_user_id'), table_name='marketplace_favorites', schema='templates')
    op.drop_table('marketplace_favorites', schema='templates')
    op.drop_index(op.f('ix_blueprints_blueprint_templates_blueprint_id'), table_name='blueprint_templates', schema='blueprints')
    op.drop_table('blueprint_templates', schema='blueprints')
    op.drop_index(op.f('ix_blueprints_blueprint_installations_event_id'), table_name='blueprint_installations', schema='blueprints')
    op.drop_table('blueprint_installations', schema='blueprints')
    op.drop_index(op.f('ix_theme_engine_theme_assets_theme_id'), table_name='theme_assets', schema='theme_engine')
    op.drop_table('theme_assets', schema='theme_engine')
    op.drop_index(op.f('ix_templates_templates_visibility'), table_name='templates', schema='templates')
    op.drop_index(op.f('ix_templates_templates_template_type'), table_name='templates', schema='templates')
    op.drop_index(op.f('ix_templates_templates_status'), table_name='templates', schema='templates')
    op.drop_index(op.f('ix_templates_templates_slug'), table_name='templates', schema='templates')
    op.drop_index(op.f('ix_templates_templates_deleted_at'), table_name='templates', schema='templates')
    op.drop_table('templates', schema='templates')
    op.drop_table('themes', schema='theme_engine')
    op.drop_table('design_tokens', schema='design_system')
    op.drop_index(op.f('ix_blueprints_blueprint_steps_blueprint_id'), table_name='blueprint_steps', schema='blueprints')
    op.drop_table('blueprint_steps', schema='blueprints')
    op.drop_table('template_marketplace_categories', schema='templates')
    op.drop_table('template_categories', schema='templates')
    op.drop_table('theme_presets', schema='design_system')
    op.drop_table('component_library', schema='design_system')
    op.drop_index(op.f('ix_blueprints_event_blueprints_industry'), table_name='event_blueprints', schema='blueprints')
    op.drop_table('event_blueprints', schema='blueprints')
    # ### end Alembic commands ###
