"""add_erp_enterprise_departments_teams_roles

Revision ID: 3c58d14ac972
Revises: phase1_deprecate_org_columns_003
Create Date: 2026-06-21 08:32:13.030842+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c58d14ac972'
down_revision: Union[str, None] = 'phase1_deprecate_org_columns_003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_permissions_code'), 'permissions', ['code'], unique=True, schema='platform')
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_dept_org_code'),
    schema='platform'
    )
    op.create_index('idx_dept_org_code', 'departments', ['organization_id', 'code'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_departments_deleted_at'), 'departments', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_departments_organization_id'), 'departments', ['organization_id'], unique=False, schema='platform')
    op.create_table('department_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['platform.departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'user_id', name='uq_dept_member'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_department_members_deleted_at'), 'department_members', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_department_members_department_id'), 'department_members', ['department_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_department_members_user_id'), 'department_members', ['user_id'], unique=False, schema='platform')
    op.create_table('department_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['platform.departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'department_id', 'code', name='uq_dept_role_org_dept_code'),
    schema='platform'
    )
    op.create_index('idx_dept_role_org_code', 'department_roles', ['organization_id', 'code'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_department_roles_deleted_at'), 'department_roles', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_department_roles_department_id'), 'department_roles', ['department_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_department_roles_organization_id'), 'department_roles', ['organization_id'], unique=False, schema='platform')
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['platform.departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_team_dept_code'),
    schema='platform'
    )
    op.create_index('idx_team_dept_code', 'teams', ['department_id', 'code'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_teams_deleted_at'), 'teams', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_teams_department_id'), 'teams', ['department_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_teams_organization_id'), 'teams', ['organization_id'], unique=False, schema='platform')
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['platform.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['platform.department_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_platform_role_permission'),
    schema='platform'
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['platform.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_team_members_deleted_at'), 'team_members', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_team_members_team_id'), 'team_members', ['team_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_team_members_user_id'), 'team_members', ['user_id'], unique=False, schema='platform')
    op.create_table('user_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['platform.departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['platform.department_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['platform.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', 'team_id', 'role_id', name='uq_user_assignment'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_user_assignments_deleted_at'), 'user_assignments', ['deleted_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_user_assignments_department_id'), 'user_assignments', ['department_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_user_assignments_organization_id'), 'user_assignments', ['organization_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_user_assignments_role_id'), 'user_assignments', ['role_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_user_assignments_team_id'), 'user_assignments', ['team_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_user_assignments_user_id'), 'user_assignments', ['user_id'], unique=False, schema='platform')
    op.alter_column('event_activations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='billing')
    op.drop_index(op.f('ix_invoices_activation_id'), table_name='invoices', schema='billing')
    op.drop_index(op.f('ix_invoices_event_id'), table_name='invoices', schema='billing')
    op.create_index(op.f('ix_billing_invoices_activation_id'), 'invoices', ['activation_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_invoices_event_id'), 'invoices', ['event_id'], unique=False, schema='billing')
    op.drop_index(op.f('ix_organization_addons_activation_id'), table_name='organization_addons', schema='billing')
    op.drop_index(op.f('ix_organization_addons_event_id'), table_name='organization_addons', schema='billing')
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='DEPRECATED: Use billing subscription features/plans',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'max_events',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DEPRECATED: Use billing subscription event limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'max_users',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DEPRECATED: Use billing subscription user limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'max_storage_gb',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DEPRECATED: Use billing subscription storage limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('ticket_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='registration')
    op.alter_column('organizations', 'max_storage_gb',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: Use billing subscription storage limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'max_users',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: Use billing subscription user limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'max_events',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: Use billing subscription event limits',
               existing_nullable=False,
               schema='platform')
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=50),
               comment='DEPRECATED: Use billing subscription features/plans',
               existing_nullable=False,
               schema='platform')
    op.create_index(op.f('ix_organization_addons_event_id'), 'organization_addons', ['event_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_organization_addons_activation_id'), 'organization_addons', ['activation_id'], unique=False, schema='billing')
    op.drop_index(op.f('ix_billing_invoices_event_id'), table_name='invoices', schema='billing')
    op.drop_index(op.f('ix_billing_invoices_activation_id'), table_name='invoices', schema='billing')
    op.create_index(op.f('ix_invoices_event_id'), 'invoices', ['event_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_invoices_activation_id'), 'invoices', ['activation_id'], unique=False, schema='billing')
    op.alter_column('event_activations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('event_activations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False,
               schema='billing')
    op.drop_index(op.f('ix_platform_user_assignments_user_id'), table_name='user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_user_assignments_team_id'), table_name='user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_user_assignments_role_id'), table_name='user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_user_assignments_organization_id'), table_name='user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_user_assignments_department_id'), table_name='user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_user_assignments_deleted_at'), table_name='user_assignments', schema='platform')
    op.drop_table('user_assignments', schema='platform')
    op.drop_index(op.f('ix_platform_team_members_user_id'), table_name='team_members', schema='platform')
    op.drop_index(op.f('ix_platform_team_members_team_id'), table_name='team_members', schema='platform')
    op.drop_index(op.f('ix_platform_team_members_deleted_at'), table_name='team_members', schema='platform')
    op.drop_table('team_members', schema='platform')
    op.drop_table('role_permissions', schema='platform')
    op.drop_index(op.f('ix_platform_teams_organization_id'), table_name='teams', schema='platform')
    op.drop_index(op.f('ix_platform_teams_department_id'), table_name='teams', schema='platform')
    op.drop_index(op.f('ix_platform_teams_deleted_at'), table_name='teams', schema='platform')
    op.drop_index('idx_team_dept_code', table_name='teams', schema='platform')
    op.drop_table('teams', schema='platform')
    op.drop_index(op.f('ix_platform_department_roles_organization_id'), table_name='department_roles', schema='platform')
    op.drop_index(op.f('ix_platform_department_roles_department_id'), table_name='department_roles', schema='platform')
    op.drop_index(op.f('ix_platform_department_roles_deleted_at'), table_name='department_roles', schema='platform')
    op.drop_index('idx_dept_role_org_code', table_name='department_roles', schema='platform')
    op.drop_table('department_roles', schema='platform')
    op.drop_index(op.f('ix_platform_department_members_user_id'), table_name='department_members', schema='platform')
    op.drop_index(op.f('ix_platform_department_members_department_id'), table_name='department_members', schema='platform')
    op.drop_index(op.f('ix_platform_department_members_deleted_at'), table_name='department_members', schema='platform')
    op.drop_table('department_members', schema='platform')
    op.drop_index(op.f('ix_platform_departments_organization_id'), table_name='departments', schema='platform')
    op.drop_index(op.f('ix_platform_departments_deleted_at'), table_name='departments', schema='platform')
    op.drop_index('idx_dept_org_code', table_name='departments', schema='platform')
    op.drop_table('departments', schema='platform')
    op.drop_index(op.f('ix_platform_permissions_code'), table_name='permissions', schema='platform')
    op.drop_table('permissions', schema='platform')
    # ### end Alembic commands ###
