"""create_theme_settings_tables

Revision ID: 0745b6f61ce2
Revises: d04bc82f74ee
Create Date: 2026-06-04 09:25:47.906759+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0745b6f61ce2'
down_revision: Union[str, None] = 'd04bc82f74ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_theme_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('theme_color', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('header_images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=False),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_default_faqs', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('registration_allowed', sa.Boolean(), nullable=False),
    sa.Column('participants_list_allowed', sa.Boolean(), nullable=False),
    sa.Column('payment_enabled', sa.Boolean(), nullable=False),
    sa.Column('active_gateway', sa.String(length=50), nullable=False),
    sa.Column('stripe_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier_cutoffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disabled_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['rbac.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_index(op.f('ix_registration_registration_theme_settings_event_id'), 'registration_theme_settings', ['event_id'], unique=True, schema='registration')
    
    op.create_table('speaker_theme_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('theme_color', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('header_images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=False),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_default_faqs', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('window_required', sa.Boolean(), nullable=False),
    sa.Column('profile_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['rbac.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='speakers'
    )
    op.create_index(op.f('ix_speakers_speaker_theme_settings_event_id'), 'speaker_theme_settings', ['event_id'], unique=True, schema='speakers')
    
    op.alter_column('speaker_profiles', 'photo_consent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='speakers')
    op.alter_column('speaker_profiles', 'last_updated_by',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False,
               schema='speakers')
    op.create_index(op.f('ix_speakers_speaker_profiles_event_id'), 'speaker_profiles', ['event_id'], unique=False, schema='speakers')
    op.create_index(op.f('ix_speakers_speaker_profiles_organization_id'), 'speaker_profiles', ['organization_id'], unique=False, schema='speakers')
    op.create_index(op.f('ix_speakers_speaker_profiles_speaker_id'), 'speaker_profiles', ['speaker_id'], unique=False, schema='speakers')

    # Data Migration: Copy JSONB configurations from events table into the new settings tables
    connection = op.get_bind()
    import json
    import uuid
    from datetime import datetime, timezone
    
    events = connection.execute(
        sa.text("SELECT id, branding_settings, registration_settings, speaker_settings FROM rbac.events")
    ).fetchall()
    
    now = datetime.now(timezone.utc)
    
    for row in events:
        event_id = row[0]
        branding = row[1] or {}
        registration = row[2] or {}
        speaker = row[3] or {}
        
        # Registration Theme Settings
        reg_id = uuid.uuid4()
        theme_color = branding.get("theme_color", "#1A73E8")
        logo_url = branding.get("logo_url")
        banner_url = branding.get("banner_url")
        theme = branding.get("theme", "midnight")
        header_images = json.dumps(branding.get("header_images", []))
        
        terms_and_conditions = registration.get("terms_and_conditions", "")
        faqs = json.dumps(registration.get("faqs", []))
        include_default_faqs = registration.get("include_default_faqs", True)
        
        enabled = registration.get("enabled", True)
        registration_allowed = registration.get("registration_allowed", True)
        participants_list_allowed = registration.get("participants_list_allowed", True)
        
        payment_enabled = registration.get("payment_enabled", False)
        active_gateway = registration.get("active_gateway", "simulated")
        stripe_credentials = json.dumps(registration.get("stripe_credentials", {}))
        tier_cutoffs = json.dumps(registration.get("tier_cutoffs", {}))
        disabled_categories = json.dumps(registration.get("disabled_categories", []))
        
        connection.execute(
            sa.text(
                """
                INSERT INTO registration.registration_theme_settings (
                    id, event_id, theme_color, logo_url, banner_url, theme, header_images,
                    terms_and_conditions, faqs, include_default_faqs, enabled,
                    registration_allowed, participants_list_allowed, payment_enabled,
                    active_gateway, stripe_credentials, tier_cutoffs, disabled_categories,
                    created_at, updated_at
                ) VALUES (
                    :id, :event_id, :theme_color, :logo_url, :banner_url, :theme, :header_images,
                    :terms_and_conditions, :faqs, :include_default_faqs, :enabled,
                    :registration_allowed, :participants_list_allowed, :payment_enabled,
                    :active_gateway, :stripe_credentials, :tier_cutoffs, :disabled_categories,
                    :created_at, :updated_at
                )
                """
            ),
            {
                "id": reg_id,
                "event_id": event_id,
                "theme_color": theme_color,
                "logo_url": logo_url,
                "banner_url": banner_url,
                "theme": theme,
                "header_images": header_images,
                "terms_and_conditions": terms_and_conditions,
                "faqs": faqs,
                "include_default_faqs": include_default_faqs,
                "enabled": enabled,
                "registration_allowed": registration_allowed,
                "participants_list_allowed": participants_list_allowed,
                "payment_enabled": payment_enabled,
                "active_gateway": active_gateway,
                "stripe_credentials": stripe_credentials,
                "tier_cutoffs": tier_cutoffs,
                "disabled_categories": disabled_categories,
                "created_at": now,
                "updated_at": now
            }
        )
        
        # Speaker Theme Settings
        spk_id = uuid.uuid4()
        spk_branding = speaker.get("branding", {})
        spk_theme_color = spk_branding.get("theme_color", "#1A73E8")
        spk_logo_url = spk_branding.get("logo_url")
        spk_banner_url = spk_branding.get("banner_url")
        spk_theme = spk_branding.get("theme", "midnight")
        spk_header_images = json.dumps(spk_branding.get("header_images", []))
        
        spk_terms = speaker.get("terms_and_conditions", "")
        spk_faqs = json.dumps(speaker.get("faqs", []))
        spk_include_default_faqs = speaker.get("include_default_faqs", True)
        
        spk_enabled = speaker.get("enabled", True)
        window_required = speaker.get("window_required", True)
        profile_settings = json.dumps(speaker.get("profile_settings", {}))
        
        connection.execute(
            sa.text(
                """
                INSERT INTO speakers.speaker_theme_settings (
                    id, event_id, theme_color, logo_url, banner_url, theme, header_images,
                    terms_and_conditions, faqs, include_default_faqs, enabled,
                    window_required, profile_settings, created_at, updated_at
                ) VALUES (
                    :id, :event_id, :theme_color, :logo_url, :banner_url, :theme, :header_images,
                    :terms_and_conditions, :faqs, :include_default_faqs, :enabled,
                    :window_required, :profile_settings, :created_at, :updated_at
                )
                """
            ),
            {
                "id": spk_id,
                "event_id": event_id,
                "theme_color": spk_theme_color,
                "logo_url": spk_logo_url,
                "banner_url": spk_banner_url,
                "theme": spk_theme,
                "header_images": spk_header_images,
                "terms_and_conditions": spk_terms,
                "faqs": spk_faqs,
                "include_default_faqs": spk_include_default_faqs,
                "enabled": spk_enabled,
                "window_required": window_required,
                "profile_settings": profile_settings,
                "created_at": now,
                "updated_at": now
            }
        )

    # 6. Drop original JSONB settings columns
    op.drop_column('events', 'speaker_settings', schema='rbac')
    op.drop_column('events', 'branding_settings', schema='rbac')
    op.drop_column('events', 'registration_settings', schema='rbac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Re-add JSONB columns as nullable initially to allow updates
    op.add_column('events', sa.Column('registration_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='rbac')
    op.add_column('events', sa.Column('branding_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='rbac')
    op.add_column('events', sa.Column('speaker_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='rbac')

    # 2. Migrate data back from theme setting tables
    connection = op.get_bind()
    
    # Query registration theme settings
    reg_settings = connection.execute(
        sa.text(
            """
            SELECT event_id, theme_color, logo_url, banner_url, theme, header_images,
                   terms_and_conditions, faqs, include_default_faqs, enabled,
                   registration_allowed, participants_list_allowed, payment_enabled,
                   active_gateway, stripe_credentials, tier_cutoffs, disabled_categories
            FROM registration.registration_theme_settings
            """
        )
    ).fetchall()
    
    # Query speaker theme settings
    spk_settings = connection.execute(
        sa.text(
            """
            SELECT event_id, theme_color, logo_url, banner_url, theme, header_images,
                   terms_and_conditions, faqs, include_default_faqs, enabled,
                   window_required, profile_settings
            FROM speakers.speaker_theme_settings
            """
        )
    ).fetchall()
    
    event_configs = {}
    
    for row in reg_settings:
        ev_id = row[0]
        if ev_id not in event_configs:
            event_configs[ev_id] = {}
        
        event_configs[ev_id]["branding"] = {
            "theme_color": row[1],
            "logo_url": row[2],
            "banner_url": row[3],
            "theme": row[4],
            "header_images": row[5]
        }
        
        event_configs[ev_id]["registration"] = {
            "terms_and_conditions": row[6],
            "faqs": row[7],
            "include_default_faqs": row[8],
            "enabled": row[9],
            "registration_allowed": row[10],
            "participants_list_allowed": row[11],
            "payment_enabled": row[12],
            "active_gateway": row[13],
            "stripe_credentials": row[14],
            "tier_cutoffs": row[15],
            "disabled_categories": row[16]
        }
        
    for row in spk_settings:
        ev_id = row[0]
        if ev_id not in event_configs:
            event_configs[ev_id] = {}
            
        event_configs[ev_id]["speaker"] = {
            "branding": {
                "theme_color": row[1],
                "logo_url": row[2],
                "banner_url": row[3],
                "theme": row[4],
                "header_images": row[5]
            },
            "terms_and_conditions": row[6],
            "faqs": row[7],
            "include_default_faqs": row[8],
            "enabled": row[9],
            "window_required": row[10],
            "profile_settings": row[11]
        }

    import json
    
    for ev_id, configs in event_configs.items():
        branding = json.dumps(configs.get("branding", {
            "theme_color": "#1A73E8",
            "logo_url": None,
            "banner_url": None,
            "theme": "midnight",
            "header_images": []
        }))
        
        registration = json.dumps(configs.get("registration", {
            "terms_and_conditions": "",
            "faqs": [],
            "include_default_faqs": True,
            "enabled": True,
            "registration_allowed": True,
            "participants_list_allowed": True,
            "payment_enabled": False,
            "active_gateway": "simulated",
            "stripe_credentials": {},
            "tier_cutoffs": {},
            "disabled_categories": []
        }))
        
        speaker = json.dumps(configs.get("speaker", {
            "branding": {
                "theme_color": "#1A73E8",
                "logo_url": None,
                "banner_url": None,
                "theme": "midnight",
                "header_images": []
            },
            "terms_and_conditions": "",
            "faqs": [],
            "include_default_faqs": True,
            "enabled": True,
            "window_required": True,
            "profile_settings": {}
        }))
        
        connection.execute(
            sa.text(
                """
                UPDATE rbac.events
                SET branding_settings = :branding,
                    registration_settings = :registration,
                    speaker_settings = :speaker
                WHERE id = :ev_id
                """
            ),
            {
                "branding": branding,
                "registration": registration,
                "speaker": speaker,
                "ev_id": ev_id
            }
        )

    # 3. Alter re-added columns to NOT NULL
    op.alter_column('events', 'registration_settings', existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False, schema='rbac')
    op.alter_column('events', 'branding_settings', existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False, schema='rbac')
    op.alter_column('events', 'speaker_settings', existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False, schema='rbac')

    # 4. Re-add indices and defaults for speaker_profiles
    op.alter_column('speaker_profiles', 'photo_consent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='speakers')
    op.alter_column('speaker_profiles', 'last_updated_by',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'organiser'::character varying"),
               existing_nullable=False,
               schema='speakers')
    op.drop_index(op.f('ix_speakers_speaker_profiles_speaker_id'), table_name='speaker_profiles', schema='speakers')
    op.drop_index(op.f('ix_speakers_speaker_profiles_organization_id'), table_name='speaker_profiles', schema='speakers')
    op.drop_index(op.f('ix_speakers_speaker_profiles_event_id'), table_name='speaker_profiles', schema='speakers')

    # 5. Drop registration_theme_settings and speaker_theme_settings
    op.drop_index(op.f('ix_speakers_speaker_theme_settings_event_id'), table_name='speaker_theme_settings', schema='speakers')
    op.drop_table('speaker_theme_settings', schema='speakers')
    op.drop_index(op.f('ix_registration_registration_theme_settings_event_id'), table_name='registration_theme_settings', schema='registration')
    op.drop_table('registration_theme_settings', schema='registration')
    # ### end Alembic commands ###
