"""remove_file_format_constraint

Revision ID: 4f24d2e30552
Revises: 2270540c135f
Create Date: 2026-05-07 16:46:10.793311+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f24d2e30552'
down_revision: Union[str, None] = '2270540c135f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_runtime_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('runtime_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forensic_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_runtime_events_correlation_id'), 'room_runtime_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_room_runtime_events_device_id'), 'room_runtime_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_room_runtime_events_event_type'), 'room_runtime_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_room_runtime_events_occurred_at'), 'room_runtime_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_room_runtime_events_session_id'), 'room_runtime_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_room_runtime_events_severity'), 'room_runtime_events', ['severity'], unique=False)
    op.create_table('sync_transfer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('transfer_status', sa.String(length=50), nullable=False),
    sa.Column('bytes_transferred', sa.Integer(), nullable=False),
    sa.Column('bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('cloud_hash', sa.String(length=64), nullable=False),
    sa.Column('local_hash', sa.String(length=64), nullable=True),
    sa.Column('hash_match', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_transfer_logs_file_id'), 'sync_transfer_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_sync_transfer_logs_job_id'), 'sync_transfer_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_sync_transfer_logs_occurred_at'), 'sync_transfer_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_sync_transfer_logs_transfer_status'), 'sync_transfer_logs', ['transfer_status'], unique=False)
    op.create_table('venue_network_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_percent', sa.Float(), nullable=True),
    sa.Column('bandwidth_mbps', sa.Float(), nullable=True),
    sa.Column('local_ip', postgresql.INET(), nullable=True),
    sa.Column('gateway_reachable', sa.Boolean(), nullable=False),
    sa.Column('internet_reachable', sa.Boolean(), nullable=False),
    sa.Column('diagnostic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_network_events_device_id'), 'venue_network_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_venue_network_events_event_type'), 'venue_network_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_venue_network_events_occurred_at'), 'venue_network_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_venue_network_events_venue_id'), 'venue_network_events', ['venue_id'], unique=False)
    op.create_table('venue_security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evidence_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_user', sa.String(length=100), nullable=True),
    sa.Column('screenshot_ref', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_security_events_device_id'), 'venue_security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_venue_security_events_event_type'), 'venue_security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_venue_security_events_occurred_at'), 'venue_security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_venue_security_events_severity'), 'venue_security_events', ['severity'], unique=False)
    op.drop_table('system_error_logs_y2026m05')
    op.drop_table('playback_events_y2026m03')
    op.drop_table('playback_events_y2026m01')
    op.drop_table('websocket_events_y2026m01')
    op.drop_table('system_error_logs_y2026m03')
    op.drop_table('websocket_events_y2026m06')
    op.drop_table('playback_events_default')
    op.drop_table('device_heartbeats_y2026m06')
    op.drop_table('playback_events_y2026m06')
    op.drop_table('device_heartbeats_y2026m02')
    op.drop_table('websocket_events_default')
    op.drop_table('audit_logs_y2026m04')
    op.drop_table('audit_logs_y2026m03')
    op.drop_table('device_heartbeats_y2026m03')
    op.drop_table('api_request_logs_y2026m01')
    op.drop_table('websocket_events_y2026m04')
    op.drop_table('system_error_logs_y2026m02')
    op.drop_table('audit_logs_y2026m05')
    op.drop_table('system_error_logs_y2026m01')
    op.drop_table('api_request_logs_default')
    op.drop_table('api_request_logs_y2026m02')
    op.drop_table('api_request_logs_y2026m04')
    op.drop_table('api_request_logs_y2026m05')
    op.drop_table('device_heartbeats_y2026m04')
    op.drop_table('device_heartbeats_y2026m05')
    op.drop_table('playback_events_y2026m02')
    op.drop_table('websocket_events_y2026m05')
    op.drop_table('device_heartbeats_y2026m01')
    op.drop_table('audit_logs_default')
    op.drop_table('playback_events_y2026m05')
    op.drop_table('websocket_events_y2026m03')
    op.drop_table('audit_logs_y2026m02')
    op.drop_table('websocket_events_y2026m02')
    op.drop_table('system_error_logs_y2026m06')
    op.drop_table('system_error_logs_default')
    op.drop_table('api_request_logs_y2026m03')
    op.drop_table('system_error_logs_y2026m04')
    op.drop_table('audit_logs_y2026m01')
    op.drop_table('playback_events_y2026m04')
    op.drop_table('audit_logs_y2026m06')
    op.drop_table('device_heartbeats_default')
    op.drop_table('api_request_logs_y2026m06')
    op.alter_column('api_request_logs', 'db_query_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_request_logs', 'db_query_duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_request_logs', 'request_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('api_request_logs', 'response_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_api_request_logs_correlation_id'), 'api_request_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_method'), 'api_request_logs', ['method'], unique=False)
    op.create_index(op.f('ix_api_request_logs_occurred_at'), 'api_request_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_path'), 'api_request_logs', ['path'], unique=False)
    op.create_index(op.f('ix_api_request_logs_request_id'), 'api_request_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_status_code'), 'api_request_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_api_request_logs_user_id'), 'api_request_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_correlation', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.create_index('ix_audit_logs_event_occurred', 'audit_logs', ['event_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.alter_column('device_heartbeats', 'memory_used_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'memory_total_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'disk_free_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'is_compromised',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_device_health_trend', 'device_heartbeats', ['device_id', 'occurred_at', 'health_score'], unique=False)
    op.create_index(op.f('ix_device_heartbeats_device_id'), 'device_heartbeats', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeats_occurred_at'), 'device_heartbeats', ['occurred_at'], unique=False)
    op.alter_column('file_integrity_logs', 'storage_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_file_integrity_logs_file_id'), 'file_integrity_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_integrity_logs_occurred_at'), 'file_integrity_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_file_integrity_logs_stage'), 'file_integrity_logs', ['stage'], unique=False)
    op.create_foreign_key(None, 'file_integrity_logs', 'presentation_files', ['file_id'], ['id'], ondelete='CASCADE')
    op.alter_column('file_validations', 'antivirus_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_file_validations_md5_hash'), 'file_validations', ['md5_hash'], unique=False)
    op.create_index(op.f('ix_file_validations_sha256_hash'), 'file_validations', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_notification_events_channel'), 'notification_events', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_events_correlation_id'), 'notification_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_notification_events_occurred_at'), 'notification_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_notification_events_recipient_id'), 'notification_events', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notification_events_status'), 'notification_events', ['status'], unique=False)
    op.alter_column('playback_events', 'is_fullscreen',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('playback_events', 'is_offline',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_playback_events_action'), 'playback_events', ['action'], unique=False)
    op.create_index(op.f('ix_playback_events_correlation_id'), 'playback_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_playback_events_device_id'), 'playback_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_playback_events_file_id'), 'playback_events', ['file_id'], unique=False)
    op.create_index(op.f('ix_playback_events_occurred_at'), 'playback_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_playback_events_playback_session_id'), 'playback_events', ['playback_session_id'], unique=False)
    op.create_index(op.f('ix_playback_events_session_id'), 'playback_events', ['session_id'], unique=False)
    op.create_index('ix_playback_session_timeline', 'playback_events', ['playback_session_id', 'occurred_at'], unique=False)
    op.create_foreign_key(None, 'playback_events', 'room_devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'playback_events', 'presentation_queue', ['playback_session_id'], ['id'])
    op.alter_column('room_devices', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('room_devices', 'trust_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('room_devices', 'compromise_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('room_devices', 'sync_latency_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('room_devices', 'ip_address')
    op.create_index(op.f('ix_security_events_correlation_id'), 'security_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_id'), 'security_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_ip_address'), 'security_events', ['ip_address'], unique=False)
    op.create_index('ix_security_events_ip_at', 'security_events', ['ip_address', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_risk_level'), 'security_events', ['risk_level'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_error_logs_correlation_id'), 'system_error_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_error_logs_exception_type'), 'system_error_logs', ['exception_type'], unique=False)
    op.create_index(op.f('ix_system_error_logs_occurred_at'), 'system_error_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_system_error_logs_request_id'), 'system_error_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_error_logs_severity'), 'system_error_logs', ['severity'], unique=False)
    op.drop_index('ix_srr_activity_logs_action', table_name='venue_activity_logs')
    op.drop_index('ix_srr_activity_logs_event_id', table_name='venue_activity_logs')
    op.drop_index('ix_srr_activity_logs_occurred_at', table_name='venue_activity_logs')
    op.drop_index('ix_srr_activity_logs_speaker_id', table_name='venue_activity_logs')
    op.drop_index('ix_srr_activity_logs_station_id', table_name='venue_activity_logs')
    op.create_index(op.f('ix_venue_activity_logs_action'), 'venue_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_venue_activity_logs_event_id'), 'venue_activity_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_venue_activity_logs_occurred_at'), 'venue_activity_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_venue_activity_logs_speaker_id'), 'venue_activity_logs', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_venue_activity_logs_station_id'), 'venue_activity_logs', ['station_id'], unique=False)
    op.alter_column('venue_sync_jobs', 'bytes_transferred',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('venue_sync_jobs', 'checksum_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venue_sync_jobs', 'storage_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_venue_sync_jobs_correlation_id'), 'venue_sync_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_venue_sync_jobs_request_id'), 'venue_sync_jobs', ['request_id'], unique=False)
    op.create_index(op.f('ix_websocket_events_action'), 'websocket_events', ['action'], unique=False)
    op.create_index(op.f('ix_websocket_events_channel_name'), 'websocket_events', ['channel_name'], unique=False)
    op.create_index(op.f('ix_websocket_events_connection_id'), 'websocket_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_websocket_events_device_id'), 'websocket_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_websocket_events_occurred_at'), 'websocket_events', ['occurred_at'], unique=False)
    op.alter_column('worker_job_logs', 'memory_usage_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index('ix_worker_job_latency', 'worker_job_logs', ['task_name', 'wait_duration_ms'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_correlation_id'), 'worker_job_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_job_id'), 'worker_job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_queue'), 'worker_job_logs', ['queue'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_status'), 'worker_job_logs', ['status'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_task_name'), 'worker_job_logs', ['task_name'], unique=False)
    op.create_index(op.f('ix_worker_job_logs_worker_name'), 'worker_job_logs', ['worker_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_job_logs_worker_name'), table_name='worker_job_logs')
    op.drop_index(op.f('ix_worker_job_logs_task_name'), table_name='worker_job_logs')
    op.drop_index(op.f('ix_worker_job_logs_status'), table_name='worker_job_logs')
    op.drop_index(op.f('ix_worker_job_logs_queue'), table_name='worker_job_logs')
    op.drop_index(op.f('ix_worker_job_logs_job_id'), table_name='worker_job_logs')
    op.drop_index(op.f('ix_worker_job_logs_correlation_id'), table_name='worker_job_logs')
    op.drop_index('ix_worker_job_latency', table_name='worker_job_logs')
    op.alter_column('worker_job_logs', 'memory_usage_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_websocket_events_occurred_at'), table_name='websocket_events')
    op.drop_index(op.f('ix_websocket_events_device_id'), table_name='websocket_events')
    op.drop_index(op.f('ix_websocket_events_connection_id'), table_name='websocket_events')
    op.drop_index(op.f('ix_websocket_events_channel_name'), table_name='websocket_events')
    op.drop_index(op.f('ix_websocket_events_action'), table_name='websocket_events')
    op.drop_index(op.f('ix_venue_sync_jobs_request_id'), table_name='venue_sync_jobs')
    op.drop_index(op.f('ix_venue_sync_jobs_correlation_id'), table_name='venue_sync_jobs')
    op.alter_column('venue_sync_jobs', 'storage_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'R2'::character varying"),
               existing_nullable=False)
    op.alter_column('venue_sync_jobs', 'checksum_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('venue_sync_jobs', 'bytes_transferred',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_venue_activity_logs_station_id'), table_name='venue_activity_logs')
    op.drop_index(op.f('ix_venue_activity_logs_speaker_id'), table_name='venue_activity_logs')
    op.drop_index(op.f('ix_venue_activity_logs_occurred_at'), table_name='venue_activity_logs')
    op.drop_index(op.f('ix_venue_activity_logs_event_id'), table_name='venue_activity_logs')
    op.drop_index(op.f('ix_venue_activity_logs_action'), table_name='venue_activity_logs')
    op.create_index('ix_srr_activity_logs_station_id', 'venue_activity_logs', ['station_id'], unique=False)
    op.create_index('ix_srr_activity_logs_speaker_id', 'venue_activity_logs', ['speaker_id'], unique=False)
    op.create_index('ix_srr_activity_logs_occurred_at', 'venue_activity_logs', ['occurred_at'], unique=False)
    op.create_index('ix_srr_activity_logs_event_id', 'venue_activity_logs', ['event_id'], unique=False)
    op.create_index('ix_srr_activity_logs_action', 'venue_activity_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_system_error_logs_severity'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_request_id'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_occurred_at'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_exception_type'), table_name='system_error_logs')
    op.drop_index(op.f('ix_system_error_logs_correlation_id'), table_name='system_error_logs')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_risk_level'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index('ix_security_events_ip_at', table_name='security_events')
    op.drop_index(op.f('ix_security_events_ip_address'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_correlation_id'), table_name='security_events')
    op.add_column('room_devices', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True))
    op.alter_column('room_devices', 'sync_latency_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('room_devices', 'compromise_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('room_devices', 'trust_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'TRUSTED'::character varying"),
               existing_nullable=False)
    op.alter_column('room_devices', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'100'::double precision"),
               existing_nullable=False)
    op.drop_constraint(None, 'playback_events', type_='foreignkey')
    op.drop_constraint(None, 'playback_events', type_='foreignkey')
    op.drop_index('ix_playback_session_timeline', table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_session_id'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_playback_session_id'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_occurred_at'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_file_id'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_device_id'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_correlation_id'), table_name='playback_events')
    op.drop_index(op.f('ix_playback_events_action'), table_name='playback_events')
    op.alter_column('playback_events', 'is_offline',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('playback_events', 'is_fullscreen',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_events_status'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_recipient_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_occurred_at'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_correlation_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_channel'), table_name='notification_events')
    op.drop_index(op.f('ix_file_validations_sha256_hash'), table_name='file_validations')
    op.drop_index(op.f('ix_file_validations_md5_hash'), table_name='file_validations')
    op.alter_column('file_validations', 'antivirus_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'CLEAN'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'file_integrity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_file_integrity_logs_stage'), table_name='file_integrity_logs')
    op.drop_index(op.f('ix_file_integrity_logs_occurred_at'), table_name='file_integrity_logs')
    op.drop_index(op.f('ix_file_integrity_logs_file_id'), table_name='file_integrity_logs')
    op.alter_column('file_integrity_logs', 'storage_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_heartbeats_occurred_at'), table_name='device_heartbeats')
    op.drop_index(op.f('ix_device_heartbeats_device_id'), table_name='device_heartbeats')
    op.drop_index('ix_device_health_trend', table_name='device_heartbeats')
    op.alter_column('device_heartbeats', 'is_compromised',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'disk_free_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'memory_total_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('device_heartbeats', 'memory_used_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_correlation', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'INFO'::character varying"),
               nullable=True)
    op.drop_index(op.f('ix_api_request_logs_user_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_status_code'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_request_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_path'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_occurred_at'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_method'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_correlation_id'), table_name='api_request_logs')
    op.alter_column('api_request_logs', 'response_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('api_request_logs', 'request_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('api_request_logs', 'db_query_duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('api_request_logs', 'db_query_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_table('api_request_logs_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m06_pkey')
    )
    op.create_table('device_heartbeats_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_default_pkey')
    )
    op.create_table('audit_logs_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m06_pkey')
    )
    op.create_table('playback_events_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m04_pkey')
    )
    op.create_table('audit_logs_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m01_pkey')
    )
    op.create_table('system_error_logs_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m04_pkey')
    )
    op.create_table('api_request_logs_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m03_pkey')
    )
    op.create_table('system_error_logs_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_default_pkey')
    )
    op.create_table('system_error_logs_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m06_pkey')
    )
    op.create_table('websocket_events_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m02_pkey')
    )
    op.create_table('audit_logs_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m02_pkey')
    )
    op.create_table('websocket_events_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m03_pkey')
    )
    op.create_table('playback_events_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m05_pkey')
    )
    op.create_table('audit_logs_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_default_pkey')
    )
    op.create_table('device_heartbeats_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m01_pkey')
    )
    op.create_table('websocket_events_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m05_pkey')
    )
    op.create_table('playback_events_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m02_pkey')
    )
    op.create_table('device_heartbeats_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m05_pkey')
    )
    op.create_table('device_heartbeats_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m04_pkey')
    )
    op.create_table('api_request_logs_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m05_pkey')
    )
    op.create_table('api_request_logs_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m04_pkey')
    )
    op.create_table('api_request_logs_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m02_pkey')
    )
    op.create_table('api_request_logs_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_default_pkey')
    )
    op.create_table('system_error_logs_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m01_pkey')
    )
    op.create_table('audit_logs_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m05_pkey')
    )
    op.create_table('system_error_logs_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m02_pkey')
    )
    op.create_table('websocket_events_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m04_pkey')
    )
    op.create_table('api_request_logs_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('db_query_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('db_query_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rate_limit_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='api_request_logs_y2026m01_pkey')
    )
    op.create_table('device_heartbeats_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m03_pkey')
    )
    op.create_table('audit_logs_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m03_pkey')
    )
    op.create_table('audit_logs_y2026m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='audit_logs_y2026m04_pkey')
    )
    op.create_table('websocket_events_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_default_pkey')
    )
    op.create_table('device_heartbeats_y2026m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m02_pkey')
    )
    op.create_table('playback_events_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m06_pkey')
    )
    op.create_table('device_heartbeats_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_used_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('memory_total_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('disk_free_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps_telemetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_latency_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_compromised', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tamper_indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='device_heartbeats_y2026m06_pkey')
    )
    op.create_table('playback_events_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_default_pkey')
    )
    op.create_table('websocket_events_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m06_pkey')
    )
    op.create_table('system_error_logs_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m03_pkey')
    )
    op.create_table('websocket_events_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('disconnect_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='websocket_events_y2026m01_pkey')
    )
    op.create_table('playback_events_y2026m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m01_pkey')
    )
    op.create_table('playback_events_y2026m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playback_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_fullscreen', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_offline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('render_timing_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_load_at_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='playback_events_y2026m03_pkey')
    )
    op.create_table('system_error_logs_y2026m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='system_error_logs_y2026m05_pkey')
    )
    op.drop_index(op.f('ix_venue_security_events_severity'), table_name='venue_security_events')
    op.drop_index(op.f('ix_venue_security_events_occurred_at'), table_name='venue_security_events')
    op.drop_index(op.f('ix_venue_security_events_event_type'), table_name='venue_security_events')
    op.drop_index(op.f('ix_venue_security_events_device_id'), table_name='venue_security_events')
    op.drop_table('venue_security_events')
    op.drop_index(op.f('ix_venue_network_events_venue_id'), table_name='venue_network_events')
    op.drop_index(op.f('ix_venue_network_events_occurred_at'), table_name='venue_network_events')
    op.drop_index(op.f('ix_venue_network_events_event_type'), table_name='venue_network_events')
    op.drop_index(op.f('ix_venue_network_events_device_id'), table_name='venue_network_events')
    op.drop_table('venue_network_events')
    op.drop_index(op.f('ix_sync_transfer_logs_transfer_status'), table_name='sync_transfer_logs')
    op.drop_index(op.f('ix_sync_transfer_logs_occurred_at'), table_name='sync_transfer_logs')
    op.drop_index(op.f('ix_sync_transfer_logs_job_id'), table_name='sync_transfer_logs')
    op.drop_index(op.f('ix_sync_transfer_logs_file_id'), table_name='sync_transfer_logs')
    op.drop_table('sync_transfer_logs')
    op.drop_index(op.f('ix_room_runtime_events_severity'), table_name='room_runtime_events')
    op.drop_index(op.f('ix_room_runtime_events_session_id'), table_name='room_runtime_events')
    op.drop_index(op.f('ix_room_runtime_events_occurred_at'), table_name='room_runtime_events')
    op.drop_index(op.f('ix_room_runtime_events_event_type'), table_name='room_runtime_events')
    op.drop_index(op.f('ix_room_runtime_events_device_id'), table_name='room_runtime_events')
    op.drop_index(op.f('ix_room_runtime_events_correlation_id'), table_name='room_runtime_events')
    op.drop_table('room_runtime_events')
    # ### end Alembic commands ###
