# app/modules/platform/roles/constants.py

ACCESS_LEVEL_GLOBAL = "GLOBAL"
ACCESS_LEVEL_DEPARTMENT = "DEPARTMENT"
ACCESS_LEVEL_TEAM = "TEAM"
ACCESS_LEVEL_SELF = "SELF"

ACCESS_LEVELS = [
    ACCESS_LEVEL_GLOBAL,
    ACCESS_LEVEL_DEPARTMENT,
    ACCESS_LEVEL_TEAM,
    ACCESS_LEVEL_SELF
]
