"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Search, ShieldCheck, Star, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/lib/api-client";
import { EmptyState, ErrorState, EvidenceTime, LoadingState, Metric, PageFrame, Section, StatusBadge, formatBytes } from "@/components/operations/control-room";

type Content = { id: string; name: string; type: string; size_bytes: number; version: number; approval_status: string; delivery_status: string; local_cache_path?: string; uploaded_at?: string; synced_at?: string; job?: { status: string; priority: number; retry_count: number; error?: string } };

export default function ContentPage() {
  const client = useQueryClient(); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState("");
  const query = useQuery({ queryKey: ["venue-content"], queryFn: () => apiClient.get<{ items: Content[] }>("/venue/admin/control/content"), refetchInterval: 12000 });
  const command = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => apiClient.post(`/venue/admin/control/commands/content/${id}`, { command: action, reason: `Content control: ${action}` }), onSuccess: () => { toast.success("Content command queued"); client.invalidateQueries({ queryKey: ["venue-content"] }); }, onError: (error: Error) => toast.error(error.message) });
  const all = query.data?.items || []; const items = useMemo(() => all.filter((item) => (filter === "all" || item.delivery_status === filter || (filter === "failed" && item.job?.status === "failed")) && item.name.toLowerCase().includes(search.toLowerCase())), [all, filter, search]);
  const totalBytes = all.reduce((sum, item) => sum + item.size_bytes, 0); const delivered = all.filter((item) => item.delivery_status === "synced").length; const failed = all.filter((item) => item.delivery_status === "failed" || item.job?.status === "failed").length;
  return <PageFrame eyebrow="Verified local media" title="Content delivery" description="Track every approved file from source version to verified local availability." actions={<button className="venue-button venue-button--secondary" onClick={() => query.refetch()}><RefreshCw className="size-4" />Refresh</button>}>
    <div className="venue-metric-grid"><Metric label="Current assets" value={all.length} detail={formatBytes(totalBytes)} /><Metric label="Delivered" value={delivered} detail="Verified local cache records" state={all.length && delivered === all.length ? "healthy" : "degraded"} /><Metric label="Pending" value={all.filter((item) => item.delivery_status === "pending").length} detail="Awaiting local delivery" /><Metric label="Failed" value={failed} detail="Requires operator action" state={failed ? "degraded" : "healthy"} /></div>
    <Section title="Asset ledger" description={`${items.length} matching current versions`}><div className="venue-toolbar"><div className="relative min-w-72 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-[var(--muted)]" /><input className="venue-input pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search file name" /></div><select className="venue-input !w-44" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All assets</option><option value="pending">Pending</option><option value="synced">Delivered</option><option value="failed">Failures</option><option value="quarantined">Quarantined</option></select></div>
      {query.isLoading && <LoadingState />}{query.isError && <ErrorState message={(query.error as Error).message} retry={() => query.refetch()} />}{!query.isLoading && items.length === 0 && <EmptyState title="No matching content" detail="Approved current versions appear when event content has been synchronized." />}
      {items.length > 0 && <div className="venue-table-wrap"><table className="venue-table"><thead><tr><th>Asset</th><th>Approval</th><th>Delivery</th><th>Size / version</th><th>Transfer evidence</th><th>Observed</th><th>Commands</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><div className="venue-code">{item.type}</div></td><td><StatusBadge state={item.approval_status} /></td><td><StatusBadge state={item.delivery_status} evidence={item.job?.error} /></td><td>{formatBytes(item.size_bytes)}<div className="venue-code">Version {item.version}</div></td><td>{item.job ? <><StatusBadge state={item.job.status} /><div className="venue-code">Priority {item.job.priority} · {item.job.retry_count} retries</div></> : <StatusBadge state="not_configured" />}</td><td><EvidenceTime value={item.synced_at || item.uploaded_at} /></td><td><div className="flex gap-1"><button title="Fetch or retry" className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => command.mutate({ id: item.id, action: item.job?.status === "failed" ? "retry" : "fetch" })}><UploadCloud className="size-3.5" /></button><button title="Prioritize" className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => command.mutate({ id: item.id, action: "prioritize" })}><Star className="size-3.5" /></button><button title="Verify" className="venue-button venue-button--secondary !h-8 !px-2" onClick={() => command.mutate({ id: item.id, action: "verify" })}><ShieldCheck className="size-3.5" /></button></div></td></tr>)}</tbody></table></div>}
    </Section>
  </PageFrame>;
}
